### ISSUE TITLE
YYModel支持泛型吗

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYKit#100]
json是个2纬的。想问下支持泛型吗。貌似不能直接转。
homemodel里面emotion_groups貌似是字典。是需要我手动在转一次吗？

@interface ViralImageAlbums : NSObject

@property (nonatomic, strong) NSString *insertTime;
@property (nonatomic, strong) NSString *viralImageAlbumsIdentifier;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSString *viralImageAlbumsDescription;
@property (nonatomic, strong) NSString *image;

@end

@interface HomeModel : NSObject

@property (nonatomic, strong) NSArray <EmotionGroups *> *emotion_groups;

**Comment by 597579501** [comment]
补充。。上面的写错了。
@property (nonatomic, strong) NSArray <EmotionGroups *> *emotion_groups;我定义成这样

**Comment by ibireme** [comment]
见 Readme：https://github.com/ibireme/YYModel#容器类属性
