### ISSUE TITLE
YYTimer 死锁问题

### ISSUE THREAD

**Issue by maquanhong** [ibireme/YYKit#101]
self.timer = [[YYTimer alloc] initWithFireTime:0 interval:1 target:self selector:@selector(enableVerifiCode) repeats:YES];
在enableVerifiCode方法中调用timer的invalidate 方法必会死锁。
目前以self.timer setValue:[NSNumber numberWithBool:NO] forKey:@"_repeats"];此方式来结束定时器。
请考虑能否暴露可以直接修改的属性。或者是因为本人对代码不了解。

**Comment by ibireme** [comment]
Fixed
