### ISSUE TITLE
请教YYKit中Weibo的Demo中表情键盘不会被第三方键盘覆盖的方法

### ISSUE THREAD

**Issue by ainopara** [ibireme/YYKit#104]
如Stackoverflow里[这个问题](http://stackoverflow.com/questions/28854831/custom-keyboard-covers-standard-inputview)所描述的现象，使用第三方键盘的情况下，将textView的inputView设置为自己制作的表情键盘，会在展示表情键盘后1秒之内切换回第三方键盘。

我从Reveal中观察了一下，这个时候表情键盘仍然存在，只是被打断了与parentView的AutoLayout约束，且宽度被设置为0。所以这个情况虽然看起来是第三方键盘覆盖了表情键盘，实际上是表情键盘被第三方挤走了。

我观察了其他app对表情键盘的处理，发现大部分app在打开表情键盘的时候，textView的光标消失了，推测是通过resignFirstResponder的方式避免第三方键盘的弹出，并手动将表情键盘加入到当前View中。

唯独YYKit中Weibo的Demo是使用了inputView来展示表情键盘的，且这个表情键盘不会被第三方键盘挤走。（确切说是，将表情键盘View赋值inputView后，并没有第三方键盘弹出，所以表情键盘view可以完好地留在那里）

我一开始以为是YYText的原因，但在手动将我自己的表情键盘中UITextView的替换为YYTextView后，并没有解决这个问题。

所以这里想请教一下YYKit中Weibo的Demo中表情键盘不会被第三方键盘覆盖，是有意为止还是无心插柳？如果是有意为止，关键点在什么地方？

非常感谢。

**Comment by ibireme** [comment]
这里是参考了苹果官方文档关于 inputView/reloadInputViews 的接口用法：
[UIResponder inputView](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIResponder_Class/#//apple_ref/occ/instp/UIResponder/inputView)  、 [TextAndWebiPhoneOS inputViews](https://developer.apple.com/library/prerelease/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/InputViews/InputViews.html)

用起来一切都是正常表现，没有遇到什么问题。。

**Comment by ainopara** [comment]
在我的项目中点击表情键盘按钮（将textView的inputView设置为我的表情键盘并reload），表情键盘先是正常加载，随后不知道基于iOS系统的什么机制，表情键盘消失，取而代之的是原来的第三方键盘。（这个问题只在用户使用第三方键盘的情况下出现），这个时候即使resign掉textView的firstResponder，再点击textView依然会重复这个过程，既先出现表情键盘，随后被第三方键盘替代。
另外这个状态下，textView的inputView依然是我的表情键盘，但此时UI上展示的第三方键盘可以正常输入文字。这时第三方键盘点击小地球图标切换输入法的时候，切换实际上会后台起作用，只是UI上仍然是当前第三方键盘，直到将textView的inputView设置为nil并reload后UI上的键盘才会切过去。
种种迹象让我觉得这个问题是iOS的bug，但这个问题似乎从iOS8到现在一直存在，这么长时间苹果没有要修的意思。再加上YYKit的Demo中没这个问题，搞的我也开始怀疑是不是我哪里没配置好。
这个是表情键盘被第三方键盘替代后的frame：
```
(lldb) po self.replyController.inputView
<UIView: 0x130bd7e90; frame = (0 -306; 0 55); autoresize = W+H; layer = <CALayer: 0x12f702ce0>>
```
最后感谢您的回复，我会继续调查这个问题，如果有新的发现会在这里告知。

**Comment by ainopara** [comment]
找到原因了。如果inputview设置为由一个viewcontroller管理的view，就会出现上述现象。

YYKit的Demo中，表情键盘继承自UIView，所以无论是系统键盘还是第三方键盘都可以正常使用。

我想这个问题应该暂且算是解决了，我也准备将自己继承自ViewController的表情键盘改为用UIView实现。

再次感谢您的回复。

**Comment by bycc070809** [comment]
hi  我也碰到这个情况  但是 我的 inputview设置的不是由viewcontroller管理的view  

如下
EmoticonInputView *v = [EmoticonInputView sharedView];
_textView.inputView = v;

**Comment by ainopara** [comment]
@bycc070809 看样子你这里是一个 `sharedView` 你试试自己手动 alloc init 一个，出来后不要让 `inputView` 以外的指针强引用它行不行。

**Comment by bycc070809** [comment]
很奇怪  我就是拿作者的例子来修改的
