### ISSUE TITLE
YYCache 缓存问题

### ISSUE THREAD

**Issue by badoychen** [ibireme/YYKit#107]
YYCache的内存怎么越使越大，设置了上限，但是wal文件一直只增不减

**Comment by ibireme** [comment]
内存缓存限制应该是准确的，wal 文件是磁盘缓存。

wal 文件是 SQLite 的 WAL 机制产生的，SQLite 会自动进行同步和合并的，具体情况可以在网上搜索`SQLite WAL` 相关的技术文章了解一下，比如[这一篇](http://blog.csdn.net/dyllove98/article/details/8841973)。

**Comment by ibireme** [comment]
嗯。。这块儿可以做一下优化，在清除缓存时强制同步一下。。

**Comment by badoychen** [comment]
回复好快啊：）

**Comment by ibireme** [comment]
已调整。
