### ISSUE TITLE
关于动态行距的控制

### ISSUE THREAD

**Issue by bycc070809** [ibireme/YYKit#109]
Hi，ibireme 有个问题请教一下 就是yytext 里动态控制行距 例如朋友圈的评论一条评论内的换行 和 评论和评论之间的行距是不一样的  你有什么好的思路 如图
![4 pic](https://cloud.githubusercontent.com/assets/1911364/12948788/47670c44-d03f-11e5-8950-b81effe9e076.jpg)

不甚感激！！！！

**Comment by ibireme** [comment]
可以调整 lineSpacing，但不能准确控制换行处位置。也可以用多余换行符号，并设置较小字体来实现。
但是朋友圈这个，每个评论都是单独的 Label，并不是通过调整行距实现的。
