### ISSUE TITLE
继承自自定义的父类后，解析出现问题。

### ISSUE THREAD

**Issue by bensonday** [ibireme/YYKit#110]
定义了一个父类，如 base.h ，并声明了几个属性。继承该类的子类在解析后，父类的属性并没有赋值。
这个如何解决？ 这个问题在不同的工程里有时候会出现，有时候不出现。

**Comment by ibireme** [comment]
这是在用什么功能时出现的问题？

**Comment by bensonday** [comment]
```
@interface HEPBaseYYModel : NSObject<YYModel>
@property (assign, nonatomic) NSInteger errCode;
@property (copy, nonatomic) NSString * errMsg;
@end
```
```
#import "HEPBaseYYModel.h"
@interface HEPTest : HEPBaseYYModel
@property (nonatomic, copy) NSString *content;
@end
```

**Comment by ibireme** [comment]
@interface HEPBaseYYModel : NSObject<YYModel>
    @property (assign, nonatomic) NSInteger errCode;
    @property (copy, nonatomic)   NSString *errMsg;
    @end

    @implementation HEPBaseYYModel
    @end

    @interface HEPTest : HEPBaseYYModel
    @property (nonatomic, copy) NSString *content;
    @end

    @implementation HEPTest
    + (NSDictionary *)modelCustomPropertyMapper {
        return @{
            @"errCode" : @"result",
            @"errMsg" : @"msg",
            @"content" : @"content",
        };
    }
    @end

    void test() {
        HEPTest *test = [HEPTest modelWithJSON:@"{\"result\":1,\"msg\":\"success\",\"content\":\"发布成功\"}"];
        NSLog(@"test:%d,%@,%@",test.errCode, test.errMsg, test.content);
    }

打印结果：

    2016-02-18 10:36:13.660 YYKitDemo[4671:236055] test:1,success,发布成功

上面这块儿代码没问题啊。。是不是编译选项开了 release 模式或者设置的编译优化，导致在 Xcode 调试时看不到值啊？

**Comment by bensonday** [comment]
没有开启release模式和设置的编译优化， 确实是解析不出来。比较诡异的是在另外一个工程却是可以正常解析的，但是写法完全一样。

**Comment by ibireme** [comment]
如果不能复现的话，我也没办法。这个项目的 TestCase 写的还是比较全面的，在逻辑上应该不会出这种问题。我只能提几个建议了：

1. 用 NSLog 把属性打印出来看一下。
2. 打印一下原始的 JSON 或 Dictionary 数据。
3. 对比一下两个工程的代码和项目配置，看看哪些地方不一样（比如基类的实现、项目的其它设置等）。

**Comment by bensonday** [comment]
好的。谢谢。
