### ISSUE TITLE
YYLabel使用YYTextBorder问题

### ISSUE THREAD

**Issue by JarhomChen** [ibireme/YYKit#111]
![qq20160216-0 2x](https://cloud.githubusercontent.com/assets/3068840/13074367/1f70bf24-d4df-11e5-86a1-eb5012dd4a9b.png)
##   当 border.insets.top <=  border.strokeWidth 时，上边框会显示不完整，请问大神怎么解决这个问题？

    
    NSMutableAttributedString *one = [[NSMutableAttributedString alloc] initWithString:@"Another Link"];
    one.font = [UIFont systemFontOfSize:13];
    one.color = UIColorFromRGB(0x5a5a5a);
    
    YYTextBorder *border = [YYTextBorder new];
    border.cornerRadius = 6;
    border.insets = UIEdgeInsetsMake(0, -10, -5, -10);
    border.strokeWidth = 2;
    border.strokeColor = one.color;
    border.lineStyle = YYTextLineStyleSingle;
    one.textBackgroundBorder = border;
    
    YYLabel *label = [YYLabel new];
    label.attributedText = one;
    label.textAlignment = NSTextAlignmentCenter;
    label.numberOfLines = 2;
    label.backgroundColor = [UIColor yellowColor];
    [self.view addSubview:label];
    __weak typeof(self)weakSelf = self;
    [label mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(weakSelf.view).with.insets(UIEdgeInsetsMake(0, 0, 0, 0));
    }];

**Comment by ibireme** [comment]
YYLabel 是把文本渲染成图片显示的，所以超出 YYLabel frame 范围的东西都会被裁掉。
这只能用 textContainerInsets 之类的属性，为文本增加额外的边缘留白了。
