### ISSUE TITLE
YYTextView 的UIMenuController不显示

### ISSUE THREAD

**Issue by BestKai** [ibireme/YYKit#113]
我是这样写的YYTextView。输入内容后长按，选择菜单不显示

![294869cd-7282-4591-9650-afdc1bcee74b](https://cloud.githubusercontent.com/assets/8436462/13278567/71d416c0-db0c-11e5-9195-d1efd6771d56.png)

**Comment by ibireme** [comment]
没能复现。
最好能贴一下更完整的代码或是Demo，说明一下设备、系统版本。

**Comment by maiqili** [comment]
我这边好像也试过有同样的问题

**Comment by goodbless** [comment]
我这里也出现了类似的问题，只要是弹出了Actionsheet后，再长按YYTextView，就不会弹出菜单了

**Comment by goodbless** [comment]
以及找到了问题，是YYTextEffectWindow导致的，原因如下:
当ActionSheet弹出时，他的window的level高于YYTextEffectWindow的level，当Actionsheet结束，dismiss时，他的window会把YYTextEffectWindow设为KeyWindow，这时候，UIMenuController就不会再显示了，我会提交一个mergeRequest
