### ISSUE TITLE
使用`YYPhotoGroupView`浏览大图过程中tableView发生滚动问题

### ISSUE THREAD

**Issue by lynn87** [ibireme/YYKit#114]
你好，向你请教个问题，大体看了`YYPhotoGroupView`实现，在缩略图和全屏大图之间的动画效果用了当前屏幕截屏作为背景，但是有一种场景这种做法会出现问题，比如聊天列表，在浏览大图的时候对方给我发送了消息导致列表滚动，原先的缩略图位置发生了变化，会导致动画出现问题，如果缩略图不发生重用的情况下问题也好解决，不做截屏，直接做动画即可，因为还是能通过传进去的缩略图imageView对象拿到缩略图控件变化后的frame，但是如果缩略图imageView控件已经被重用，这个时候会比较麻烦，因为这时候取到的frame已经不是原先点击进来的缩略图，而是另一张缩略图了，这种情况应该怎么处理好呢？能否赐教一个好的思路，谢谢啦！O(∩_∩)O~

**Comment by ibireme** [comment]
这个大概可以加一些判断逻辑和控制方法，让出线那种情况时，直接走个渐隐动画消失，或者再重新获取缩略图位置。

YYPhotoGroupView 只是个简单的 Demo 里的东西，没考虑更多的情况。

**Comment by lynn87** [comment]
好的，感谢回复。
