### ISSUE TITLE
Interface Builder  build failed 

### ISSUE THREAD

**Issue by gaoxiao228** [ibireme/YYKit#115]
更新了新版1.0  就会出现这样的问题.. 
![5e7cb5b7-1a35-49c3-90ff-e43369dea1e9](https://cloud.githubusercontent.com/assets/1780502/13377688/6c878e2e-de20-11e5-99b4-5b31d7b99b4b.png)

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYKit/commit/dd9d436b63c5316541c25828099ea9f0717507af
