### ISSUE TITLE
YYLabel的autolayout兼容问题

### ISSUE THREAD

**Issue by ldasein** [ibireme/YYKit#116]
在同时使用YYLabel和autolayout进行编写图文混排界面的时候，目前发现只能使用那种把label的宽高都先计算的约束方式，不支持设定好内容然后根据内容自动计算宽高的功能。

而系统的UILabel是支持自动计算宽高的

**Comment by ibireme** [comment]
更新到最新代码试试。

如果不行，设置一下 label.preferredMaxLayoutWidth。

如果还不行，取一下  label.intrinsicContentSize。

**Comment by ldasein** [comment]
我是用的是pod上的最新版，0.9.11，而不是目前的1.0.2。
至少在0.9.11上面yylabel直接就不支持preferredMaxLayoutWidth这个属性，直接报错。原生的UILabel可以设置这个属性。
通过CGSize size = [label intrinsicContentSize];的方法发现在相同NSAttributeString的情况和约束下yylabel的size是
(width = -1, height = -1)
 (width = -1, height = -1)，
而原生的UIlabel的size则是
(width = 153, height = 33.5)
 (width = 153, height = 33.5)

第一次看到宽高还能为负数。。。
估计是因为这个导致的不显示吧

**Comment by ibireme** [comment]
1.0 以前，不支持 AutoLayout。

**Comment by ldasein** [comment]
那赶紧把cocoapods上的版本升级到最新吧

**Comment by ibireme** [comment]
几天前就发布出去了：
http://cocoapods.org/?q=YYKit 
http://cocoapods.org/?q=YYText

你该更新下 CocoaPods 列表了

**Comment by ldasein** [comment]
我在终端运行
pod search yykit
-> YYKit (0.9.11)
   A collection of iOS components.
   pod 'YYKit', '~> 0.9.11'
   - Homepage: https://github.com/ibireme/YYKit
   - Source:   https://github.com/ibireme/YYKit.git
   - Versions: 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3,
   0.9.2, 0.9.1, 0.9.0, 0.2.0 [master repo]
   - Subspecs:
     - YYKit/no-arc (0.9.11)
``

我还以为一直没有更新呢，刚刚试了试直接运行pod update是正常的，可以升级，这个地方也更新一下吧

**Comment by ibireme** [comment]
执行 `pod setup` 来更新本地列表

**Comment by ldasein** [comment]
升级到1.0之后问题解决，可以支持autolayout了

还有就是我的意思是执行`pod search yykit`的时候仍然显示最新版本是0.9.11，这个地方请更新一下

**Comment by ibireme** [comment]
搜索是 CocoaPods 自己本身的功能，我发布出去了，你没有搜到，那你应该执行 `pod setup` 来更新你电脑上的索引。这个，我是改不了的。。

**Comment by ldasein** [comment]
多谢了，看来我还是不太明白cocoapods的原理。
