### ISSUE TITLE
多维数组dictionary为model的问题

### ISSUE THREAD

**Issue by luoshihui** [ibireme/YYKit#118]
+ (NSArray *)yy_modelArrayWithClass:(Class)cls array:(NSArray *)arr 方法中仅处理了arr中单层的dictionary, 如果array中还有嵌套array, 这时候array就会被忽略掉, 而且最终返回的结果的层次也会乱掉.
故最好用递归对多维array做处理, 谢谢.
+ (NSArray *)yy_modelArrayWithClass:(Class)cls array:(NSArray *)arr {
    if (!cls || !arr) return nil;
    NSMutableArray *result = [NSMutableArray new];
    for (NSDictionary *dic in arr) {
		if ([dic isKindOfClass:[NSDictionary class]]) {
			NSObject *obj = [cls yy_modelWithDictionary:dic];
			if (obj) [result addObject:obj];
		}else  if ([dic isKindOfClass:[NSArray class]]) {
			NSArray *arr = [self yy_modelArrayWithClass:cls array:(NSArray*)dic];
			if (arr) [result addObject:arr];
		}else {
			continue;
		}
    }
    return result;
}

**Comment by ibireme** [comment]
在 NSArray 和 NSDictionary 上那两个扩展方法，只是很简单的假定传入参数也是单层的 NSArray 或 NSDictionary，返回值也是全部都是同一类型的对象。如果递归处理，就有可能会破坏这个返回类型的期望。

你可以在别处加一个 category 方法，例如 `recursiveModelArrayWithClass `，与这个方法区分开避免产生混淆。
