### ISSUE TITLE
有个奇怪的行为想请教下

### ISSUE THREAD

**Issue by CodeEagle** [ibireme/YYKit#119]
![image](https://cloud.githubusercontent.com/assets/2311352/13452220/e2e5e748-e080-11e5-9898-931f3a7c7ede.png)

如上图，`UITableViewCell`里面有两个`YYLabel`，在初始化的时候添加了`YYLabel`的`layer`
`contentView.layer.addSublayer(_titleNode.layer)`
但是在`Reveal`上看到的却是`YYLabel`的`view`
就想请教下哪里出问题了。

**Comment by ibireme** [comment]
我猜，也许 Reveal 是遍历的 CALayer tree，然后如果能从 layer.delegate 取到 UIView，那就用 UIView 作为数据？

**Comment by CodeEagle** [comment]
可能是吧，苹果自带的也是同样的结果。
