### ISSUE TITLE
是否有方法可以获取到设备当前的网速？

### ISSUE THREAD

**Issue by DeveloperLx** [ibireme/YYKit#12]
是否有方法可以获取到设备当前的网速？即上传速度和下载速度？希望添加到UIDevice+YYAdd的#pragma mark - Network Information 中，谢谢！（除了真的用一个测试文件上传/下载，然后体积/用时的这种方法外）

**Comment by ibireme** [comment]
网络传输速度不是一个实时的值，只能定时获取全部的流量，与时间差进行计算来获得一小段时间内的平均网速。

加了一个小方法到 UIDevice+YYAdd, 使用方法见注释。

**Comment by DeveloperLx** [comment]
强大👍
