### ISSUE TITLE
YYLabel显示不完整

### ISSUE THREAD

**Issue by lexiaoyao20** [ibireme/YYKit#120]
看了你的Weibo的那个Demo，有个问题需要向你请教一下：
用户名后面有VIP和蓝V之类的图标，但是如果用户名很长，超过了给YYTextContainer设置的最大长度，后面的图标就看不到了，
能不能做到  用户名... <图标> 这种形式展示啊？？

**Comment by ibireme** [comment]
可以试试 `lineBreakMode = NSLineBreakByTruncatingMiddle`，这样当超过长度时，会保留两遍，只把中间部分换成 `...`。

如果要精确控制 `...` 出现的位置，那可能需要创建两个 Label，分别显示名字和后面的图标。

**Comment by lexiaoyao20** [comment]
谢了，我还是采用中间显示 `...` 这种方案算了。
