### ISSUE TITLE
你好  我想问一下weibo feed列表为什么视频播放不了呢

### ISSUE THREAD

**Issue by maibou8888** [ibireme/YYKit#121]

**Comment by ibireme** [comment]
没处理视频的数据和事件。。
毕竟那只是个用于演示的 Demo，视频做起来太复杂而且无关紧要。。

**Comment by maibou8888** [comment]
你好 在匹配表情的时候range.location -= emoClipLength;  然后又emoClipLength += range.length - 1;  我想问一下这是在做什么

**Comment by ibireme** [comment]
原本是 `[大笑]` 这样4个字符的文本，被替换为 `😄` 这样的一个字符的文本，这里需要计算一下被裁剪掉的文本长度。

**Comment by maibou8888** [comment]
好的  谢谢
