### ISSUE TITLE
YYCGUtilities.m 中的 YYCGRectFitWithContentMode()方法有一些问题

### ISSUE THREAD

**Issue by enrecul** [ibireme/YYKit#123]
case UIViewContentModeScaleAspectFit: 时；
应该是这样才对吧。if else 内语句要对换一下。
if (mode == UIViewContentModeScaleAspectFit) {
                    if (size.width / size.height < rect.size.width / rect.size.height) {
                        scale = rect.size.width / size.width;
                    } else {
                        scale = rect.size.height / size.height;
                    }
                }

**Comment by ibireme** [comment]
没没问。。现在用到这个方法的地方也都没问题。。

这个方法的注释倒是有问题，我改了一下：https://github.com/ibireme/YYKit/commit/75d4e3b086b08063637adce22669e94f48bb0e15
