### ISSUE TITLE
YY, UIImage+YYAdd.m 128行的代码问题。

### ISSUE THREAD

**Issue by Gainell** [ibireme/YYKit#124]
UIImage *image = image = [UIImage imageWithCGImage:decoded scale:scale orientation:UIImageOrientationUp];

这是多写了一个“image＝”吧 。

**Comment by ibireme** [comment]
是写多了。。
Fixed: https://github.com/ibireme/YYKit/commit/6ce0ceb414491c594f51f2c0507959fbd3eae499
