### ISSUE TITLE
WBStatusComposeViewController.m 中在init方法中执行[[YYTextKeyboardManager defaultManager] addObserver:self]会有潜在问题

### ISSUE THREAD

**Issue by goodbless** [ibireme/YYKit#126]
您好，我在研究您的YYKit的Demo并仿照其中的代码实现我自己的类似微博的功能。
我在仿照您Demo中的WBStatusComposeViewController来写我自己的一个微博编辑界面时，遇到一个问题，我在进入这个编辑界面之前的界面（之后称为A界面A），也是有输入框的，并且会在viewWillDisappear中dismiss掉键盘。

这时候，如我在A界面，并且键盘处于弹出状态，这时候我进入到编辑界面(nav push)。会100%出现崩溃。

定位到代码如下，`[YYTextKeyboardManager  _notifyAllObservers]:`
```ObjectiveC
if (!CGRectEqualToRect(trans.toFrame, _fromFrame)) {
    for (id<YYTextKeyboardObserver> observer in _observers) {
        if ([observer respondsToSelector:@selector(keyboardChangedWithTransition:)]) {
            [observer keyboardChangedWithTransition:trans];
        }
    }
}
```
抛出的的异常是 `Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <NSConcreteHashTable: 0x7ae78650> was mutated while being enumerated.'`
也就是说_observers数组在遍历过程中有变动。经过排查发现原因如下：

上面的循环过程中，调用了我编辑界面的` keyboardChangedWithTransition: `方法。
```ObjectiveC
- (void)keyboardChangedWithTransition:(YYTextKeyboardTransition)transition {
    CGRect toFrame = [[YYTextKeyboardManager defaultManager] convertRect:transition.toFrame toView:self.view];
    if (transition.animationDuration == 0) {
        _vwToolBar.bottom = CGRectGetMinY(toFrame);
    } else {
        [UIView animateWithDuration:transition.animationDuration delay:0 options:transition.animationOption | UIViewAnimationOptionBeginFromCurrentState animations:^{
            _vwToolBar.bottom = CGRectGetMinY(toFrame);
        } completion:NULL];
    }
}
```

上面一段代码中第一行的`self.view`触发了`viewDidLoad`方法，其中又调用了`[YYTextView new]`，而YYTextView在init的过程中，会调用`[[YYTextKeyboardManager defaultManager] addObserver]`。而此时，上面`_notifyAllObservers`方法中的循环还在进行中，所以会导致异常。

这个问题可以通过修改代码执行顺序来简单规避，比如讲在`init`中调用的`addObserver`方法移到`[YYTextView new]`的后面。但Demo工程目前的写法确实会给使用者带来一定的误导，而且YYTextView是隐式的在初始化过程中将自己注册为observer的，在界面层级复杂时确实会给Debug带来一定麻烦。

更好的解决方案还是修改`[YYTextKeyboardManager  _notifyAllObservers]:`方法，在遍历_observers之前，拷贝一个不可变副本，遍历这个副本，从而避免上面的风险。

**Comment by ibireme** [comment]
稍后改一下 YYTextKeyboardManager 这块儿～

**Comment by goodbless** [comment]
又发现了新的问题，如果按照后一种方式，对_observers进行拷贝，确实不会崩溃了。但由于还是在`init`中进行的`addObserver`,在view真正显示在屏幕上之前，就触发了`keyboardChangedWithTransition:`，这时候self.view的真正frame还未确定，`[[YYTextKeyboardManager defaultManager] convertRect:transition.toFrame toView:self.view]`方法返回的rect是不正确的，导致界面控件错位，跑到屏幕下面去了，看来`addObserver`的位置还是要考虑。

**Comment by ibireme** [comment]
上面那个问题已经 fixed。
下面这个 convert 的方法，只能在 view 放入 window 后才能计算正确。。
