### ISSUE TITLE
请问如何将大图浏览的向上拖拽退出手势禁用.发现会导致导航栏和tabbar闪动明显

### ISSUE THREAD

**Issue by sixleaves** [ibireme/YYKit#128]
请问如何将大图浏览的向上拖拽退出手势禁用.发现会导致导航栏和tabbar闪动明显

**Comment by ibireme** [comment]
是说 YYPhotoGroupView 这各类吗？这各类 .m 的结尾处有个 pan: 方法，你可以修改一下这个方法，或者直接禁用这个 gesture。

另外，这各类是属于 Demo 项目，仅用于演示，我不会在这上面做太多维护工作。

**Comment by sixleaves** [comment]
好的, 十分谢谢~~~
