### ISSUE TITLE
YYModel是否可以支持Realm的自定义RLMArray<Class> 类型（类似泛型）

### ISSUE THREAD

**Issue by HeroOnline** [ibireme/YYKit#129]
Realm框架： https://github.com/realm/realm-cocoa

#import <Foundation/Foundation.h>
#import <Realm/Realm.h>

// 注意这里 ！！！
 RLM_ARRAY_TYPE(Dog)

@interface Person : RLMObject
@property(nonatomic, copy) NSString      *name;
// 类似泛型 // YYKit # Model 解析报错
 @property(nonatomic, strong) RLMArray<Dog> *dogs;

// NSMutableArray
//@property (nonatomic, strong) NSMutableArray *dogs;

//@property (nonatomic, strong) NSArray *dogs;

// All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'

// 不支持 NSArray，只能支持 RLMArray

@end

**Comment by ibireme** [comment]
RLMArray 是继承自 NSObject，本身并不是 iOS 系统的 Array 类型。
除非我这边引入 Realm 并针对这个类型做特殊处理，否则是不可能支持这种类型的。

**Comment by caoway** [comment]
这你只能自己处理，缓存层和网络层不要耦合， 建议建2个模型 中间做transform

**Comment by caoway** [comment]
YY大神好勤快啊 每条issue都这么认真的回复

**Comment by HeroOnline** [comment]
亲，可以有什么更好的解决方案，提供支持吗？ 因为不可能Realm 改变了，Realm并没有直接支持 NSArray ，YYModel是否可以提供一种自定义特殊容器类型，然后特殊处理吗？

**Comment by HeroOnline** [comment]
这你只能自己处理，缓存层和网络层不要耦合， 建议建2个模型 中间做transform ， 我知道可以这种方式转换可以解决，之前Android使用 Ormlite 也是采取这种方式，但是，现在的团队的同事建议，iOS是否不要采取这种方式，因为需要再多一倍的Model， 网络层：Model ，一个是数据库层：Model

**Comment by HeroOnline** [comment]
YY亲，因为Realm这种发展趋势，会越来越广泛，同时YYKit也是越来越使用广泛，YY亲，提供特殊处理，更方便大家开发

**Comment by ibireme** [comment]
如果说仅仅是为了兼容 Realm，而让其他没有用到 Realm 的人被迫引入这样一个几兆的库，这是不能接受的。

既然你希望用 Realm，那应该试试基于 Realm 的扩展，比如 [Realm-JSON](https://github.com/matthewcheok/Realm-JSON)。

**Comment by HeroOnline** [comment]
从框架架构设计来说，不必要用到Realm就被迫引入Realm；单独隔离出来对 Realm的扩展，不错的想法

**Comment by HeroOnline** [comment]
YY亲，大概多久可以扩展出来  Realm-JSON 对 Realm 支持

**Comment by ibireme** [comment]
https://github.com/matthewcheok/Realm-JSON
