### ISSUE TITLE
请问YYCGImageXXXXXX的解码为什么占用了这么多CPU时间, 有没有好的优化方式....

### ISSUE THREAD

**Issue by sixleaves** [ibireme/YYKit#130]
请问YYCGImage的解码为什么占用了这么多CPU时间, 有没有好的优化方式....
<img width="489" alt="7e2894a6-2218-4ca6-b0a1-9498db23e29e" src="https://cloud.githubusercontent.com/assets/3601210/13730046/eef16e2a-e97e-11e5-99be-94da4885448b.png">

**Comment by ibireme** [comment]
把图片显示到屏幕上，解码这一步肯定是少不了的，即使不在这个方法里解码，那提交给 GPU 显示时，也会发生解码。

唯一能优化的就是尽量缓存解码后的图片，尽量让解码在后台线程进行。
