### ISSUE TITLE
既然 [UIImage imageNamed:xxx]  这个方法是有缓存的，那么为什么在 Weibo Demo 中还需要把 image 放入 cache？

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYKit#131]
您在 [iOS 处理图片的一些小 Tip](http://blog.ibireme.com/2015/11/02/ios_image_tips/) 一文中提到：**"通过 imageNamed 创建 UIImage 时，系统实际上只是在 Bundle 内查找到文件名，然后把这个文件名放到 UIImage 里返回，并没有进行实际的文件读取和解码。当 UIImage 第一次显示到屏幕上时，其内部的解码方法才会被调用，同时解码结果会保存到一个全局缓存去。据我观察，在图片解码后，App 第一次退到后台和收到内存警告时，该图片的缓存才会被清空，其他情况下缓存会一直存在。"**

但是这 weibo 的这个 demo 中，我发现您在用 name 去 image 的时候依然使用了手动 cache，不太理解，还请指教。

代码如下：

```objc
+ (UIImage *)imageNamed:(NSString *)name {
  if (!name) return nil;
  UIImage *image = [[self imageCache] objectForKey:name];
  if (image) return image;
  image = [UIImage imageNamed:name];
  if (!image) return nil;
  [[self imageCache] setObject:image forKey:name];
  return image;
}
```

**Comment by ibireme** [comment]
之前这里面可能有一些从其它 bundle 获取的资源，但是实际上并没有用到。。所以这个 Cache 没什么意义。。

**Comment by KittenYang** [comment]
@ibireme  恩，好的。
