### ISSUE TITLE
WBStatusHelper

### ISSUE THREAD

**Issue by shaozl** [ibireme/YYKit#133]
/**
 很多都写死单例了，毕竟只是 Demo。。
 */
@interface WBStatusHelper : NSObject

看到您加了这个注释，请问您 如果不是demo，您打算用什么方法来替代单例模式呢？

**Comment by ibireme** [comment]
实际开发时，表情之类的东西是动态加载的，不能直接那样写死。这里并不是说单例模式不好。。
