### ISSUE TITLE
尝试使用 YYDiskCache 做持久化遇到的一个疑问

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYKit#134]
您好，我尝试使用 YYDiskCache 给网络请求到的微博数据做持久化，我是直接存的 layout 对象，所以必须给 layout 类实现 NSCoding 方法，layout 还有 status ,status 里又有 user，所以每个类我都要实现 NSCoding 方法，繁多的属性重复同一句代码麻烦不说，关键我发现再次打开从磁盘读取的速度非常慢。我不知道是不是我不应该直接存 layout 这个自定义对象，而是应该存基本数据类型（NSString *name,NSString *text ....）这些到数据库，然后每次从数据库读取这些基本类型后再算出相应的 layout。另外我使用的是 Swift 进行开发，但我感觉关系不大。还望指点。

**Comment by ibireme** [comment]
用 Instruments 分析一下，看看耗时在哪里。

一般来说，Archive/Unarchive  确实比较慢，而且还需要消耗更多的磁盘空间和 I/O。

**Comment by KittenYang** [comment]
恩，实测发现都消耗在了 Archive/Unarchive 上了。然后我阅读了下 diskCache 的源码，之后又对比了 FMDB，有一点非常疑惑。
首先，您在存简单数据`(NSNumber)`的时候，做法是用 `[NSKeyedArchiver archivedDataWithRootObject:object] ` 把 object 转成 NSData（实际上我发现你把所有 object 都转成了 NSData），然后统一使用 `sqlite3_bind_blob(stmt, 7, extendedData.bytes, (int)extendedData.length, 0);` 进行数据库存储。但就像你说的：
>"Archive/Unarchive 确实比较慢，而且还需要消耗更多的磁盘空间和 I/O。"

所以我又去翻看了[FMDB](https://github.com/ccgus/fmdb) 的源码，发现它进行了区分：
```objc
    else if ([obj isKindOfClass:[NSNumber class]]) {
        if (strcmp([obj objCType], @encode(char)) == 0) {
            sqlite3_bind_int(pStmt, idx, [obj charValue]);
        }
        else if (strcmp([obj objCType], @encode(unsigned char)) == 0) {
            sqlite3_bind_int(pStmt, idx, [obj unsignedCharValue]);
        }
        else if (strcmp([obj objCType], @encode(short)) == 0) {
            sqlite3_bind_int(pStmt, idx, [obj shortValue]);
        }
        else if (strcmp([obj objCType], @encode(unsigned short)) == 0) {
            sqlite3_bind_int(pStmt, idx, [obj unsignedShortValue]);
        }
        else if (strcmp([obj objCType], @encode(int)) == 0) {
            sqlite3_bind_int(pStmt, idx, [obj intValue]);
        }
        .....
```
可以看到，FMDB 对于基本类型的 object 存储的都是基本类型本身。
这方面还请 YY 解惑一下。

**Comment by ibireme** [comment]
FMDB 这块儿是对应 sqlite 某一个表的特定的一行，而且这行的数据类型应该是 INT，这是建表时就需要确定下来的。如果这时传入的 NSNumber 是个 float 类型，那这里就会丢失精度。

YYKVStorage 需要支持任意类型的数据，所以这里用的是 BLOB 类型，存储的数据是二进制的。对象与二进制之间转换一般都是实现 NSCoding 协议来做的。

**Comment by KittenYang** [comment]
@ibireme 恩，可是 Archive/Unarchive 又会比较变慢而且还需要消耗更多的磁盘空间和 I/O。 所以 YYDiskCache 其实不太适用于 Model 的持久化是吗？

**Comment by ibireme** [comment]
除非你用 FMDB 针对每个 Model 建立一个单独的表，并且每个字段都映射过去；或者用其它的方式比如 protobuf，那性能才能有明显提高，但相对的开发代价也太大。

一般的数据缓存（比如 PINCache/ImageCache 或是 Facebook App 的那些 Cache）都在用 Archive/Unarchive，所以用来缓存 Model 这点是没问题的。另外，基于磁盘读写的缓存，本身性能就不会太高，所以一般存取操作都是异步进行的。
