### ISSUE TITLE
建议YYKit所有的方法都使用前缀：yy , 这样可以根据方便找到YYKit的方法

### ISSUE THREAD

**Issue by HeroOnline** [ibireme/YYKit#135]
建议YYKit所有的方法都使用前缀：yy , 这样可以根据方便找到YYKit的方法 ， 例如 :  yy_test , yy_modelToJson ,

**Comment by ibireme** [comment]
这里已经解释过了：https://github.com/ibireme/YYKit#注意

> 我希望调用 API 时，有着和调用系统自带 API 一样的体验，所以我并没有为 Category 方法添加前缀。我已经用工具扫描过这个项目中的 API，确保没有对系统 API 产生影响，但即使这样没有前缀的 Category 也可能会带来其他麻烦。因此我不太推荐直接使用 YYKit 这个库，你应该先尝试一下上面那些拆分出来的独立组件。

**Comment by HeroOnline** [comment]
YY亲，各个独立模块也一样没有使用 yy 前缀啊！！！

**Comment by ibireme** [comment]
https://github.com/ibireme/YYModel/blob/master/YYModel/NSObject%2BYYModel.h#L78

> \+ (nullable instancetype)yy_modelWithJSON:(id)json;

**Comment by HeroOnline** [comment]
YY亲，其他的模块没有yy前缀
