### ISSUE TITLE
Static declaration of 'CGRectGetCenter' follows non-static declaration

### ISSUE THREAD

**Issue by HeroOnline** [ibireme/YYKit#136]
/Pods/Headers/Public/YYKit/YYCGUtilities.h:128:23: Static declaration of 'CGRectGetCenter' follows non-static declaration

**Comment by ibireme** [comment]
CGRectGetCenter 这个方法里引用的两个函数是 CoreGraphic 声明的，所以这里不可能出现这种问题。
我和其它使用者都没有遇到这个问题。你可以检查一下你的编译选项。

**Comment by HeroOnline** [comment]
YY亲，新建的项目是没有报错，但是进入到之前创建的项目中就报错：/Pods/Headers/Public/YYKit/YYCGUtilities.h:128:23: Static declaration of 'CGRectGetCenter' follows non-static declaration ， 可以帮忙找找吗？ 编译的几个选项都是默认的

**Comment by ibireme** [comment]
`CGRectGetCenter` 这个函数本身是没问题的。你项目的错误我帮不了。

**Comment by haojian2016** [comment]
我也遇到这个问题啦，@HeroOnline 你解决了吗？

**Comment by haojian2016** [comment]
问题解决了，原工程里面有CGRectGetCenter，重复定义了
