### ISSUE TITLE
YY亲，Model转换成JSON，是否提供一个方法，返回的JSON不包含值为空的 

### ISSUE THREAD

**Issue by HeroOnline** [ibireme/YYKit#144]
YY亲，Model转换成JSON，是否提供一个方法，返回的JSON不包含值为空的  ， 例如：  name 没有设置值，JSON就不要有 "name":nil , 或者 "name": "" ，直接返回有值的就可以了

**Comment by ibireme** [comment]
现在就是这个逻辑。
