### ISSUE TITLE
想知道每个文件里面的 License 是怎么加进去的？

### ISSUE THREAD

**Issue by hilen** [ibireme/YYKit#145]
![image](https://cloud.githubusercontent.com/assets/2245840/13840622/8e298a68-ec5e-11e5-967a-5fb4144f0c6a.png)
比如这个文件的，License 信息是创建时候就会有吗？ 还是手动加入的？

**Comment by ibireme** [comment]
这个可以在 Xcode 文件模板里配置好。
不过我这块儿是手动加的😅

**Comment by hilen** [comment]
哈哈，好吧。多谢回答 :100:
