### ISSUE TITLE
YYLabel开启displaysAsynchronously，在reload的时候会闪一下

### ISSUE THREAD

**Issue by sealedace** [ibireme/YYKit#146]
我的YYLabel是在UICllectionViewCell里面，当UICollectionView reload的时候，已经展示好的label会闪一下，这个怎么解决？

**Comment by ibireme** [comment]
https://github.com/ibireme/YYKit/issues/64

**Comment by sealedace** [comment]
谢了。我再看看有没有更好的解决方案:)
