### ISSUE TITLE
文字显示不出来, 再刷新一次可以了.

### ISSUE THREAD

**Issue by sixleaves** [ibireme/YYKit#147]
iOS9以上红色的为YYLabel, 高度和宽度是根据 YYLabel 的textBoundingSize来获取.文本的位置也确定没问题.在 Xcode 中用视图查看的这个工具是可以看到, 但是就是显示不出来?....确定没有被隐藏.

<img width="458" alt="1507fa63-78e9-4cfa-abbd-a7972da77452" src="https://cloud.githubusercontent.com/assets/3601210/13841199/55d73440-ec62-11e5-9cfa-95602eb85c9b.png">

**Comment by ibireme** [comment]
可以检查下是否在某个时刻在非主线程访问了某些属性。

**Comment by sixleaves** [comment]
原来是因为linePositionModifier没有设置好.
还有一个问题, 就是无法加粗, 只能改大字体.
如果使用fontWithBold, 这是 YYAdd 中添加的, 显示会不完整, 不能正确计算出 高度.

**Comment by sixleaves** [comment]
.而且这是在 ios9后的才会有问题.在 ios9之前的却没问题.....好奇怪.....如果我不加 fontWithBold, 并且 linePositionModifier 设置正确, 就没有问题, 但是这样字体就不能加粗了.

**Comment by ibireme** [comment]
宽高计算都是 CoreText 的逻辑，这个应该不至于出错吧：

    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(100, CGFLOAT_MAX);
    container.maximumNumberOfRows = 0;
    container. linePositionModifier = xxx;

    // Generate a text layout.
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
    CGSize size = layout.textBoundingSize;

    label.textLayout = layout;

**Comment by sixleaves** [comment]
`        BKRecipeTextLinePositionModifier *modifier = [BKRecipeTextLinePositionModifier new];
        modifier.font =[[UIFont fontWithName:@"Heiti SC" size:18] fontWithBold];
        modifier.paddingTop = 0;
        modifier.paddingBottom = 0;

        NSMutableAttributedString *titleAttr = [[NSMutableAttributedString alloc] initWithString: title];
        titleAttr.font =[[UIFont fontWithName:@"Heiti SC" size:18] fontWithBold];
        titleAttr.color = kBKCellTextTitleNormalColor;
        YYTextContainer *container = [YYTextContainer containerWithSize:(CGSize){kBKCellProfileNameWidth, 9999}];
        container.maximumNumberOfRows = 1;
        container.linePositionModifier = modifier;
        _textTitleLayout = [YYTextLayout layoutWithContainer:container text:titleAttr];

        _textTitleHeight = _textTitleLayout.textBoundingSize.height;`


......这样一写, 就显示不正常了, 把fontWithBold去掉, 就 OK 了

**Comment by ibireme** [comment]
显示时，是用 label.textLayout = layout; 显示的吗？

另外，可以试试开启调试模式，看看界面上的排版结果。

    YYTextDebugOption *debugOptions = [YYTextDebugOption new];
    debugOptions.baselineColor = [UIColor redColor];
    debugOptions.CTFrameBorderColor = [UIColor redColor];
    debugOptions.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.463 blue:1.000 alpha:0.180];
    debugOptions.CGGlyphBorderColor = [UIColor colorWithRed:1.000 green:0.524 blue:0.000 alpha:0.200];
    [YYTextDebugOption setSharedDebugOption:debugOptions];

**Comment by sixleaves** [comment]
标题还是没有......如下图.标题是加粗的.是用 label.textLayout = layout; 没错
![image](https://cloud.githubusercontent.com/assets/3601210/13948216/dfd56c84-f059-11e5-9041-b06c87dbd7b5.png)

<img width="305" alt="e75a17ac-2c8c-4508-b43c-d4c665920a02" src="https://cloud.githubusercontent.com/assets/3601210/13948213/da1c37d2-f059-11e5-80af-a652e0fddb71.png">

**Comment by ibireme** [comment]
这就不知道了。。试试去掉 linePositionModifier 看看吧。。或者 bold 字体用系统的方法创建。。

**Comment by sixleaves** [comment]
去掉有试过, 是可以, 但是字体变小了.应该是我这的问题.我改了下 Demo 都每能重现~~~~

**Comment by sixleaves** [comment]
字体会变小很多....我再找找吧.....谢谢拉.

**Comment by sixleaves** [comment]
暂时的解决方案: 改成系统字体, 可以兼容 ios6---ios9.可加粗.
