### ISSUE TITLE
Xcode7.3环境 NSObject (YYAddForKVO)下的一个方法错误

### ISSUE THREAD

**Issue by lyj98** [ibireme/YYKit#149]
- (void)addObserverBlockForKeyPath:(NSString*)keyPath block:(void (^)(__weak id obj, id oldVal, id newVal))block;

/YYKit/Base/Foundation/NSObject+YYAddForKVO.h:31:71: Cannot create __weak reference in file using manual reference counting
暂时把 __weak  删掉没有错误,  这个错误应该怎么解决.

**Comment by ibireme** [comment]
我也发现了。。把 __weak 删掉吧。。
今天或明天更新一下。

**Comment by lyj98** [comment]
@ibireme 好的

**Comment by ibireme** [comment]
Fixed

**Comment by JarhomChen** [comment]
你好，pods的库能同步到1.0.3吗？使用cocoa pods删不掉，无法unlock
