### ISSUE TITLE
YYHashFile对文件加密后如何解密

### ISSUE THREAD

**Issue by wangyansnow** [ibireme/YYKit#150]
## `YYHashFile`解密的问题
我看到你写的`YYHashFile`功能十分强大,可是我不知道使用这个类把文件加密了,然后又应该如何解密呢?有提供这样的接口类吗?

**Comment by ibireme** [comment]
这是计算文件 hash 的，并不是加密解密。。

**Comment by wangyansnow** [comment]
返回的`YYFileHashType`的属性,`MD5Data`, `MD5String`怎么理解.在项目中如何使用.

**Comment by ibireme** [comment]
MD5Data 是文件的 md5 hash 二进制值，而 MD5String 是文件的 md5 hash 转换得到的文本。

**Comment by wangyansnow** [comment]
文件 hash的这个过程可逆吗

**Comment by wangyansnow** [comment]
我没有看懂`YYHashFile`这个类在项目中的用处,或者它在什么场景下使用是比较合适的

**Comment by ibireme** [comment]
在需要计算文件 hash 的时候用啊。。做文件校验或索引之类的可能会用到。

**Comment by wangyansnow** [comment]
嗯，明白了，谢谢，最近一直在看阁下的YYKit有什么不明白的地方再继续向你讨教。还有很想知道你是如何高效学习的，能在这么短的时间里成长如此之快，给一点学习iOS进阶知识的建议。
在2016年03月22日 18:18，Yaoyuan 写道:

在需要计算文件 hash 的时候用啊。。做文件校验或索引之类的可能会用到。
