### ISSUE TITLE
不知为啥下载图片, 有的看得到有得看不到

### ISSUE THREAD

**Issue by sixleaves** [ibireme/YYKit#153]
`    [_bigImage setImageWithURL:[NSURL URLWithString:[[NoteService getFirstImage:layout.note.contentItems] url]]
                           placeholder:nil
                               options:kNilOptions
                               manager:nil
                              progress:nil
                             transform:nil
                            completion:nil];
`
又来求助 yy 了, 有的图片看得到, 但是是有下载下来.....好奇怪啊.imageView 宽高是后台线程算好的.imageView 页面没有隐藏,就是图片出不来......图片地址粘贴到网页是可以看的......啊啊啊....

**Comment by ibireme** [comment]
这个我不清楚了，从上面描述上看不出问题来。

**Comment by sixleaves** [comment]
啊啊啊啊啊, 这里有错误提示, 图片url 是http://bkd-cdn.buildcoo.com/img-message/85815296-4391-40ec-8916-f7e86c50f3c0.jpg
<img width="507" alt="02c23c15-6959-45ba-ab74-2ca0943fdc27" src="https://cloud.githubusercontent.com/assets/3601210/13979591/72a781ae-f114-11e5-9224-43fccb4c1c65.png">

**Comment by xialisuper** [comment]
图片并不能看...而且jpg格式的 能直接用吗?

**Comment by xialisuper** [comment]
图片打不开. 而且jpg格式的图片可以直接使用吗?

**Comment by sixleaves** [comment]
NSURLConnection 也出来了....呜呜....我试试 SDWebImage 看下....
<NSURLConnection: 0x7fa8e505d010> { request: <NSMutableURLRequest: 0x7fa8e5069d00> { URL: http://bkd-cdn.buildcoo.com/img-message/85815296-4391-40ec-8916-f7e86c50f3c0.jpg } }

**Comment by ibireme** [comment]
把 error 信息打印出来啊。。图没截取全。。
另外，在 YYWebImageDemo 里是可以显示出来的。

**Comment by sixleaves** [comment]
<img width="472" alt="ab31bf65-2538-4042-a29d-41d6c5dc140a" src="https://cloud.githubusercontent.com/assets/3601210/13982476/4eb9a946-f125-11e5-8ed4-e45f4e2a3bfa.png">
是我这边的问题, 这是图片编码格式不对吗?

**Comment by ibireme** [comment]
<img width="314" alt="2016-03-23 6 42 26" src="https://cloud.githubusercontent.com/assets/839283/13982801/071b6e60-f127-11e5-9623-637d11d8f774.png">

在 Demo 项目里是没问题的。。我猜可能是你那儿的 CDN 分发没有完成或者其它什么原因导致图片损坏了？

**Comment by ibireme** [comment]
查明白了，虽然这个图片名字是 jpg，但实际内容是 webp 格式的。如果你在用 YYWebImage，那可能是没有引入 WebP 的子模块。这块儿可以看一下 YYWebImage Readme 的安装步骤。

**Comment by sixleaves** [comment]
.....这是根据图片的 URL 缓存图片的吧?那这个坏的图片会被缓存着么.

**Comment by ibireme** [comment]
解码失败的图片会被丢弃掉，不会缓存

**Comment by sixleaves** [comment]
哈哈, 真的可以拉, 膜拜

**Comment by sixleaves** [comment]
我的好好读下大神的博客
