### ISSUE TITLE
关于Cocoapods 安装YYKit 与 YYCache 等的问题

### ISSUE THREAD

**Issue by CodeEagle** [ibireme/YYKit#154]
项目中，需要分离一些功能做成单独的模块，可能用到YYKit的器重一个部分，如YYCache，但是主项目中直接用YYKit的话，会造成个问题
` Class YYCache is implemented in both */YYKit.framework/YYKit and */YYCache.framework/YYCache. One of the two will be used. Which one is undefined.`
所以想请教下，是否能把单独出来的那些如`YYCache`的归入`YYKit`的 subspec 中

－－－－－－－－－－
好像也不太行

**Comment by ibireme** [comment]
能拆出来的大块儿都拆出来了。。
而且，拆出来的东西和 `YYKit` 里面可能有些细节不一样，还不能直接用 subspec。
