### ISSUE TITLE
Xcode 7 cocoaPods安装YYKit 链接错误，报符号重复

### ISSUE THREAD

**Issue by bigship** [ibireme/YYKit#156]
Hi，我用cocoaPods安装了YYKit，build的时候报了很多符号重复的错误
`duplicate symbol _WebPInitConvertARGBToYUV in:
    .../Pods/YYKit/Vendor/WebP.framework/WebP(libwebpdsp_la-yuv.o)
   .../Pods/YYKit/Vendor/WebP.framework/WebP(libwebpdspdecode_la-yuv.o)
`
`
duplicate symbol _WebPConvertARGBToUV_C in:
   .../Pods/YYKit/Vendor/WebP.framework/WebP(libwebpdsp_la-yuv.o)
   .../Pods/YYKit/Vendor/WebP.framework/WebP(libwebpdspdecode_la-yuv.o)
`
`
duplicate symbol _WebPConvertRGBA32ToUV_C in:
   .../Pods/YYKit/Vendor/WebP.framework/WebP(libwebpdsp_la-yuv.o)
    .../Pods/YYKit/Vendor/WebP.framework/WebP(libwebpdspdecode_la-yuv.o)
`
`
ld: 62 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

我觉得应该是我的Xcode配置的问题吧，但我实在不知道怎么弄。cocoaPods版本是1.0.0.beta.4

**Comment by ibireme** [comment]
检查下编译的 flag 有没有 all_load 之类的东西。

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYKit/commits/master
