### ISSUE TITLE
Xcode 7.3 cocoaPods安装YYKit 编译报错

### ISSUE THREAD

**Issue by kakukeme** [ibireme/YYKit#158]
/Pods/Headers/Public/YYKit/UIDevice+YYAdd.h:31:1: Property cannot have array or function type 'BOOL (())' (aka 'bool ()'

Pods/Headers/Public/YYKit/YYCGUtilities.h:128:23: Static declaration of 'CGRectGetCenter' follows non-static declaration

**Comment by ibireme** [comment]
请清空缓存并检查项目配置。
目前用 Xcode 7.3 新建工程并倒入 YYKit 是没问题的。

**Comment by kakukeme** [comment]
好的，不知怎么回事，现项目就是加不了YYKit。

**Comment by kakukeme** [comment]
需要将之前cocoaPods安装的移除后，然后和YYKit一次性添加；就这样解决了！
