### ISSUE TITLE
YYKitDemo was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by wangyanlong** [ibireme/YYKit#160]
下载了YYKit的demo,发现打印台里的变量都为nil,并且显示出了这句话:
YYKitDemo was compiled with optimization - stepping may behave oddly; variables may not be available.
请问怎么解决?

**Comment by ibireme** [comment]
把 scheme 中的 release 改成 debug。

**Comment by wangyanlong** [comment]
谢谢,可以了
