### ISSUE TITLE
关于gif图文混排

### ISSUE THREAD

**Issue by lishuanghenu** [ibireme/YYKit#164]
我使用了您在微博demo中图文混排的方式来做图文混排 同时我将textlayout提前算出 但是我发现在cell复用的时候 第一次gif图片能显示 但当cell进入复用池再次使用的时候git图片就无法显示了
`- (id)content {
    /// UIImageView 只能在主线程访问
    
    if (![NSThread isMainThread]) {
        return nil;
    }
    
    NSAssert([NSThread isMainThread], @"err");
    
    if (_imageView) return _imageView;
    /// 第一次获取时 (应该是在文本渲染完成，需要添加附件视图时)，初始化图片视图，并下载图片
    _imageView = [UIImageView new];
    CGRect frame = _imageView.frame;
    frame.size = _size;
    _imageView.frame = frame;
    [_imageView sd_setImageWithURL:[NSURL URLWithString:_imageURL]
                 placeholderImage:[UIImage defaultTVImageWithSize:_imageView.bounds.size] options:SDWebImageRetryFailed | SDWebImageLowPriority completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                     if (error) {
                         _imageView.hidden = true;
                     }
                 }];
    _imageView.userInteractionEnabled = true;
    
    UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(doImageTap)];
    [_imageView addGestureRecognizer:tap];
    
    return _imageView;
}`

这是我在content中的代码 正常图片是可以的 gif就会显示占位图

**Comment by ibireme** [comment]
是 gif 吧。。
cell 复用后要重新设置 layout 等属性。

**Comment by lishuanghenu** [comment]
重设这个做了的 普通图片就是OK的 gif就不行了 这边一点头绪都没有

**Comment by ibireme** [comment]
reuseCell 的时候先清空一下，再复用的时候重新设置一下 layout。。
再不行我就不清楚了，目前我复现不了。。

**Comment by lishuanghenu** [comment]
`[_imageView sd_setImageWithURL:[NSURL URLWithString:_imageURL]
             placeholderImage:[UIImage defaultTVImageWithSize:_imageView.bounds.size] options:SDWebImageRetryFailed | SDWebImageLowPriority completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                 if (error) {
                     _imageView.hidden = true;
                 }
             }];` 
我现在每次都执行这段就可以了 我去看了SD的源码 它也没对imageview做什么特殊处理 但是每次复用后都只显示占位图这个蛋疼 暂时只能这样 我再研究研究
