### ISSUE TITLE
属性和key大小写匹配的问题

### ISSUE THREAD

**Issue by goodcyg** [ibireme/YYKit#168]
如果属性和json里的key，大小写不匹配的话，json转模型就是失败的。但是一个项目这种情况很多啊，改起来是个体力活。你对这个问题是咋看？啥好的解决方案？

**Comment by ibireme** [comment]
实现 `modelCustomPropertyMapper` 来返回自定义映射关系啊。
JSON 和 Property 都是大小写敏感的，比如 `underline` 和 `underLine` 就是两个不同的属性，这不可能去忽略大小写来做映射。

**Comment by goodcyg** [comment]
明白了，原来你这里已经做了处理，非常好 呵呵。
还有一个问题+ (nullable NSDictionary<NSString *, id> *)modelCustomPropertyMapper 是YYModel可选协议，一般我们是要在实现类中写上'<YYModel>'，你把<YYModel> 写在分类中，就不需要在There's no need to add '<YYModel>' to your class header.？

**Comment by goodcyg** [comment]
There's no need to add '' to your class header.
======
这样到挺方便的，免得加一大堆的协议头，你咋样的实现原理?麻烦解释一下.谢谢。

**Comment by ibireme** [comment]
这里只会检测是否实现了具体方法，而不是去检测是否实现整个协议，所以加不加 \<YYModel\> 的声明都是无所谓的。

**Comment by goodcyg** [comment]
这里只会检测是否实现了具体方法，而不是去检测是否实现整个协议，所以加不加 <YYModel> 的声明都是无所谓的。
================
 定义成协议，而又不是按协议方式来。有点费解.
那是否可以这样，在NSobject的分类中定义一个方法+ (nullable NSDictionary *)modelCustomPropertyMapper，让子类去重新实现它？而不用搞成 <YYModel> 协议声明?

**Comment by ibireme** [comment]
如果你愿意按照协议来，在 model 的 interface 里面声明了 \<YYModel\>，那这就是 "定义成协议，也按协议方式来" 了。

\<YYModel\> 协议里面的方法都是可选的，我在内部做检测时，仍然还是需要针对每个方法做判断，而不能直接判断是否实现了 \<YYModel\> 协议。所以，这里也允许了使用者不去写这个 `\<YYModel\>`。

在 NSObject 上定义方法也行，但这会污染 NSObject 的函数命名空间，还会带来`未实现方法`的编译警告。

**Comment by goodcyg** [comment]
谢谢，你的解答，顺便问一下，你处理过app 访问的DNS被劫持的问题？有能分享一下经验？

**Comment by ibireme** [comment]
没有，不过可以试试 HttpDNS 之类的方式来直接访问 IP。
