### ISSUE TITLE
YYLabel如果一行显示不下, 无法显示到最末尾在换行啊.

### ISSUE THREAD

**Issue by sixleaves** [ibireme/YYKit#169]
设置了lineBreakMode还是没有用.......

**Comment by sixleaves** [comment]
没有像UILabel的preferredMaxLayoutWidth属性, 让它能到末尾再换行啊.....

**Comment by ibireme** [comment]
YYLabel 是有 preferredMaxLayoutWidth 属性的。

**Comment by sixleaves** [comment]
.........泪奔....今年1月下的没更新过......

**Comment by sixleaves** [comment]
设置还是没用啊......

**Comment by ibireme** [comment]
你是怎么使用的啊。。把相关代码贴一下吧。。

**Comment by sixleaves** [comment]
_contentTitle = [YYLabel new];
    _contentTitle.displaysAsynchronously = YES;
    _contentTitle.ignoreCommonProperties = YES;
    _contentTitle.fadeOnAsynchronouslyDisplay = NO;
    _contentTitle.fadeOnHighlight = NO;
    _contentTitle.userInteractionEnabled = YES;
    _contentTitle.preferredMaxLayoutWidth = viewwidth - 2 *kBKCellPadding;
    _contentTitle.lineBreakMode = NSLineBreakByCharWrapping;

**Comment by ibireme** [comment]
你是如何设置文本的？

如果是用 text/font/attributedText 的话，`ignoreCommonProperties` 就不要设置为 YES。
如果是用 textLayout 的话，宽度限制应该在 textLayout 创建时使用。

**Comment by sixleaves** [comment]
已经解决了, 是我的bug, sorry~

**Comment by YongHuiCheng** [comment]
你是怎么解决的呢。。我现在怎么设置都不显示尾部...

**Comment by YongHuiCheng** [comment]
@sixleaves 你是怎么解决的，我现在也遇到这个问题
