### ISSUE TITLE
linespace 修改行间距的时候发现有偏差

### ISSUE THREAD

**Issue by yupliang** [ibireme/YYKit#170]
![22.png](http://7xsmj5.com2.z0.glb.clouddn.com/22.png)
打开debug模式的时候，发现文字上边缘与框还有一段距离，这个应该是计算ascent的时候，ascent偏大，这个间距是多少呢，想知道有没有计算方法来在计算这个间距。

**Comment by ibireme** [comment]
如果没有用 `YYTextLinePositionModifier`，那所有的排版结果都是 CoreText 生成的。这块儿的 ascent 和 descent 都是字体本身属性。字体在设计时，会考虑加入适当的 ascent 和 descent 来保证页面的排版效果。

如果仅需要文字黑色部分的高度的话，可以在 textLayout 中取到具体的 CTLineRef，然后用 CTLineGetBoundsWithOptions() 并传入 kCTLineBoundsUseGlyphPathBounds 来计算，不过也不一定准确。。
