### ISSUE TITLE
显示中文引号问题

### ISSUE THREAD

**Issue by yupliang** [ibireme/YYKit#171]
![44.png](http://7xsmj5.com2.z0.glb.clouddn.com/44.png)
YY亲，这里采用的字体是[UIFont systemFontOfSize:14]
在iOS 9下显示双引号是半角，该怎么设置才能显示成全角呢。

**Comment by ibireme** [comment]
`""` 和 `“”` 应该不是同一个字符吧？

**Comment by yupliang** [comment]
上边两处写的是“”

**Comment by ibireme** [comment]
系统地区设置看一下是不是中国。
如果地区没问题，改用 PingFang SC / Heiti SC 字体试试。

**Comment by yupliang** [comment]
PingFang SC 引号显示正常了，YY亲这个是什么原因呀

**Comment by ibireme** [comment]
同一个字符，在不同字体中会有不同的样式。排版时，系统会根据地区偏好、文字上下文等信息，生成一份字体优先级列表，对于同一个字符来说，会从这个列表中按顺序查找看哪个字体能用来显示，（fallback）。如果对文字设置为 system font，那这个列表中 Helvetica Neue 可能会靠前，而 PingFang SC 则会排后，大概是这样。

另外，iOS 9 和以上系统，中文字体是 PingFang SC，而 iOS8 和以下系统是 Heiti SC，这个可能要根据系统版本号来做一下判断。
