### ISSUE TITLE
关于podspec的建议

### ISSUE THREAD

**Issue by JianboYan** [ibireme/YYKit#173]
目前YYKit的podspec文件因为没有分subspec, 所以引入后全部都混入到一个文件夹中, 这么做有几个缺点:
1. 没有很好的归档, 看起来很混乱
2. 不能只引入部分文件, 比如我只想引入里面的cache, 但是却不得不引入全部的文件

**Comment by ibireme** [comment]
呃。。我不太推荐直接使用 `YYKit` 这个库，你应该先尝试一下那些拆分出来的独立组件，比如 `YYCache`。这个我也在 readme `注意` 里提到了。

YYKit 和那些拆分出来的独立组件，还是有一些地方不一样的，所以不能直接 subspec。

**Comment by JianboYan** [comment]
嗯, 明白了, 之前没有看到你已经拆分了. 谢啦
