### ISSUE TITLE
'YYKit/YYKitMacro.h' file not found

### ISSUE THREAD

**Issue by goodcyg** [ibireme/YYKit#176]
1.我把YYKit拖进行工程中加入，导入frameworks，然后再pct中
#import  <YYKit/YYKit.h>
#import "YYKit.h"
加入任意一个都报错，我再头文件的搜索路径里加入yykit路径也不行。
'YYKit/YYKitMacro.h' file not found？

2#if __has_include(<YYKit/YYKit.h>)
#import <YYKit/YYKitMacro.h>
#else
#import "YYKitMacro.h"
#endif

请解释一下__has_include的用法？

**Comment by ibireme** [comment]
关于安装，可以看看这一段：https://github.com/ibireme/YYKit#安装

关于 has_include 可以看看文档：http://clang.llvm.org/docs/LanguageExtensions.html#include-file-checking-macros

**Comment by goodcyg** [comment]
手动安装

    下载 YYKit 文件夹内的所有内容。
    将 YYKit 内的源文件添加(拖放)到你的工程。
    为 NSObject+YYAddForARC.m 和 NSThread+YYAdd.m 添加编译参数 -fno-objc-arc。
    链接以下 frameworks:
        UIKit
        CoreFoundation
        CoreText
        CoreGraphics
        CoreImage
        QuartzCore
        ImageIO
        AssetsLibrary
        Accelerate
        MobileCoreServices
        SystemConfiguration
        sqlite3
        libz
    如果你需要支持 WebP，可以将 Vendor/WebP.framework(静态库) 加入你的工程。
    导入 YYKit.h。
我就是按照上边操作的。你可以在的demo把 yykit删除后，在加进去，多试试就知道了。

**Comment by ibireme** [comment]
再多试试。。。😓 这不是操作次数的问题啊，那个 Demo 项目的配置本来就是特殊处理的，不要抄那个配置。

首先，删除那些多余的与 YYKit 相关的东西（包括 header/library/framework search 路径），清空 Xcode 缓存，重启 Xcode，保证安装过程不受 Xcode 本身的影响。

然后，把 `YYKit` 这个文件夹拖到你的 Xcode 工程里，勾上 ‘Copy Items'，选择 'Create Group'。header/library/framework 之类的工程配置中不要添加与 YYKit 相关的路径。

这个操作过程，应该和你在工程内新建文件是一个逻辑。

**Comment by goodcyg** [comment]
header/library/framework 之类的工程配置中不要添加与 YYKit 相关的路径。
==============
我在../libs/YYKit中,把../libs/设置到header/library/framework 中了，删除就可以了。😓  谢谢
