### ISSUE TITLE
导入YYkit后编译报错

### ISSUE THREAD

**Issue by JakeMeng** [ibireme/YYKit#178]
出现三处错误,都是同一类型的:
1 位置: UIDevice+YYAdd 的 isPad is Simulator 属性
2 错误信息: 
Property cannot have array or function type "BOOL(())"

**Comment by ibireme** [comment]
可以参考下这个问题：https://github.com/ibireme/YYKit/issues/158

**Comment by JakeMeng** [comment]
ok, I will try

**Comment by JakeMeng** [comment]
采用#158的解决方法, 清除Xcode 7.3 的缓存后, 删除cocoaPods添加的第三方库文件夹pods以及xcwokespace , 仅保留Podfile, 重新update后, 编译依然报错.

**Comment by ibireme** [comment]
我之前也遇到过一次类似的错误，但 Clean 一下就好了。
我觉得可能与项目原来的环境、配置或某处 Xcode 缓存有关。。这个问题很难查。。

**Comment by JakeMeng** [comment]
好的, 我试试别的办法是否可行, 如果可以再来comment.

**Comment by ibireme** [comment]
如果有新进展，可以在 Reopen 来讨论。

**Comment by JakeMeng** [comment]
好的,郭大神.                             原始邮件                             发件人: Yaoyuan<notifications@github.com>收件人: ibireme/YYKit<YYKit@noreply.github.com>抄送: JakeMeng<mengjinshan@qfpay.com>; Author<author@noreply.github.com>发送时间: 2016年5月24日(周二) 00:59主题: Re: [ibireme/YYKit] 导入YYkit后编译报错 (#178)如果有新进展，可以在 Reopen 来讨论。
