### ISSUE TITLE
关于表情键盘的问题

### ISSUE THREAD

**Issue by bycc070809** [ibireme/YYKit#179]
最近在项目中 用到表情  代码基本参照你的  微博项目里的表情 代码如下

- (void)_buttonClicked:(UIButton *)button {
    if (button == _toolbarEmoticonButton)
     {
 
        if (_textView.inputView) 
        {
            _textView.inputView = nil;
            [_textView reloadInputViews];
            [_textView becomeFirstResponder];
            
            [_toolbarEmoticonButton setImage:[UIImage imageNamed:@"Album_ToolViewEmotion"] forState:UIControlStateNormal];
            [_toolbarEmoticonButton setImage:[UIImage imageNamed:@"Album_ToolViewEmotionHL"] forState:UIControlStateHighlighted];
        }
         else
        {
            EmoticonInputView *v = [EmoticonInputView sharedView];
            v.delegate = self;
            _textView.inputView = v;
            [_textView reloadInputViews];
            [_textView becomeFirstResponder];
            [_toolbarEmoticonButton setImage:[UIImage imageNamed:@"Album_ToolViewKeyboard"] forState:UIControlStateNormal];
            [_toolbarEmoticonButton setImage:[UIImage imageNamed:@"Album_ToolViewKeyboardHL"] forState:UIControlStateHighlighted];
        }
}

但是发现有时候点击切换键盘和表情的时候 没有反应  也就是说不切换 我对于这块的不是太熟 花了点时间 也没有整理出思路 这会是由于什么原因导致的呢 请给我一些思路 非常感谢

**Comment by ibireme** [comment]
可以试试调整一下 [_textView reloadInputViews]; 的调用顺序，也可以试试延迟执行这个。

**Comment by bycc070809** [comment]
好的 谢谢  我试试 ，还有一点 忘了 讲 当把键盘 隐藏 在显示 又好了   也就是说每次切换键盘  需要隐藏后 在现实 才行
