### ISSUE TITLE
YYLabel使用好繁琐

### ISSUE THREAD

**Issue by mengerpiao** [ibireme/YYKit#18]
YYLabel使用好繁琐,
    YYTextContainer *container = [YYTextContainer containerWithSize:CGSizeMake(self.frameModel.nameF.size.width, self.frameModel.nameF.size.height)];
    NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:self.frameModel.newsModel.nickname];
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
    self.nameLabel.textLayout = layout;

界面没有显示,请教是怎么回事?

**Comment by ibireme** [comment]
YYLabel 的使用可以参考 https://github.com/ibireme/YYText 的中文说明。
默认是可以用 UILabel 一样的方式使用的。

上面代码没有显示的话，可以检查 label 的大小、layout 的结果。
