### ISSUE TITLE
小疑问

### ISSUE THREAD

**Issue by 1247706647** [ibireme/YYKit#180]
使用yykit来做model转json的操作时,在控制台NSLog得到的json对象时，NSString类型对象的双引号为什么丢失了？比如正常json：{
  "uid" : 123456,
  "name" : "michael",
  "created" : "2016-04-141T00:00:00+0000"
}，用yy_modelToJSONObject转换一下后：json:{
    created = "2016-04-14T08:00:00+0800";
    name = michael;
    uid = 123456;
}
name后面的值作为NSString类型不是应该带上双引号吗

**Comment by ibireme** [comment]
这是 NSDictionary description 的逻辑，而且那也不是 JSON。

**Comment by 1247706647** [comment]
我是用先用yy_modelWithJSON的方法先把一个已知的json转成model的，然后将转成的model放到yy_modelToJSONObject方法里得到一个json数据，比照这两个json，发现不一样了

**Comment by ibireme** [comment]
呃。。json 的 key-value 是无序的啊，另外 model 和 json 可能并不能完全一致的对应上，所以转入 model 再转回来是可能不一样啊。

另外，yy_modelToJSONObject 返回的是一个 NSDictionary 或者 NSArray，这并不是 JSON 字符串。。
