### ISSUE TITLE
键盘 默认中文 问题

### ISSUE THREAD

**Issue by bycc070809** [ibireme/YYKit#183]
我现在碰到一个问题  我用YYTextView 默认 弹出键盘的时候 键盘默认显示的是 英文 我想显示的是 中文   我代码 是 参照微博的那块 但是 发现你微博 那边 默认显示的就是 中文  这块会是 什么原因引起

**Comment by ibireme** [comment]
在系统设置里，设置下区域语言和键盘。
在 App 的配置中，配置一下 Localizations。

**Comment by bycc070809** [comment]
好的 谢谢

**Comment by bycc070809** [comment]
试了一下 不行 我用系统默认键盘 就是中文  但是搜狗 就不行 ，但是你的demo  搜狗键盘是可以的 不知道 是什么原因
