### ISSUE TITLE
修改yykit 

### ISSUE THREAD

**Issue by yupliang** [ibireme/YYKit#184]
yy亲，我打算修改一下yykit来满足项目的需求，然后把它放到cocoapods上，方便管理，不知道这个是不是被允许的？

**Comment by ibireme** [comment]
CocoaPods 的包名是个全局的空间，没有前缀。。所以如果还是以 `YYKit` 这个名字向 CocoaPods 中央仓库提交，应该是不会成功的。。

你可以把代码放在本地或你自己的私有仓库内，然后在 Podfile 里指定明确的地址。
