### ISSUE TITLE
Ambiguous expansion of macro 'weakly' 

### ISSUE THREAD

**Issue by zdrjson** [ibireme/YYKit#185]
YYKit 和ReactiveCocoa都有定义，如何去除此warning？

**Comment by jhonny-me** [comment]
你可以在podfile中加上这一句 inhibit_all_warnings!忽略所有pod中的警告

```
platform :ios,'7.0'

inhibit_all_warnings!

pod 'MBProgressHUD'
pod 'YYKit'
pod 'ReactiveCocoa'
```

**Comment by ibireme** [comment]
在引用头文件时，把 #import  RAC.h 放到 #import YYKit.h 之前。

**Comment by Quanhua-Guan** [comment]
但是, 问题依然存在. 
    #import "ReactiveObjC.h"
    #import "YYKit.h"

**Comment by Quanhua-Guan** [comment]
Podfile里设置使用 use_frameworks! 的时候依然会报这个错误, 已经按照作者的方法把#import "YYKit.h" 放在  #import "ReactiveObjC.h" 后面.

**Comment by beforeold** [comment]
> Podfile里设置使用 use_frameworks! 的时候依然会报这个错误, 已经按照作者的方法把#import "YYKit.h" 放在 #import "ReactiveObjC.h" 后面.

me too

**Comment by Quanhua-Guan** [comment]
放的位置不对 再找找是否在引用yykit后还有引用reactiveobjc.h




| |
官泉华
邮箱：xinmuheart@163.com
|

签名由 网易邮箱大师 定制

On 12/03/2018 14:20, 席萍萍 Brook wrote:

Podfile里设置使用 use_frameworks! 的时候依然会报这个错误, 已经按照作者的方法把#import "YYKit.h" 放在 #import "ReactiveObjC.h" 后面.

me too

**Comment by beforeold** [comment]
podfile 使用 use_framework，同时还使用了 prefixheader.pch，这时候更改 import 的顺序无法解决问题。

**Comment by daveyqyou** [comment]
在build setting中 Other Warning Flags中：-Wno-ambiguous-macro
