### ISSUE TITLE
YYadd

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYKit#187]
- (void)setBottom:(CGFloat)bottom {
    CGRect frame = self.frame;
    frame.origin.y = bottom - frame.size.height;
    self.frame = frame;
}

一直觉得这个方法怪怪的？
我设置底部位置。
应该是当前视图的父视图的高-自身高度-bottom参数才对吧？

**Comment by ibireme** [comment]
这个是从 three20 里流行开来的写法，很多公司和团队在手动布局时都还在用类似这一套东西，所以并没有什么问题。

对比一下 top 的用法，应该就能明白了。
