### ISSUE TITLE
YYKit 貌似没有 subspec ？

### ISSUE THREAD

**Issue by juvham** [ibireme/YYKit#188]
如果 我 一个 工程的 两个 target   一个 是 app  一个 是 today extension

那么 在 app 里 导入 yykit
在 today extension 里 导入 yycache

就回报错

希望 支持 sub subspec

**Comment by ibireme** [comment]
YYKit 和那些拆分出来的独立组件，还是有一些地方不一样的，所以不能直接 subspec。我不太推荐直接使用 `YYKit` 这个库，建议先尝试一下那些拆分出来的独立组件。这个在 readme `注意` 里也提到了相关原因。

**Comment by juvham** [comment]
嗯，还是 建议 YYKit 能做到模块化、最近又发现一个问题 已经提了issue 了 

在 app 启动的时候 内存 暴涨 profile 看 内存分配  貌似 是 yyimage 的 问题
好像是对图片解码造成的问题 。

期待你的回复 ， 谢谢

**Comment by ibireme** [comment]
每个组件都已经是独立的了。。
