### ISSUE TITLE
屏幕每秒60次刷新是由什么线程控制的？runloop如何参与其中

### ISSUE THREAD

**Issue by slemon** [ibireme/YYKit#189]
你好，我遇到一个问题，不知道大神能否帮忙解答：
iOS系统在程序静止的状态下（没有任何事件需要处理），它的屏幕是1秒被刷新60次，但runloop在程序静止的状态下，它是进入睡眠的，这个时候屏幕刷新是由哪个线程完成的？60秒刷新一次跟我们点击屏幕控件屏幕刷新是一回事吗？

**Comment by ibireme** [comment]
触摸事件和屏幕刷新的 Vsync 事件，都是由系统的 GraphicsServices/SpringBoard 线程处理并通过 IPC(Inter-process communication 进程间通信) 传递到对应 App 内部的，然后由 App 内主线程的 RunLoop port 接收。

话说这种问题更建议去 stackoverflow 之类的地方问，Github Issues 还是偏向于处理项目 Bug 的。

**Comment by slemon** [comment]
不好意思，我也是之前看到你的那篇《iOS 保持界面流畅的技巧》文章产生疑问，故来这里问了。

**Comment by ibireme** [comment]
就是说，主线程卡顿时，它就无法在额定时间内把新内容提交到 GPU，屏幕内容就不会有变化。这时无论屏幕刷新有多快，看到的内容不变，这就有卡顿的感觉了。
