### ISSUE TITLE
好强大啊

### ISSUE THREAD

**Issue by hhb19900618** [ibireme/YYKit#19]
你写的吗

**Comment by ibireme** [comment]
是的。。

**Comment by hhb19900618** [comment]
2015-12-02 10:51:17.884 YYKitDemo[1345:62080] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
发微博页面 点击表情按钮崩溃

**Comment by hhb19900618** [comment]
对了  你这里的label显示文本 支持自定义表情吗？

**Comment by ibireme** [comment]
关于 Demo 的崩溃，希望能提供更详细的信息，比如崩溃时停留处的截图，崩溃日志等，这样能方便定位。

关于 Label 的使用，可以见 YYText 这个单独项目的的说明文档，表情等都是支持的。

**Comment by hhb19900618** [comment]
不过感觉使用表情写的很麻烦  要先预定义对应字符呢
  NSMutableDictionary *mapper = [NSMutableDictionary new];
    mapper[@":smile:"] = [self imageWithName:@"002"];
    mapper[@":cool:"] = [self imageWithName:@"013"];
    mapper[@":biggrin:"] = [self imageWithName:@"047"];
    mapper[@":arrow:"] = [self imageWithName:@"007"];
    mapper[@":confused:"] = [self imageWithName:@"041"];
    mapper[@":cry:"] = [self imageWithName:@"010"];
    mapper[@":wink:"] = [self imageWithName:@"085"];
    mapper[@"002"] = [self imageWithName:@"002"];
    
    YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
    parser.emoticonMapper = mapper;
    
    YYTextLinePositionSimpleModifier *mod = [YYTextLinePositionSimpleModifier new];
    mod.fixedLineHeight = 22;
    
    YYTextView *textView = [YYTextView new];
    textView.text = @"Hahahah:smile:, it\'s emoticons::cool::arrow::cry::wink:\n\nYou can input \":\" + \"smile\" + \":\" to display smile emoticon, or you can copy and paste these emoticons.\n\nSee \'YYTextEmoticonExample.m\' for example. 002";
    textView.font = [UIFont systemFontOfSize:17];
    textView.textParser = parser;
    textView.size = self.view.size;
    textView.linePositionModifier = mod;
    textView.textContainerInset = UIEdgeInsetsMake(10, 10, 10, 10);
    textView.delegate = self;
