### ISSUE TITLE
内存暴涨造成 程序奔溃

### ISSUE THREAD

**Issue by juvham** [ibireme/YYKit#190]
程序启动 内存暴涨至 300M 在 5c 设备上造成内存压力导致闪退

 YYImageFrame *frame = [decoder frameAtIndex:0 decodeForDisplay:YES];

貌似在这一行代码

**Comment by ibireme** [comment]
首先需要明确你在使用什么功能。。上面这行代码是把图片文件解码到内存，这个方法会被许多地方调用到，包括显示网络图片、显示 GIF 图片等。显示网络会用到一个内存缓存来保存图片，但在收到内存警告、App 退到后台时会自动释放内存，不会造成闪退。显示动图时也会有一个很小的内存缓存，但这个缓存也会根据当前设备可用内存来动态调整，当收到内存警告时也会释放内存来保证安全。

建议先检查下你的代码是否有循环引用等问题、是否开启了 Zombie Objects 选项等。

如果是在显示 GIF/APNG/WebP 动图时遇到的问题，那

**Comment by juvham** [comment]
加载的网络jpg图片  图片尺寸  2400 ＊2800  3张
我测试过了，不使用 yywebimage  使用 afnetworking 提供的 加载图片的方法 不会引起暴涨

**Comment by juvham** [comment]
对，内存暴涨是会降回去，但是有时候增加过多程序就被干掉了。

发自我的 iPhone

**Comment by ibireme** [comment]
加载网络图片弄这么大的图。。。

这样一张图片解码后占用内存 25 MB，总共占 75 MB，就算非常凑巧在同一时刻解码并且加上画布内存，也不会超过 150 MB。除掉 App 本身的内存占用，再怎么说也不可能会达到 300 MB 的地步。没有 Demo 来复现的话，就无法知道问题是在哪个地方产生的了。

如果要说和 AFNetworking 的区别的话，AFN 的内存缓存是 100MB 上限，YYWebImage 也可以在这里手动设置一下：

    [YYWebImageManager sharedManager].cache.memoryCache.costLimit = 100 * 1024 * 1024;

如果这样还有问题，那就需要提供 Demo 来复现这个问题了。

**Comment by juvham** [comment]
知道是什么问题了，昨天图片的尺寸弄错了  图片 的 尺寸 是 6000 ＊ 6000 ＋的 jpg 图片 在 app 获取的 size 是 2000 多
确实 是同时渲染的 我是把图片加载在 一个 scrollView上的 。
应该是没有问题了
叫后台换过图片 没有问题了
多谢 热心解答
