### ISSUE TITLE
新工程创建YYTextView崩溃

### ISSUE THREAD

**Issue by haojian2016** [ibireme/YYKit#192]
![726daee2-7e40-4c32-929b-e41664766efc](https://cloud.githubusercontent.com/assets/16795422/14873215/a33c39da-0d26-11e6-9091-0dc12ad9e1de.png)

**Comment by ibireme** [comment]
已知问题（iOS 9.x 兼容问题），已修复。
更新代码到最新版本就可以了。

**Comment by haojian2016** [comment]
已经更新到最新版本啦，1.0.1的，Xcode是7.3，还是会出现这个问题，创建YYTextView就出现这个问题，YYLabel没有问题

**Comment by haojian2016** [comment]
不好意思，是我cocoapod版本的问题，获取不到最新的版本

**Comment by ibireme** [comment]
执行 pod setup 更新一下就行了。

**Comment by haojian2016** [comment]
嗯，是滴
