### ISSUE TITLE
Demo里UITableViewCell上的分隔线有时候在ios7的touch5上不显示。

### ISSUE THREAD

**Issue by zqpmaster** [ibireme/YYKit#193]
我看例子里是自己绘制一张小图然后拉伸作为分割线，但是这样在ios7的touch5上不显示。

**Comment by ibireme** [comment]
手头没有 iOS 7 的 Touch 5，无法复现。。“拿小图拉伸”这种做法，与设备无关。

**Comment by zqpmaster** [comment]
用图拉伸比设置背景色的性能要更优是吗？

**Comment by ibireme** [comment]
记得好像那条线是个很小的阴影，如果是阴影的话，显示图片比手动设置 layer 阴影性能要好。

**Comment by zqpmaster** [comment]
对，是阴影
