### ISSUE TITLE
UIDevice+YYAdd 中越狱方法crash -(bool)isJailbroken

### ISSUE THREAD

**Issue by keshiim** [ibireme/YYKit#194]
![image](https://cloud.githubusercontent.com/assets/3243095/14977153/640dee8a-1144-11e6-9ed0-91cbd40b4206.png)

**Comment by ibireme** [comment]
`isJailbroken` 这个方法内的调用都是安全的系统函数，并不会产生崩溃。。

查了一下，`xCon.dylib` 是个越狱插件，可以用来让设备绕过 App 的越狱检测，我不太清楚这个插件做了什么导致了崩溃。。

**Comment by keshiim** [comment]
你的意思手机越狱以后会在系统中插入xCon.dylib这种越狱插件吗？

**Comment by keshiim** [comment]
`xCon.dylib`

**Comment by ibireme** [comment]
正常情况下，即使越狱的手机也不会有这个东西。

这个日志说明这台手机的使用者越狱了，并且主动装了 xCon 这个插件来尝试把手机伪装成未越狱状态。

**Comment by keshiim** [comment]
OK, 谢谢

**Comment by g8168039** [comment]
我也遇到了这个问题...
