### ISSUE TITLE
CocoaPods的版本是0.9.11 pod下来WebP.framework冲突

### ISSUE THREAD

**Issue by guanghua07** [ibireme/YYKit#195]
我试了最新版本的1.0.5 的WebP.framework 是OK的，解决了WebP.framework冲突问题。
问题是cocoaPods上的版本还是0.9.11.   请问大神什么时候把1.0.5更新上去？

**Comment by ibireme** [comment]
CocoaPods 上已经是 1.0.5 了，http://cocoapods.org/?q=YYKit
更新时要保证 CocoaPods 列表也更新。

**Comment by sunbohong** [comment]
可以通过依次移除 other linker flags 里面的值来尝试解决此类问题。

**Comment by ibireme** [comment]
冲突的问题已经解决了，见：https://github.com/ibireme/YYImage/issues/24
只需要更新 pods 就好，即清除本地 pod 缓存，重新 pod install 一次，或者直接取线上的 WebP.framework 替换到本地。
