### ISSUE TITLE
是否可以实现被 YYTextBindingAttributeName 修饰的字符串禁止折行的功能？

### ISSUE THREAD

**Issue by sunbohong** [ibireme/YYKit#196]
[截图](http://upload-images.jianshu.io/upload_images/1711809-5baf052692d557c4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

如绿色区域所示，是否可以使其保持在同一行？

抱歉，图片上传一直在报错，贴链接了。

**Comment by ibireme** [comment]
见 https://github.com/ibireme/YYText/issues/62

**Comment by sunbohong** [comment]
@ibireme  也就是说，没法从 CoreText 层面解决，对吗？

**Comment by ibireme** [comment]
CoreText 的换行逻辑，在上层是不能直接控制的。。
