### ISSUE TITLE
在父容器为UIScrollVIew时.长按文本复制.会导致YYTextView滚动并失去选择文本效果

### ISSUE THREAD

**Issue by MonkeyHZT** [ibireme/YYKit#198]
如题

**Comment by ibireme** [comment]
能提供一些简单的测试代码吗？可能需要时间来看一下。。

**Comment by MonkeyHZT** [comment]
不好意思.我的失误.Demo已经上传
[Uploading YYTextViewToUIScrollViewDemo.zip…]()

**Comment by ibireme** [comment]
额。。貌似没有传上来。。

**Comment by MonkeyHZT** [comment]
好吧...这次可以了
[YYTextViewToUIScrollViewDemo.zip](https://github.com/ibireme/YYKit/files/265391/YYTextViewToUIScrollViewDemo.zip)

**Comment by ibireme** [comment]
"长按文本复制.会导致YYTextView滚动并失去选择文本效果" 没有复现。。但是在选择并拖动时确实需要延迟。

你可以试试调整一下 scrollView.delaysContentTouches 属性。

**Comment by MonkeyHZT** [comment]
首先长按选择几个文字.然后松开鼠标.选择任意一侧并开始上下拖动选择.会导致外层scrollView滚动并触发YYTextView的touchesCancel事件

**Comment by ibireme** [comment]
那就调整一下 scrollView.delaysContentTouches 和 scrollView.canCancelContentTouches 这两个值。
