### ISSUE TITLE
YYWebImage缓存问题

### ISSUE THREAD

**Issue by DaokunBai** [ibireme/YYKit#199]
YY大神，你好！
当我使用YYWebImage下载图片时，下载成功后，你对图片进行了缓存；
由于项目中需要显示圆形图片，所以我对图片进行了裁剪，裁剪成圆形图片后再显示；
但是此时YYWebImage缓存的是裁剪之前的图片，这时就会出现，即使重复下载已经下载过的图片，我依然会多次裁剪，所以刷新时，imageView会闪烁一下；

有没有方法可以将裁剪之后的圆形图片进行缓存，替代原图片缓存,这样重复下载的时候，拿到的缓存是裁剪之后的圆形图片！

有点绕嘴，不知道说清楚了没有，还望得到你的解答！
非常感谢！

__weak typeof(self) weakSelf = self;
[self setImageWithURL:[NSURL URLWithString:iconUrl] placeholder:placeholderImage options:YYWebImageOptionProgressiveBlur | YYWebImageOptionSetImageWithFadeAnimation completion:^(UIImage * _Nullable image, NSURL * _Nonnull url, YYWebImageFromType from, YYWebImageStage stage, NSError * _Nullable error) {
       
      // 异步裁剪图片
       if (weakSelf && image) {
            
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                
                UIImage *newImage = [image xdw_circleImage];
                
                dispatch_async(dispatch_get_main_queue(), ^{
                    
                    if (weakSelf && newImage) {
                        
                        weakSelf.image = newImage;
                    }
                });
            });
        }
}]

**Comment by ibireme** [comment]
如果只需要裁剪后的图片，可以用 Readme 中的 transform 方式：https://github.com/ibireme/YYWebImage#load-and-process-image

以后会考虑添加这种接口：https://github.com/ibireme/YYWebImage/issues/51

**Comment by DaokunBai** [comment]
谢谢！
