### ISSUE TITLE
非常期待你的后续作品

### ISSUE THREAD

**Issue by molon** [ibireme/YYKit#2]
阁下的东西是我看过国内干货最多的，太多值得我学习的。
非常期待大神的后续作品。

如果方便的话，可否认识下，希望在以后的开发过程中能得到指教。:)

扣扣： 姚姚启叁贰贰贰肆贰

**Comment by ibireme** [comment]
谢谢～
联系我的话可以微博 @ibireme 或博客 blog.ibireme.com，
扣扣目前只用于工作流程，抱歉。。

**Comment by molon** [comment]
@ibireme 无妨。有疑惑我开issue就是。 到时还请不吝赐教。 :)
