### ISSUE TITLE
在预编译头文件中引入#import <YYKit/YYKit.h>，但无法使用NSAttributedString 分类方法的情况

### ISSUE THREAD

**Issue by zsading** [ibireme/YYKit#201]
使用cocoapods 引入YYKit框架，#import <YYKit/YYKit.h>后，无法使用NSAttributedString分类方法，但YYLabel,YYTextView等使用正常

**Comment by zsading** [comment]
单个引入YYText正常，改成单个引入了

**Comment by chenZai90** [comment]
你好，请问你是怎么解决的，我现在也遇到了同样的问题
