### ISSUE TITLE
YYReachability中使用了一些ipv4的API，在ipv6环境下不兼容

### ISSUE THREAD

**Issue by liuf1986** [ibireme/YYKit#202]
https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1

**Comment by ibireme** [comment]
已添加兼容：https://github.com/ibireme/YYKit/commit/05daf81479c589955466b953141d63de82b55a12
