### ISSUE TITLE
使用了 inet_ntoa  是不是不兼容ipv6 啊 "UIDevice+YYAdd  还有 YYReachability

### ISSUE THREAD

**Issue by soocue** [ibireme/YYKit#204]
- (NSString *)ipAddressWIFI {
    NSString *address = nil;
    struct ifaddrs *addrs = NULL;
    if (getifaddrs(&addrs) == 0) {
        struct ifaddrs *addr = addrs;
        while (addr != NULL) {
            if (addr->ifa_addr->sa_family == AF_INET) {
                if ([[NSString stringWithUTF8String:addr->ifa_name] isEqualToString:@"en0"]) {
                    address = [NSString stringWithUTF8String:
                               inet_ntoa(((struct sockaddr_in *)addr->ifa_addr)->sin_addr)];
                    break;
                }
            }
            addr = addr->ifa_next;
        }
    }
    freeifaddrs(addrs);
    return address;
}

还有+ (instancetype)reachabilityWithAddress:(const struct sockaddr_in *)hostAddress {

**Comment by ibireme** [comment]
已添加支持。
