### ISSUE TITLE
-modelSetWithDictionary: 无法像-setValuesForKeysWithDictionary:一样处理被readonly修饰的属性

### ISSUE THREAD

**Issue by sunbohong** [ibireme/YYKit#208]
https://github.com/sunbohong/YYKit/commit/18d04e662e64aa0e259ac0d75be82dd9cdacc61b

为了更好的控制 model 属性存储逻辑，我只对外提供readonly的属性，实际上内部进行了一些特殊的处理。
之前通过在model内部通过系统的setValuesForKeysWithDictionary可以正常的赋值。但是通过NSObject+YYModel.m 却无法像之前那样进行赋值了。

**Comment by ibireme** [comment]
`modelSetWithDictionary` 会遵循外部调用者的身份来进行设值，即通过 property 对应的 getter 和 setter 方法进行操作，这会保证更好的兼容性。

你的代码中，`变量0` 最终是合成了 setter 方法，而 `变量1` 是没有 setter 方法的，所以这里会避免 `变量1` 被外部修改。

**Comment by sunbohong** [comment]
解决思路1：让`modelSetWithDictionary` 和 `setValuesForKeysWithDictionary` 的处理方式表现一致。（通过宏等方式）
解决思路2：让`modelSetWithDictionary` 方法返回`NO`，由调用者决定是否再次调用 `setValuesForKeysWithDictionary` 。

**Comment by sunbohong** [comment]
@ibireme  如果需要设置实例变量，如何通过 `NSObject+YYModel` 实现呢？

**Comment by ibireme** [comment]
YYModel 是实现的 Model 对象的设置，Model 对外是通过 property 来暴露内部数据的，内部数据是不会暴露到外部的，如果通过外部直接访问就会破坏了 Model 的设计意图。

setValuesForKeysWithDictionary 是用 KVC 来设置值的，它的表现和 Model 逻辑有很多差别。它会尝试用 property、getter/setter、ivar 等好几个方式来处理 key-value pair，并且没有自动转换，失败时会抛出异常，除此之外，KVC 的性能也不是很高，兼容性也稍差。这并不是处理 Model 的好方法。。

**Comment by sunbohong** [comment]
- (BOOL)modelSetWithDictionary:(NSDictionary *)dic {
	    if (!dic || dic == (id)kCFNull) return NO;
	    
	    if (![dic isKindOfClass:[NSDictionary class]]) return NO;
	    
	    _YYModelMeta *modelMeta = [_YYModelMeta metaWithClass:object_getClass(self)];
	    if (modelMeta->_keyMappedCount == 0) return NO;
	    
	    if (modelMeta->_hasCustomWillTransformFromDictionary) {
	        dic = [((id < YYModel >)self) modelCustomWillTransformFromDictionary:dic];
	        if (![dic isKindOfClass:[NSDictionary class]]) return NO;
	    }


根据NSObject+YYModel.m里面的实现方法，它会在以下情况下返回NO。

1.  dic  不存在
1.  dic 类型错误
1.  _mapper为空
1. model transform 信息错误

但是，当一个Model的部分属性不被readonly修饰时，调用`-modelSetWithDictionary:`方法后，虽然dic里面的所有属性均没有设置成功，却依旧返回了YES。
为了方便外部调用者进行赋值，这里是否应当添加对其的逻辑处理？

**Comment by sunbohong** [comment]
当设计Model时，我们通常会对属性添加`readonly`修饰符。

例如，

`
@property (nonatomic, copy, readonly) NSString *title;
`

当Model进行了网络请求后，为了更新信息，我们通过某种方式更新属性。

例如，

    //方案1
    - (void)setWithDictionary:(NSDictionary *)dic {
        _pro0 = dic[@"pro0"];
        _pro1 = dic[@"pro1"];
        
        [self setValuesForKeysWithDictionary:dic];
    }

或者，

    //方案2
    - (void)setWithDictionary:(NSDictionary *)dic {        
        [self setValuesForKeysWithDictionary:dic];
    }

当属性很多时，显然用第二种方案更加合适。

因为KVC 的性能不高，兼容性稍差。所以，我们需要一些替代品。

为了避免重复造轮子，我希望能够把成熟开源的`YYModel`应用在自己的应用内。

但是，目前很遗憾的发现，我无法直接用`YYModel`替换之前的`KVO`方案。

 所以，我在这里诚恳的希望作者能够提供在`Model`内部对`iVar`进行赋值的扩展方法。

比如，方法名可以叫做`-modelSetPropertyAndIvarWithDictionary:`

它可以检测`iVar`和可用`property`的是否存在，并对其进行赋值。

    - (void)setWithDictionary:(NSDictionary *)dic {
        [self modelSetWithDictionary:dic];
       // [self modelSetPropertyAndIvarWithDictionary:dic];
    }

**Comment by ibireme** [comment]
抱歉目前不会考虑：1. 和这个库的设计思路有些差距，2. 如果支持，需要改动的代码实在太多，也需要更多的 test case。

**Comment by sunbohong** [comment]
> YYModel 是实现的 Model 对象的设置，Model 对外是通过 property 来暴露内部数据的，内部数据是不会暴露到外部的，如果通过外部直接访问就会破坏了 Model 的设计意图。例如 Foundation/UIKit 中有些类的属性就是 readonly 的，如果绕开这个限制直接修改了内部 ivar，就可能会产生一些异常情况。



1. 在OC中，比较合理的接口与API设计是**尽量使用不可变对象**（即通过`readonly`属性修饰）
 
4. 在OC中，比较合理的接口与API设计是**在内部通过readwrite再写一次属性**（我开`issue`的起始原因是为了偷懒）

5. 1. 在OC中，因为`runtime`的原因，所有的属性和变量在实际上都是可以可读可写的。

2. YYModel虽然不会修改被`readonly`修饰的属性，但实际上却在内部会修改通过下面代码处理后的属性。从破坏性来说，这种作用更大。
比如，在`YYModel`的设计中下面的代码在实际作用上已经重写了`setter`方法，只看`.h`文件根本不知道把`id`传入后会有改变`userID`的***副作用***。
    
    ```
    @implementation YYWeiboUser
    + (NSDictionary *)modelCustomPropertyMapper {
        return @{@"userID" : @"id",
    ```

**Comment by ibireme** [comment]
1、没错，道理是这样。这种 API 设计思路目的是防止外界不当的调用导致的问题，如果绕开了这个逻辑用 runtime/KVC 来修改，则调用者需要为他自己的代码负责。调用 yy_modelWithJSON 或 yy_modelSetWithJSON 这样的方法时，原则上也是遵循这种思路，只对可读写 property 进行设置，而不从外面修改 readonly 的属性。

2、内部可以直接访问 ivar，没必要用 readwrite 再重写一次。

3、是的，所以用 runtime/KVC 或相似逻辑进行设置，并不是好的做法，调用者需要为自己的代码负责。

4 这是一个外部的协议，返回的是外部的 JSON 如何映射到 Model 外部的属性名，这个映射是外部进行的，与 Model 内部无关，更谈不上破坏性。
