### ISSUE TITLE
使用YYReachability监听网络状态的时候。。 WIFI状态下NotifyBlock回调无网络~

### ISSUE THREAD

**Issue by MichaelHuyp** [ibireme/YYKit#209]
这是我的代码。。 大神看下是我用错了么
#pragma mark - 网络监测
- (void)networkMonitoring
{
    self.reachability = [YYReachability reachabilityWithHostname:@"https://www.baidu.com/"];
    [self.reachability setNotifyBlock:^(YYReachability * reachability) {
        YYReachabilityStatus status = reachability.status;
        YYReachabilityWWANStatus wwanStatus = reachability.wwanStatus;
        switch (status) {
            case YYReachabilityStatusNone:
            {
                YPLog(@"无网络")
                break;
            }
            case YYReachabilityStatusWWAN:
            {
                switch (wwanStatus) {
                    case YYReachabilityWWANStatusNone:
                    {
                        YPLog(@"蜂窝网络");
                        break;
                    }
                    case YYReachabilityWWANStatus2G:
                    {
                        YPLog(@"2G");
                        break;
                    }
                    case YYReachabilityWWANStatus3G:
                    {
                        YPLog(@"3G");
                        break;
                    }
                    case YYReachabilityWWANStatus4G:
                    {
                        YPLog(@"4G");
                        break;
                    }
                    default:
                        break;
                }
                break;
            }
            case YYReachabilityStatusWiFi:
            {
                YPLog(@"Wifi网络");
                break;
            }
            default:
                break;
        }
        
    }];
}

**Comment by ibireme** [comment]
reachabilityWithHostname 应该传入 host name，例如 "www.baidu.com"。

**Comment by MichaelHuyp** [comment]
好的 谢谢大神 😊
