### ISSUE TITLE
YYTextView in markdown example has wrong edge insets on iOS6

### ISSUE THREAD

**Issue by skyline75489** [ibireme/YYKit#21]
This is what happens when scrolling to bottom. The content is not fully showed. On iOS 7 and later it's OK.

![img_0385](https://cloud.githubusercontent.com/assets/4710575/11501740/98a9f432-9871-11e5-8e32-2c1a573ff955.jpg)

**Comment by ixizi** [comment]
try to set `contentInset`

**Comment by ibireme** [comment]
It's only a demo... and currently I don't have an iOS 6 device...
Wontfix...
