### ISSUE TITLE
YYTextView  文本中存在大量自定义表情时，复制功能会导致卡机。

### ISSUE THREAD

**Issue by NSaylor** [ibireme/YYKit#212]
如题~

**Comment by ibireme** [comment]
默认情况下，copy 时会吧 attributedText 进行 Archive，这其中就包括了所有 attachment。如果不需要保持这些东西，可以把 textView.allowsCopyAttributedString 设置为 NO。

**Comment by NSaylor** [comment]
fixed thanks
