### ISSUE TITLE
NSObject+YYAdd中swizzleInstanceMethod与swizzleClassMethod

### ISSUE THREAD

**Issue by xxlxiong** [ibireme/YYKit#213]
这两个交换Method的方法，源码里的method都是通过class_getInstanceMethod获取的，这是否是BUG?还是有什么区别?

**Comment by ibireme** [comment]
替换类方法时，先取了 meta class：Class class = object_getClass(self);

**Comment by xxlxiong** [comment]
不能用class_getclassmethod这个方法来取类方法吗？

**Comment by ibireme** [comment]
都一样啊，能实现就行。
