### ISSUE TITLE
关于yyweakproxy

### ISSUE THREAD

**Issue by dustturtle** [ibireme/YYKit#214]
如果用- (void)performSelector:(SEL)aSelector withObject:(nullable id)anArgument afterDelay:(NSTimeInterval)delay; 方法来实现循环定时操作，此处就不能使用weakProxy代理来解决retain cycle问题了; 因为nsproxy类不是nsobject对象，不支持这一组操作。
对于这个问题作者有没有思路啊？ 个人比较喜欢用这个方法。请教一下哈

**Comment by ibireme** [comment]
感觉没什么太好的办法，这个会向对象发的消息，会隐含把 self 传进去。。

循环定时操作我可能更偏向用 GCD：

    - (void)tick {
        // do something
        __weak typeof(self) _self = self;
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [_self tick];
        });
    }

**Comment by dustturtle** [comment]
嗯，gcd确实是比较好，精度也高，也没有nstimer的问题
