### ISSUE TITLE
关于NSObject+YYAddForARC

### ISSUE THREAD

**Issue by dustturtle** [ibireme/YYKit#217]
这个category的用途是啥？看源码没太明白；NSObject_YYAddForARC类的定义有什么用？其他地方好像没有用到？望解惑！~谢谢

**Comment by ibireme** [comment]
ARC 下，retain/release/retainCount 这些方法都不能用了，但调试代码的时候偶尔也想用一下看看（比如看一下 retainCount），所以这里把原来的函数又改个名字暴露了出来。

平时基本用不到。。。

**Comment by dustturtle** [comment]
我看代码大概能明白你的意图，但是不清楚怎么用，怎么起作用。还有那个空类的定义也不清楚起啥作用

**Comment by ibireme** [comment]
哦。。那个空的类，作用是这样的：如果一个文件里，只有 category 但没有 class 的时候，在打包到 .a 并链接的时候，那个 category 会被默认忽略掉，https://developer.apple.com/library/mac/qa/qa1490/_index.html

这个空的类就相当于是个占位，保证那个 category 不会被忽略。

**Comment by dustturtle** [comment]
我看你别的category里面有用过一个宏定义，这个空的类和那个是一样的吧？ 你这个类是在arc下用，引入这个category头文件（这个category的.m打标签运行在mrc模式），这样一来就可以在arc下使用你封装的方法了。我现在才明白过来，哈哈～ 感谢！很有意思的思路

**Comment by snowCoveredPoetry** [comment]
@dustturtle  你说那个空类  类名叫什么啊

**Comment by ibireme** [comment]
https://github.com/ibireme/YYKit/blob/master/YYKit/Base/Foundation/NSObject%2BYYAddForARC.m#L14-L15

**Comment by snowCoveredPoetry** [comment]
谢谢 @ibireme   不过有一个问题要请教你一下啊
我看你发微博 里面 inputAccessoryView 最左边一个 添加图片 这是一个 九宫格的图片吗 就跟新浪微博一样吗
如果跟新浪微博一样 我想问一下 这个应该怎么样布局啊。
1.添加一个视图 在YYTextView 里面吗 当作 九宫格图片 父类的展示区域
请 楼主 指教一下

**Comment by ibireme** [comment]
那个，Demo 里应该都有代码吧。。

**Comment by snowCoveredPoetry** [comment]
@ibireme  图片选择那一块 根本就没有做
