### ISSUE TITLE
关于WWAN  后台模式到前台模式，系统currentRadioAccessTechnology这个值是空的

### ISSUE THREAD

**Issue by pengleelove** [ibireme/YYKit#221]
```
    if (self.networkInfo) return YYReachabilityWWANStatusNone;
    NSString *status = self.networkInfo.currentRadioAccessTechnology;
    if (!status) return YYReachabilityWWANStatusNone;
```
self.networkInfo.currentRadioAccessTechnology  这个值在按下home 键之后，再去进入APP，手动获取WWAN 状态，获取不到值  ，4G条件下，正在播放视频或者音乐的时候，APP进入后台，会有这个情况出现，就是还有没有别的可以使用
或者你看下这个stack 上的连接，有其他方法可以替换么：[CTTelephonyNetworkInfo's currentRadioAccessTechnology Ambiguous response](http://stackoverflow.com/questions/34668588/cttelephonynetworkinfos-currentradioaccesstechnology-ambiguous-response)

**Comment by ibireme** [comment]
Reachability 用法是这样的：先设置 notifyBlock 启动监听，然后在 block 内去取网络状态，这样一般是准确的。直接在外面去取状态值，可能会不准确或有阻塞。

苹果的 Reachability 也一样。

**Comment by pengleelove** [comment]
恩，那个自动监听改变的方法没错，就是有时候需要判断一下目前的网络状态，所以想着会提前判断一下，但是结果反而无效了，我昨天加了一个获取状态栏的方法，嘿嘿
