### ISSUE TITLE
引入YYKit后，Masonry布局的失效

### ISSUE THREAD

**Issue by ulongx** [ibireme/YYKit#223]
引入YYKit后，Masonry布局的页面失效，就全部乱了

**Comment by hengcj** [comment]
category命名冲突？

**Comment by ibireme** [comment]
与 Masonry 没关系啊。。
另外，建议如果只需要某个模块的话，单独引入。

**Comment by hengcj** [comment]
我也是yykit和masonry都用，都是pod管理的，木有出现问题，是不是引入别的库造成的？

**Comment by ulongx** [comment]
嗯，我是在pch中直接饮用了YYKit，昨晚我查了一下，是UIView＋YYAdd里面的left，right这些方法和masonry的冲突了

**Comment by ulongx** [comment]
之后我就只引入了YYText 模块

**Comment by hengcj** [comment]
我觉得pch里面做全局引用要慎重，因为OC没有命名空间，很容易打架~

**Comment by ulongx** [comment]
嗯是的，有些框架里面的Category会重名相互冲突,谢谢@hengcj

**Comment by hengcj** [comment]
客气了~

**Comment by ibireme** [comment]
这么说想起来了，好像 masonry 有个宏开关来控制，打开后就会和 left right 那套东西有冲突。

**Comment by ulongx** [comment]
对对，我为了方便，把那个打开了

**Comment by zhangqibin** [comment]
masonry中是什么宏，来控制left冲突？

**Comment by zhangqibin** [comment]
找到了：MAS_SHORTHAND
