### ISSUE TITLE
ipv6处理

### ISSUE THREAD

**Issue by jw10126121** [ibireme/YYKit#225]
因为应用审核因为Ipv6被拒绝，所有用到Reachability的地方只有YYKit，看了一下YYReachability.h的代码，是否没有做ipv6支持的判断？
+ (instancetype)reachabilityForLocalWifi {
    struct sockaddr_in localWifiAddress;
    bzero(&localWifiAddress, sizeof(localWifiAddress));
    localWifiAddress.sin_len = sizeof(localWifiAddress);
    localWifiAddress.sin_family = AF_INET;
    localWifiAddress.sin_addr.s_addr = htonl(IN_LINKLOCALNETNUM);
    YYReachability *one = [self reachabilityWithAddress:(const struct sockaddr *)&localWifiAddress];
    one.allowWWAN = NO;
    return one;
}

**Comment by ibireme** [comment]
reachability 这个地方，其实用之前的代码也没问题。注意使用时先设置回调，之后在回调里去判断网络状态。这个如果用苹果的 Reachability 也推荐这样做。 

苹果审核时，不会关注代码内部实现，它只会在 IPv6 环境下对 App 进行可用性测试。

**Comment by jw10126121** [comment]
谢谢
