### ISSUE TITLE
同时引用YYText和YYKit重复YYTextRunDelegate及redefine YYTextVerticalAlignment

### ISSUE THREAD

**Issue by sinzang** [ibireme/YYKit#23]
同时引用YYText和YYKit重复YYTextRunDelegate及redefine YYTextVerticalAlignment，望修改以便几个库可以同时引用

**Comment by ibireme** [comment]
YYKit 包含了 YYText/YYImage 等库，所以如果引用了 YYKit，那就没必要再引用其他几个库了。

另外，如果要使用的话，还是推荐使用单独的 YYText/YYImage 等单独的库～

**Comment by sinzang** [comment]
Oh，我引得YYKit比较早，pod 'YYKit', '~> 0.2.0'，并没有包含YYText、YYImage，只是category的集合

**Comment by sinzang** [comment]
另外，建议pod引的库，文件夹分类能和Demo里面的一样，方便查阅，现在的都是所有的文件全部放在一起，没有一点组织结构，谢谢了。

**Comment by ibireme** [comment]
pod 默认会把文件都放到一起。指定文件夹的话，可能需要用 subspec 了。以后有时间我会尝试一下。
