### ISSUE TITLE
NSString+YYAdd.h --> -containsString: 这个方法建议改个名字, 因为会被系统频繁的调用

### ISSUE THREAD

**Issue by bigtreenono** [ibireme/YYKit#231]
复现步骤: 在 -containsString: 这个方法打个断点, 详见截图
![image](https://cloud.githubusercontent.com/assets/8012469/16103952/8e50a63c-33af-11e6-9199-2d9617b00175.png)

**Comment by ibireme** [comment]
旧版 iOS 系统没有这个方法，这里是为了兼容。另外这个方法和系统实现的逻辑是一样的。

**Comment by bigtreenono** [comment]
ok, thx
