### ISSUE TITLE
关于后台线程计算布局的疑问

### ISSUE THREAD

**Issue by ShelinShelin** [ibireme/YYKit#243]
“当获取到 API JSON 数据后，我会把每条 Cell 需要的数据都在后台线程计算并封装为一个布局对象 CellLayout”，这是摘自你[博客](http://blog.ibireme.com/2015/11/12/smooth_user_interfaces_for_ios/)的一段话。
1、请教列表优化的Demo中关于后台线程计算布局的实现应该定位在哪个文件，最近阅读源码的时候一直没有发现
2、当后台线程计算布局，刚进入页面怎样去处理当前页面的显示（此时还未返回布局的计算结果）
谢谢！

**Comment by ibireme** [comment]
那个就在 WBStatusTimelineViewController.m viewDidLoad 里，模拟了一下解析过程。

刚进页面，没有数据时，可以加一些 loading 界面，或者像 Facebook 那样，展示一些占位符界面。

**Comment by ShelinShelin** [comment]
OK，之前理解的想太复杂了，谢谢！
