### ISSUE TITLE
YYTextView,复制粘贴图片文字出现[objc]的问题

### ISSUE THREAD

**Issue by leibaozai** [ibireme/YYKit#244]
大神你好,在使用YYTextView,复制粘贴图片文字出现[objc]的问题
操作描述：YYTextView输入文字，图片，文字，然后全选赋值粘贴。只出现粘贴文字，在ios手机上，Mac上都没问题。但是在Windows和安卓手机上，粘贴的文字，之前是图片的地方会出现[objc]的字样，大神可知道是什么原因吗？？？
![1](https://cloud.githubusercontent.com/assets/12133314/16443819/66d93cc8-3e0d-11e6-82f5-26fe3d8b1119.png)

**Comment by ibireme** [comment]
那是 unicode 占位符 uFFFC，用于作为图片等附加文字的占位。这个字符可能会在不同平台上有不同喧嚷样式吧，如果只需要纯文本，那可以把这个字符过滤掉。

**Comment by leibaozai** [comment]
已解决，谢谢了！
