### ISSUE TITLE
TextAttachments怎么从屏幕的左上角开始显示,而且文字的高度不定的

### ISSUE THREAD

**Issue by qiaoming1990321** [ibireme/YYKit#246]
contentText.font = font;
    _label.userInteractionEnabled = YES;
    _label.numberOfLines = 0;
    _label.textVerticalAlignment = YYTextVerticalAlignmentCenter;
    _label.size = CGSizeMake(self.view.width - 20, rect.size.height);
    _label.center = CGPointMake(self.view.width / 2, self.view.height / 2 - (kiOS7Later ? 0 : 32));
    
        _label.backgroundColor = [UIColor groupTableViewBackgroundColor];
    [_label sizeToFit];

这一段代码怎么从屏幕的左上角开始显示,而且文字的高度不定的

**Comment by ibireme** [comment]
verticalAlignment 设置为 top，然后调整 label 的 frame。

**Comment by qiaoming1990321** [comment]
_label.textVerticalAlignment = YYTextVerticalAlignmentTop;
    
//    _label.size = CGSizeMake(self.view.width - 20, 400);
//    _label.center = CGPointMake(self.view.width / 2, self.view.height / 2 - (kiOS7Later ? 0 : 32));
    _label.frame = CGRectMake(10, 0, self.view.width - 20, self.view.height);

改过之后还是空了一个很大的位置,


//第二个问题:最后一行的文字为什么那么小?
[contentText appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];
            [contentText appendAttributedString:[[NSAttributedString alloc] initWithString:@"（按从小到大顺序填写）.0123456789－[1,4,7]" attributes:nil]];
            [contentText appendAttributedString:[[NSAttributedString alloc] initWithString:@"（按从小到大顺序填写）.0123456789－[1,4,7]" attributes:nil]];

能不能留一个邮箱,我截图给你看下,谢谢  我的邮箱qiaoming321@126.com

**Comment by ibireme** [comment]
截图可以直接拽到评论框上传。

另外，可以给 textView.layer 加一个 borderColor 来看看边缘，另外，开一下 YYText 的 debug 来看卡排版结果：https://github.com/ibireme/YYText#debug-1

**Comment by qiaoming1990321** [comment]
非常感谢您的细心指导,排版问题解决了.但是导入环信的时候,出现了一个新的问题,
duplicate symbol _ff_init_cabac_states in:
    /Users/xueersi/Documents/技术积累/Study/Study/QMStudy/Thirds(第三方)/环信/EaseMobSDK/lib/libEaseMobClientSDK.a(cabac.o)
    /Users/xueersi/Documents/技术积累/Study/Study/YY图文混排/YYKit/bpg.framework/bpg(cabac.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

这个能不能提供一点解决方案,谢谢

**Comment by qiaoming1990321** [comment]
解决了 祝您生活愉快

**Comment by ibireme** [comment]
👌
那个 bpg.framework 是没必要导入的。
