### ISSUE TITLE
富文本缓存

### ISSUE THREAD

**Issue by leibaozai** [ibireme/YYKit#249]
我通过转data，发现图片读取不出来。目前没找到其他的办法，请教一下。
存
NSData *data = [self.yyTextView.attributedText dataFromRange:NSMakeRange(0, self.yyTextView.attributedText.length) documentAttributes:@{NSDocumentTypeDocumentAttribute:NSRTFDTextDocumentType} error:nil];

读
self.yyTextView.attributedText = [[NSAttributedString alloc] initWithData:data options:@{NSDocumentTypeDocumentAttribute : NSRTFDTextDocumentType} documentAttributes:nil error:nil];

**Comment by ibireme** [comment]
可以用 YYTextArchive 来进行归档解档。

**Comment by leibaozai** [comment]
谢谢回复，解决了归档解档的问题。但是解档后之前的图片可点击，现在怎么去重新设置点击区域，并且还有自定义view上添加UIButton，用YYTextAttachment好像不能区分是图片还是自定义view。

**Comment by ibireme** [comment]
这里归档时用的是 UIView 自身的 NSCoding 协议，具体能存储多哪些属性取决于视图本身的实现。
另外，TapGesture、block、target 这些都是运行时生成的逻辑，是无法保存下来的。这需要手动进行处理。

**Comment by leibaozai** [comment]
谢谢大神，我再手动处理下，看能不能行。
