### ISSUE TITLE
dispatch_async_on_main_queue 貌似不是异步

### ISSUE THREAD

**Issue by JianboYan** [ibireme/YYKit#25]
static inline void dispatch_async_on_main_queue(void (^block)()) {
    if (pthread_main_np()) {
        block();   // 直接执行算同步吧?
    } else {
        dispatch_async(dispatch_get_main_queue(), block);
    }
}

**Comment by ibireme** [comment]
是的。。如果是主线程就直接执行了。。
这个函数命名主要是为了和 dispatch_async_on_main_queue 有区别，但并不是很合适。。
