### ISSUE TITLE
YYTextView加载太多内容会不显示

### ISSUE THREAD

**Issue by PeterLYY** [ibireme/YYKit#256]
我用YYTextView加载一部小说，结果不显示，我减少显示的文字就可以了

**Comment by CodeLife2012** [comment]
YYTextView目前并不适合做大量文本的显示...

**Comment by ibireme** [comment]
模拟器不能显示大于 4096 高度的图片 Layer，换成真机就正常了。

另外。。一部小说这么多文字。。确实有点不太适合用这个来做。
