### ISSUE TITLE
我将YYKit Demo做了个抽离，请问可以吗？

### ISSUE THREAD

**Issue by ding379985418** [ibireme/YYKit#258]
bireme _你好，我发现Demo中图片浏览器效果不错，然后对其做了个抽离，上传到上了[https://github.com/ding379985418/YYPhotoBrowseView](rul),请问可以吗？如果您要是觉得不妥请联系我，谢谢！！   Email:ding379985418@live.com

**Comment by ibireme** [comment]
没问题～
这里的 License 是 MIT 的，很宽松，基本全没什么限制。

**Comment by ding379985418** [comment]
谢谢了！！
