### ISSUE TITLE
Date的isLeapYear实现貌似有问题

### ISSUE THREAD

**Issue by JianboYan** [ibireme/YYKit#26]
闰年计算方法:
1、年份能被4整除；
2、年份若是100的整数倍的话，需被400整除，否则是平年。

但是实现是
- (BOOL)isLeapYear {
    NSUInteger year = self.year;
    return ((year % 400 == 0) || (year % 100 == 0) || (year % 4 == 0));
}
从代码上来看, 被400整除或被100整除或被4整除都行,
总体上而言, 就是被4整除即可.

**Comment by JianboYan** [comment]
之前提的 YYKitMacro里面的issue貌似不见了
static inline void dispatch_async_on_main_queue(void (^block)()) {
    if (pthread_main_np()) {
        block();  // 直接回调应该是同步的吧?
    } else {
        dispatch_async(dispatch_get_main_queue(), block);
   }

**Comment by ibireme** [comment]
闰年那个是有。。我改一下～

另外那个 Issue 在这里：https://github.com/ibireme/YYKit/issues/25

**Comment by ibireme** [comment]
Fixed~  https://github.com/ibireme/YYKit/commit/3f2e045acda70dc140ec8cf0d14cc37692210559
