### ISSUE TITLE
NSObject (YYAddForKVO)观察者未及时释放问题

### ISSUE THREAD

**Issue by TreasureU** [ibireme/YYKit#260]
Hi 大神你好：
使用关联对象存储观察者后，在removeObserverBlocks时，仅仅是移除了观察者的身份，但是观察者本身并没有被释放，且也没有从该数组中被移除。
这会导致两个问题：
1.下次继续 removeObserverBlocks 时会重复remove同一个观察者对象，会导致crash!
2.无效的观察者一直霸占着内存，造成内存泄露。

麻烦大神及时修复。

**Comment by ibireme** [comment]
能提供一些复现问题的代码吗？我无法复现 crash 和内存泄漏的问题。

**Comment by TreasureU** [comment]
只需要在一个对象上添加一个监听，然后执行removeObserverBlocks。然后，再添加一个监听，然后再removeObserverBlocks。这个时候就会crash。
内存泄露是指观察者一直在数组中残留，没有移除。

**Comment by ibireme** [comment]
测试下面的代码：
        UIView *v = [UIView new];
        [v addObserverBlockForKeyPath:@"frame" block:^(id obj, id oldVal, id newVal) {}];
        [v removeObserverBlocks];
        [v addObserverBlockForKeyPath:@"frame" block:^(id obj, id oldVal, id newVal) {}];
        [v removeObserverBlocks];

没有问题。。

能贴一下你的测试代码吗？

**Comment by TreasureU** [comment]
抱歉额，貌似是我这边弄错了:)
大神的代码棒棒的~
