### ISSUE TITLE
NSData+YYAdd 中的base64EncodedString问题

### ISSUE THREAD

**Issue by TreasureU** [ibireme/YYKit#261]
Hi 你好：
我发现NSData+YYAdd 的base64EncodedString在申请 output 字符数组时，使用以下代码：
NSUInteger length = self.length;
    if (length == 0)
        return @"";
    
    NSUInteger out_length = ((length + 2) / 3) * 4;
    uint8_t *output = malloc(((out_length + 2) / 3) * 4);
    if (output == NULL)
        return nil;
其重复申请了 （（(length +2) / 3 * 4）+2）/ 3 * 4  的大小，但其实base64编码后的大小没有这么大。
感觉使用以下方法可以得到精确的计算值：
NSUInteger length = self.length;
    if (length == 0)
        return @"";
    
    NSUInteger out_length = length;
    if( out_length % 3 != 0 ){
        out_length = out_length + ( 3 - out_length % 3 );
    }
    out_length = (out_length / 3) * 4;
    uint8_t *output = malloc(out_length);
    if (output == NULL)
        return nil;
    //清理操作
    memset(output, 0, out_length);

要是我的理解有什么不对的地方，还请帮忙指出，谢谢。

**Comment by ibireme** [comment]
第 391 行确实多余了，直接 malloc(out_length) 就行。
((length + 2) / 3) * 4 这个结果和上面你的 if 判断后的结果是一样的。
