### ISSUE TITLE
请教下YYCahe中的磁盘缓存监听terminate通知调用的函数有什么特殊意义吗？

### ISSUE THREAD

**Issue by zxl20zxl** [ibireme/YYKit#263]
- (void)_appWillBeTerminated {
    Lock();
    _kv = nil;
    Unlock();
}
app终止后，_kv不就是自动置为nil了吗

**Comment by ibireme** [comment]
应该是避免 will terminated 和 did terminated 之间的访问吧。

**Comment by zxl20zxl** [comment]
明白了
