### ISSUE TITLE
[YYModel] usage: modelCustomTransformFromDictionary returns void instead of BOOL

### ISSUE THREAD

**Issue by skyline75489** [ibireme/YYKit#27]
From WBEmoticonGroup:

```objective-c
- (void)modelCustomTransformFromDictionary:(NSDictionary *)dic {
    [_emoticons enumerateObjectsUsingBlock:^(WBEmoticon *emoticon, NSUInteger idx, BOOL *stop) {
        emoticon.group = self;
    }];
}
```

This returns `void` instead of `BOOL`. On iOS6 the return value seems to be considered as `NO`, which is more reasonable in my perspective, causing crash when entering emoticon panel. 

However, on iOS7 and above `void` seems to be treated as `YES` and the code works. Is this by design or something?

**Comment by ibireme** [comment]
Updated ~
Thanks!

**Comment by skyline75489** [comment]
This fixed the question. But seriously, do you have any idea why would the behavior be different between iOS 6 & 7? I have no clue about this. I didn't even know that `void` would be the same as 'YES`, for god's sake...

**Comment by ibireme** [comment]
I don't know...

**Comment by skyline75489** [comment]
This is really, really weird. Gotta admit. Perhaps something to do with compiler and runtime. Never mind. I think we can let this go since the problem is solved.
