### ISSUE TITLE
YYTextLayout 使用之后 YYLabel的truncationToken失效....

### ISSUE THREAD

**Issue by FelixYin66** [ibireme/YYKit#277]

**Comment by FelixYin66** [comment]
问题已解决...在布局文本时，只需要设置YYTextContainer 的两个属性《truncationType，truncationToken》，就可以实现YYLabel的truncationToken功能...

**Comment by ibireme** [comment]
👌

**Comment by juefeiyechen** [comment]
真的是。必须YYTextLayout 必须2个同时设置
