### ISSUE TITLE
NSObject+YYAdd 发现一处bug

### ISSUE THREAD

**Issue by MRsummer** [ibireme/YYKit#279]
case 'f': // 4: float / CGFloat(32bit)
            { // 'float' will be promoted to 'double'.
                double arg = va_arg(args, double);
                float argf = arg;
                [inv setArgument:&argf atIndex:index];
            }
                
忘记写break了  浮点数会出错

**Comment by ibireme** [comment]
Thanks!
Fixed: https://github.com/ibireme/YYKit/commit/0c66d5e9256ec093aceec895b0d41fea045c2c48
