### ISSUE TITLE
关于图片https加载问题

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYKit#282]
你好，请问用https的方式加载图片的证书要怎么设置，证书是在本地的，以前是自己写了一个imageDownLoader，然后在- (void)connection:(NSURLConnection *)theConnection willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge方法里加载证书。如果用YYImage的话，要怎么设置这个证书？

**Comment by ibireme** [comment]
目前没有直接对外的接口。

如果你能修改代码的话，那就在 YYWebImageOperation.m 里修改一下那个方法。

不然就比较麻烦，需要先子类化 YYWebImageOperation，重写上面那个方法；然后子类化 YYWebImageManager，重写 requestImageWithURL... 方法，返回你的子类化的 Operation。

**Comment by wy19901227** [comment]
嗯，可是我是pod的代码，直接在你里边改不好吧。

发自我的 iPhone

**Comment by ibireme** [comment]
再或者，用 method swizzle 来替换 YYWebImageOperation.m 里那个方法吧，比较 trick 但是简单些。。

**Comment by wy19901227** [comment]
嗯嗯，好的

发自我的 iPhone
