### ISSUE TITLE
关于YYLabel的问题

### ISSUE THREAD

**Issue by ytx0574** [ibireme/YYKit#284]
YYLabel设置attributedText的时候自己计算高度有点奇怪,  多行的时候, 高度计算正常, 单行的时候, 就变得高多了.  这是有什么需要特殊注意的吗?

**Comment by ibireme** [comment]
YYLabel 是用 CoreText 的结果来绘制的，所以计算高度需要用 YYTextLayout 来处理。

**Comment by ytx0574** [comment]
很奇怪啊. 一行的时候算得过高了.   不过算了, 我用sizeToFit重置高度了

**Comment by ibireme** [comment]
👌
