### ISSUE TITLE
UILabel 实现YYLabel 的文字点击效果

### ISSUE THREAD

**Issue by DozEuto** [ibireme/YYKit#285]
项目需要用到 cell 的自适应高度，用 storyboard 创建的 UILabel 无法实现文字的点击效果，UILabel 的交互已打开，是我用的方法不对还是目前 storyboard 创建的 UILabel 无法实现这个效果？

**Comment by ibireme** [comment]
可以啊，检查下是否有其他 TapGesture 阻碍或者延迟了点击事件。

**Comment by DozEuto** [comment]
@ibireme 在YYText下面有人给解决了，设置一个属性就好了
