### ISSUE TITLE
YYControl的image用来做什么的.

### ISSUE THREAD

**Issue by zhishuixx** [ibireme/YYKit#287]
没看懂YYControl的Image属性，希望大神给讲解下。

**Comment by ibireme** [comment]
和 UIImageView 的 image 属性效果一样。

**Comment by zhishuixx** [comment]
我给image设置一张图片，但是没有显示。

**Comment by ibireme** [comment]
确保 image.CGImage 是一个有效值，设置后不要修改 layer.contents
