### ISSUE TITLE
提示‘bpg/libbpg.h’ file not found

### ISSUE THREAD

**Issue by xiongyoudou** [ibireme/YYKit#291]
谢谢您的开源！
我通过Pods拉取最新YYKit Demo后，发现报错，提示‘bpg/libbpg.h’ file not found
另外：我pods版本是1.0.1

**Comment by ibireme** [comment]
Demo 的话，直接把项目 Clone 下来就行，不用 CocoaPods。

**Comment by xiongyoudou** [comment]
OK,谢谢
