### ISSUE TITLE
NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds 

### ISSUE THREAD

**Issue by tianglin** [ibireme/YYKit#292]
最近项目中遇到这个bug，

-[YYTextView _updateAttributesHolder] 
-[YYTextView _updateOuterProperties]
-[YYTextView setSelectedTextRange:]

**Comment by ibireme** [comment]
能详细说下使用情况和崩溃调用栈吗？

**Comment by tianglin** [comment]
我调试的时候没有出现，这个bug是在友盟上看到的，好像没有调用栈，下图可以吗？

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYKit/commit/713a60955564851de98283862f546cebf2358ade

**Comment by tianglin** [comment]
thx
