### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by liuweiisme** [ibireme/YYKit#30]
我是将YYKit下载下来，将YYKit文件夹加入到项目中，编译后UIDevice+YYAdd.h出现错误

**Comment by caoway** [comment]
我遇到这种情况 是 不包含整个YYKit 而是用到那个 模块 包含哪个头文件就行。
可能YYKit 函数和你本身的工程文件 有冲突

**Comment by ibireme** [comment]
我猜可能是没有前缀的 Category 有冲突？希望能有更详细的错误描述。。

我在这个项目里并没有为 Category 加强前缀，所以确实会和其他一些库或是代码产生冲突，这个我在 readme 里也提到了。建议用那些单独提出来的子项目，比如 YYText、YYImage 等。

**Comment by acqiang** [comment]
我分开添加组件YYText\YYImage\YYCache等等，然后[!] The 'Pods' target has frameworks with conflicting names: WebP.。这个是什么问题呢，我直接添加整个YYKit就没问题

**Comment by ibireme** [comment]
这几个组件之间的包含大致如下：

    YYKit
        YYCategories
        YYModel
        YYWebImage
            YYCache
            YYImage
                WebP
        YYText

如果引入了一个库，那就没必要引入它包含的子工程了（比如引入了 YYWebImage 那就没必要引入 YYImage 了），不然就会有 conflict。

**Comment by zdrzdr** [comment]
能将这个组件像AFN分一下组吗？

**Comment by ibireme** [comment]
以后有空会试试用 subspec 来把 pod 分一下组。。不过，这里还是推荐用单独提出来的子项目～
