### ISSUE TITLE
YYLabel   highlightTapAction

### ISSUE THREAD

**Issue by bidm** [ibireme/YYKit#308]
仿微博@功能  使用highlightTapAction  昵称可以高亮  但是点击后不能马上变色  需要稍稍稍微时间长一点点  找不到原因

**Comment by WangBingQuan1992** [comment]
解决了吗 同样有这样的问题 放在tableview上 高亮会延迟

**Comment by maundytime** [comment]
同问：我放在tableview的headerview里不会有延迟，在cell里会有延迟，action并没有延迟

**Comment by wurenyijia** [comment]
同样的问题，原因是scrollview delayContentTouch 属性默认为YES，YYLabel点击时调用的顺序为 touchBegin->touchEnd->CALayer display,这样会把highlight属性移除掉，所以有这个bug，如果把delayContentTouch 设置成NO  YYLabel点击时调用的顺序为 touchBegin->CALayer display->touchEnd 就正常了 ，但是这个属性设置后，tableview上子view如果是button 会滚动不了，还需要添加 以下代码，当scrollview drag的时候如果子view是button，则cancelbutton的响应，暂时可以修复这个bug，希望ibireme 能够在YYLabel中兼容该问题
- (BOOL)touchesShouldCancelInContentView:(UIView *)view
{
    if ([view isKindOfClass:[UIButton class]])
    {
        return YES;
    }
    
    return [super touchesShouldCancelInContentView:view];
}
