### ISSUE TITLE
关于YYKit在版本升级中弃用的方法？

### ISSUE THREAD

**Issue by sunwell** [ibireme/YYKit#317]
在YYKit原来的版本中，`UIColor+YYAdd.h`文件中有一个`+ (UIColor *)colorWithHex:(unsigned int)hex;`方法，但是升级了YYKit之后，我发现最新版本中的这个方法不见了，应该是被作者弃用了吧。

在我原来的项目中，大量使用了这个便利方法，升级了之后用不了了，请问有什么好的方法来解决这个问题吗？如果有辅助的工具也行。

谢谢~

**Comment by sunwell** [comment]
不太了解作者为什么要弃用这种方法，但是自己手动修改了下最新版本的`UIColor+YYAdd.h`文件，添加了对应的方法。这可能是解决这个问题最简单的方法了~~
做个记录。

**Comment by liyuemin** [comment]
做UITableView 的自动设置行高的时候会有一个问题[TableView setRowHeight:UITableViewAutomaticDimension]; 后然后给YYlabel 添加约束，当文本很多的时候不会换行，但换成UILable 后就会自动换行，这个问题是什么导致的呢？

**Comment by sunwell** [comment]
@liyuemin 这种情况还没遇到过，不过你的两种情况下添加的约束是一样的吗？你可以检查下约束看看，另外这个问题，你应该`New Issue`提出来。
