### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by yy910217** [ibireme/YYKit#32]
我在项目中同时导入了 YYWebImage 、YYCache、YYImage。
一开是我在不知道YYWebImage是包含了其他2个库的
结果我在podfile文件同时引用了这个3个库。冲突了，文件重了！
那可以不可以 用 dependency 的方式去引用 YYCache、YYImage
s.dependency 'YYCache'
s.dependency 'YYImage'

**Comment by ibireme** [comment]
我只希望，开发者把 git 文件下载下来后，能直接跑起来，不用进行额外的操作，而且开发和调试会方便些。。

另外，readme 里也简单的说了一下依赖关系～
