### ISSUE TITLE
大神你还好吗？

### ISSUE THREAD

**Issue by li6185377** [ibireme/YYKit#325]
![image](https://cloud.githubusercontent.com/assets/1924211/20337232/c64480c6-ac0a-11e6-9b24-9e64db2b2598.png)

**Comment by qazwyw** [comment]
身体是革命的本钱，各位奋斗在一线的同仁们要多多注意身体啊！

**Comment by xuzhenmin** [comment]
保重身体

**Comment by liuweiisme** [comment]
可怕的办公室政治，望保重身体！

**Comment by weidu23** [comment]
持续围观

**Comment by ibireme** [comment]
谢谢楼上们的关心。。。
我得的病叫”腹内疝伴肠梗阻“，先天的问题导致的，做了两次手术，现在在家慢慢恢复中~
在滴滴的时候，我一直待在一个 team 内没动过，team 和 leader 也都很棒~ 看到有人瞎说赶紧再这里辟个谣。

另外，最近没时间回复各种 issues 很抱歉，稍后会处理的。

**Comment by ryanlikecode** [comment]
兄弟，保重身体

**Comment by li6185377** [comment]
赶紧关了

**Comment by fangdary** [comment]
吓尿~

**Comment by cxjwin** [comment]
啥情况

**Comment by lovelytomy** [comment]
曜源大神，身体是最重要的，好好照顾自己。

**Comment by cx2768279** [comment]
保重身体

**Comment by bing050802** [comment]
保重身体

**Comment by sunwell** [comment]
看到你还能回复，我们就放心了！
以讹传讹，很可怕啊！
保重身体！

**Comment by wonderffee** [comment]
我感觉主要黑滴滴的，大神也要保重身体

**Comment by ccoding2015** [comment]
保重身体

**Comment by itianyi** [comment]
大神 身体第一

**Comment by itianyi** [comment]
没事多做做大保健

**Comment by MichaelHuyp** [comment]
@ibireme 偶像我们永远支持你... 保重身体...

**Comment by zilaiyedaren** [comment]
人红是非多，哈哈，差点成了段子

**Comment by XLsn0w** [comment]
吃驚!

**Comment by slemon** [comment]
恭喜YY上娱乐头条

**Comment by atony2099** [comment]
666666

**Comment by yupliang** [comment]
呵呵

**Comment by AAChartModel** [comment]
iOS 开发界的传说终于熬成了网红了😝

**Comment by JobsKits** [comment]
大神还活着吗？
