### ISSUE TITLE
使用UIButton+YYWebImage做缓存时会出现白色图片情况

### ISSUE THREAD

**Issue by SOOBEI** [ibireme/YYKit#33]
[button setImageWithURL:[NSURL URLWithString:mediaLink] forState:UIControlStateNormal placeholder:[[WeTheme instance] emptyComicSquare] options:YYWebImageOptionProgressive |YYWebImageOptionSetImageWithFadeAnimation completion: nil];  使用这样的代码加载button的图片，缓存失败的话会被白色图片替代。

**Comment by SOOBEI** [comment]
[button setImageWithURL:[NSURL URLWithString:mediaLink] forState:UIControlStateNormal placeholder:[[WeTheme instance] emptyComicSquare] options:YYWebImageOptionAvoidSetImage completion:^(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error) {
                if (image && stage == YYWebImageStageFinished) {
                    [weakButton setImage:image forState:UIControlStateNormal];
                } else {
                    [weakButton setImage:[[WeTheme instance] emptyComicSquare] forState:UIControlStateNormal];
                }
            } ];
目前是在block里做判断，但我不知道是不是真的解决了这个问题

**Comment by ibireme** [comment]
如果没必要，可以试试把 YYWebImageOptionProgressive 这个参数去掉，
用这个参数时，它会随时尝试把未下载完的数据解码并显示出来。
