### ISSUE TITLE
想问一下，这些为什么都使用宏而不是常量

### ISSUE THREAD

**Issue by angelen10** [ibireme/YYKit#337]
![image](https://cloud.githubusercontent.com/assets/4332610/21178459/a2f36df4-c22a-11e6-8fcc-9afff36a6723.png)
在 /YYKit-master/Demo/YYKitDemo/Feed List/Weibo/Timeline/WBStatusLayout.h 文件里

**Comment by godL** [comment]
作者已经说了   这只是一个demo    怎么方便怎么来

**Comment by angelen10** [comment]
soga，谢谢
