### ISSUE TITLE
YYTextEditExample，改成大图片，拖动一会图片后CPU一直100%

### ISSUE THREAD

**Issue by yangshuibaishi** [ibireme/YYKit#34]
// YYTextEditExample 这个类的155 行
UIImage *image = [[YYImage alloc] initWithData:data scale:2];
UIImage *resizeImage = [image imageByResizeToSize:CGSizeMake(kScreenWidth, 200)];
UIImageView *imageView = [[YYAnimatedImageView alloc] initWithImage:resizeImage];

**Comment by ibireme** [comment]
代码一直停留在如下函数内：
<img width="694" alt="2015-12-08 1 51 21" src="https://cloud.githubusercontent.com/assets/839283/11648791/e0151496-9db2-11e5-8f85-ee16dd94f7c6.png">

可以看到是 CTFramesetterCreateFrame() 这个函数一直没有返回。我反复检查了前后的代码和传入参数都完全没问题，那么这应该是 CoreText 内部的 Bug：在 Text Frame 有不规则图形交叉时，排版出现了死循环。为了避免这个问题，布局时应该尽量避免 exclusionPaths 和 frame 边界产生交叉。
