### ISSUE TITLE
YYFPSLabel 

### ISSUE THREAD

**Issue by yupliang** [ibireme/YYKit#345]
Y神你好，用iPhone 6s模拟器运行你的Weibo demo的时候发现fps稳定在23，26附近，这个是什么原因呢？
![simulator screen shot 2017 1 16 4 27 29](https://cloud.githubusercontent.com/assets/5669715/21975642/b71832d6-dc08-11e6-926a-a82227c08239.png)

**Comment by faimin** [comment]
用真机就正常了
