### ISSUE TITLE
iOS7 系统下， 某些情况 CTFramesetterCreateWithAttributedString 方法不返回，一直处于卡死状态。

### ISSUE THREAD

**Issue by lpgonghan** [ibireme/YYKit#349]
#教头情报局#
糊 糊 糊 是真的糊，我自己都受不了自給🙈🙈用糊糊的慧子生日場集錦祝我們教主生日快樂～永遠開心思密達✌🏻️✌🏻️(大家感受感受氣氛，千萬不要點全屏)今天成都很冷～冷～冷～

这段文字，在 iOS7 系统下， 会卡死在 YYTextLayout 476 行
    ctSetter = CTFramesetterCreateWithAttributedString((CFTypeRef)text);
这段代码。 不做任何返回。
不知道是什么原因？

**Comment by mixiu7992** [comment]
我也遇到了 类似问题

**Comment by lpgonghan** [comment]
已解决!

UIFont *result = nil;
CTFontRef ctFont = CTFontCreateWithName((__bridge CFStringRef)font.fontName, font.pointSize, NULL);
result = (__bridge id)ctFont;
CFRelease(ctFont);

 用 result font。
