### ISSUE TITLE
这里有个BUG

### ISSUE THREAD

**Issue by l45** [ibireme/YYKit#357]
@interface LSImage : UIImage

@end
@implementation LSImage

+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        // NSObject+YYAdd.m 346行
        [self swizzleClassMethod:@selector(imageNamed:) with:@selector(ls_imageNamed:)];
    });
}

+ (UIImage *)ls_imageNamed:(NSString *)name {
    NSLog(@"%s", __func__);
    return [self ls_imageNamed:name];
}

@end

void doTest() {
    [UIImage imageNamed:@""];
    // +[UIImage ls_imageNamed:]: unrecognized selector sent to class 0x10721b0b0
}

**Comment by RITL** [comment]
@l45 这个是你写的问题吧，很明显ls_imageNamed是LSImage的类方法，超类UIImage并不具备这个方法，所以肯定会报错的呢
