### ISSUE TITLE
could not build module 'YYKit'

### ISSUE THREAD

**Issue by macoscoder** [ibireme/YYKit#36]
使用carthage编译生成的framework，拖到工程里，然后#import <YYKit/YYKit.h>
编译报错 could not build module 'YYKit'
error: unknown type name 'FOUNDATION_EXPORT'
FOUNDATION_EXPORT double YYKitVersionNumber;

请问怎么解决呀?

**Comment by macoscoder** [comment]
add this line at top of YYKit.h, it works fine.
```
#import <Foundation/Foundation.h>
```

<img width="409" alt="d8246d71-2cac-44b1-8928-76d2702df7f0" src="https://cloud.githubusercontent.com/assets/5967849/11678071/6482ae1a-9e7f-11e5-91c5-009209be1a57.png">

**Comment by ibireme** [comment]
Thanks!
Fixed.
