### ISSUE TITLE
高内存必崩 CTFramesetterCreateWithAttributedString

### ISSUE THREAD

**Issue by JxbSir** [ibireme/YYKit#372]
手机还没有达到内存警告的程序，比如占用2G才会收到警告，但是在1.7G的时候，就挂了
xxxxxx(3529,0x16e803000) malloc: *** error for object 0x177700280: Freeing unallocated pointer
*** set a breakpoint in malloc_error_break to debug

不是所有手机都这样，小内存手机还没挂，在占用1G左右的时候就收到警告了，这个是在iPhone7 Plus上面必现

如图
[http://7xi9xs.com1.z0.glb.clouddn.com/WX20170406-105946@2x.png](url)

**Comment by youlianchun** [comment]
我这边也是这个问题，最严重的事使用对象释放了内存下不来，闪退了

**Comment by emsihyo** [comment]
什么app这么可怕。会占用这么多内存。

**Comment by JxbSir** [comment]
没人解决就关了吧，哈哈哈

**Comment by sylarhcn** [comment]
自己搞定提个pull request还不是美滋滋

**Comment by StanTheEvil** [comment]
图片呢

**Comment by mrhyh** [comment]
这个问题解决了吗？
