### ISSUE TITLE
关于lldb调试

### ISSUE THREAD

**Issue by yangchao0033** [ibireme/YYKit#38]
请问在断点调试时提示编译被优化，那断点调试或者lldb是否不可用？

**Comment by ibireme** [comment]
调试时需要把编译优化关掉 (Optimization Level 设置为 -O0) ，
否则调试代码和编辑器中的代码会匹配不上导致各种问题。

**Comment by yangchao0033** [comment]
找到原因了 是因为项目scheme默认是release 而你设置的Optimization level release模式是优化过的
只要在scheme中改为debug模式就行~
