### ISSUE TITLE
YYTextView添加分类后， 再次进入引入YYTextView的控制器时会崩溃

### ISSUE THREAD

**Issue by sharlley** [ibireme/YYKit#381]
YYTextView增加了一个限制文本长度的分类，开始正常，退出该控制器，再次进入就会崩溃，崩溃代码：
static void _addDebugTarget(id<YYTextDebugTarget> target) {
    _initSharedDebug();
    pthread_mutex_lock(&_sharedDebugLock);
    CFSetAddValue(_sharedDebugTargets, (__bridge const void *)(target)); //这行会崩溃
    pthread_mutex_unlock(&_sharedDebugLock);
}

**Comment by zhenshub** [comment]
是不是在分类中重写了dealloc方法，YYTextView的dealloc方法有在TextView销毁后，从_sharedDebugTargets移除自己的逻辑，重写方法后CFSet add Value时，对比了旧的TextView（已被销毁），故造成了崩溃

解决：
hook dealloc方法
