### ISSUE TITLE
这么多问题，作者为什么不修复呢？YYImage读取不到Assets的图片。yy_setImageWithURL这个方法在cell滑动时明显卡顿，更换成sd_set..后可以对比出来

### ISSUE THREAD

**Issue by Rain-dew** [ibireme/YYKit#393]
`[self.iconImageView yy_setImageWithURL:[NSURL URLWithString:model.fristimg] placeholder:[YYImage imageNamed:@"place"] options: YYWebImageOptionSetImageWithFadeAnimation completion:^(UIImage * _Nullable image, NSURL * _Nonnull url, YYWebImageFromType from, YYWebImageStage stage, NSError * _Nullable error) {
    }];
`
代码如上！。使用时cell滑动会出现卡顿。。

**Comment by jkpang** [comment]
大兄弟,你这么说就不对了,YY大神给iOS界开源的这么好用的工具,分文未取,我们应该要感到庆幸才是.大神也是人,也有忙不过来的时候, 如果你觉得写得有问题,你可以fork代码后自行修改提PR, 这样不仅是对自己能力的提高也是对开源界的贡献. 希望你能理解开源作者的痛与泪,不要一味的索取......望珍重! @Rain-dew

**Comment by Rain-dew** [comment]
这位兄弟，请你仔细看我的问题，我仅仅问了一句为什么不修复。这么正常的疑问句，怎么就涉及到一味的索取了，怎么就涉及到痛与泪了！！！正是对YY的喜爱，才有对她更好的期待，我希望好的东西越来越好，更加完美。我想这也是所有关注YY开发者的期待，请问你，有何不妥？




Sent from Mail Master
在2017年07月07日 18:15，jkpang 写道：

大兄弟,你这么说就不对了,YY大神给iOS界开源的这么好用的工具,分文未取,我们应该要感到庆幸才是.大神也是人,也有忙不过来的时候, 如果你觉得写得有问题,你可以fork代码后自行修改提PR, 这样不仅是对自己能力的提高也是对开源界的贡献. 希望你能理解开源作者的痛与泪,不要一味的索取......望珍重! @Rain-dew

**Comment by amisare** [comment]
遇到问题fork代码，修改bug，提交，作者看到了修改，合理的话会合并。仅仅提出问题，缺少线索，作者也没办法解决。何况解决bug也要分析烧脑

**Comment by hssdx** [comment]
我这一点都不卡顿，能定位一下卡顿的代码是哪一行吗

**Comment by TigerBeanst** [comment]
“作者为什么不修复”
这种说法难道不是一种伸手吗？

**Comment by Rain-dew** [comment]
你无须站在这样的道德高度来说教，我请楼上来喷的来看看我有没有说一句不好听的话，一个疑问句，你就来喷，我想你也就是这样无聊的人了。还有以后来发言的人，我觉得你们应该想清楚，你们是不是也有让好的框架持续更新下去的心愿。这是一个自由言论的地方，但是1.我正常问问题2.我没有在问题里骂人，说不好听的话3.我并不觉得我这样问有什么不好，但在我看来你来这里鸡蛋挑骨头的说教本身就是一个低素质的表现！

**Comment by liberalisman** [comment]
因为作者生病了

**Comment by Rain-dew** [comment]
@liberalisman 希望他早日康复啊！
