### ISSUE TITLE
pod update 后 pod install，YYKit 还显示 1.0.9 版本

### ISSUE THREAD

**Issue by hssdx** [ibireme/YYKit#399]
各位大神好，是不是新 change 还没更新到 pod 上？我这编译还是有30+个 warning

Podfile 是用的 pod 'YYKit'

版本显示
Using YYKit (1.0.9)

**Comment by jkpang** [comment]
那是你没有更新本地的pod缓存,解决办法:
1. 终端执行 pod setup
2.终端执行 pod install
@hssdx

**Comment by faimin** [comment]
作者应该是还没更新`pod`，你可以换用`git`的方式引用`pod`，这样应该能获取到最新的`YYKit`。
`pod 'YYKit', :git => 'https://github.com/ibireme/YYKit.git'`

**Comment by jkpang** [comment]
**1. 作者只是更新了主线的代码,并没有发布新版本,当然没更新了**
![image](https://user-images.githubusercontent.com/17583451/29012126-b582c8f2-7b6b-11e7-9d4e-da0cfbbdbb4b.png)

**2. 另外pod导入的库去除编译警告可以在Podfile文件添加** 
inhibit_all_warnings! ,如图:
![image](https://user-images.githubusercontent.com/17583451/29012117-a3c4523e-7b6b-11e7-8b03-1f4de46ef122.png)
@hssdx

**Comment by hssdx** [comment]
@faimin  @jkpang  
谢谢大神回复，我先用git的方式引用pod

**Comment by realCJ** [comment]
@hssdx  git的方式引用pod  怎么引用啊？pod 'YYKit', :git => 'https://github.com/ibireme/YYKit.git' 这样吗？我的还是1.0.9 啊

**Comment by hssdx** [comment]
@LiberalChen  pod 'YYKit', :git => 'https://github.com/ibireme/YYKit.git' 即可，一定是可以的，你试下 pod update
