### ISSUE TITLE
在swift项目中使用

### ISSUE THREAD

**Issue by zhouzizi** [ibireme/YYKit#4]
在swift项目中。按照 『手动安装』 中的步骤把YYKit加入项目中，并且在oc桥接文件中 ``` import "YYKit.h"  ```  ，但是在项目中还是不能调用YYKit，请问，在swift项目中还需要做什么步骤吗~

**Comment by zhouzizi** [comment]
我是想使用 YYWebImage  。
``` let image = UIImageView()
image. yy_imageURL...
```
无法调用yy_imageURL。。。

**Comment by zhouzizi** [comment]
额。请问。是把前缀yy去掉了吗。。

**Comment by ibireme** [comment]
嗯对～
YYKit 这个大包包里，所有的 Category 都没有前缀，这个在 Readme 里有提到原因。

**Comment by zhouzizi** [comment]
不好意思。。
