### ISSUE TITLE
使用YYkeychain 取值的时候 崩溃

### ISSUE THREAD

**Issue by HWDW** [ibireme/YYKit#40]
NSString *macCode=[YYKeychain getPasswordForService:@"123" account:@"YXmacCode" error:nil];
	if (macCode==nil) {
		macCode=[NSString stringWithUUID];
		[YYKeychain setPassword:macCode forService:@"123" account:@"YXmacCode" error:nil];
	}

在第一次运行的时候取空值是不报错的，再次运行取值就崩溃了

**Comment by ibireme** [comment]
对于访问 keychain，推荐还是用 SSKeychain。
YYKeyChain 这个类还为经过更多测试，稍后我会添加一些单元测试。
