### ISSUE TITLE
NSTImeer+YYAdd有个问题

### ISSUE THREAD

**Issue by chquanquan** [ibireme/YYKit#401]
接手一个项目.里面一启动就crash,查看report定位到这里.
能帮忙看一下吗?就是我觉得不是YYKit的问题,但是能不能给点建议,是不是哪用用得不对了...因为这个bug害惨我的.不会修....
<img width="1335" alt="2017-08-15 11 45 00" src="https://user-images.githubusercontent.com/14248860/29301503-36ca7ef2-81af-11e7-999c-f6877fb6d4f3.png">

**Comment by hssdx** [comment]
贴一下相关代码和 console 的崩溃栈信息

**Comment by chquanquan** [comment]
这就难搞了,很多地方都调用了这个代码.然后,没有console(我是通过xcode的Organizeer--->crashes定位到这句代码的)...我重现不了bug....如果信息太小,无法解决...那我就closed issue了...因为我也是因为信息太少了,所以找不到问题..我功力还是不够啊....

**Comment by hssdx** [comment]
我觉得可能是  scheduledTimerWithTimeInterval:block:repeats: 方法里的 block 参数传空了吧？

**Comment by ishepherdMiner** [comment]
根据 ``NSTimer+YYAdd.m``

```objc
+ (NSTimer *)scheduledTimerWithTimeInterval:(NSTimeInterval)seconds block:(void (^)(NSTimer *timer))block repeats:(BOOL)repeats {
    return [NSTimer scheduledTimerWithTimeInterval:seconds target:self selector:@selector(_yy_ExecBlock:) userInfo:[block copy] repeats:repeats];
}

+ (NSTimer *)timerWithTimeInterval:(NSTimeInterval)seconds block:(void (^)(NSTimer *timer))block repeats:(BOOL)repeats {
    return [NSTimer timerWithTimeInterval:seconds target:self selector:@selector(_yy_ExecBlock:) userInfo:[block copy] repeats:repeats];
}
```

``_yy_ExecBlock:`` 被这两个方法触发,``timer`` 的 ``userInfo`` 参数有值的情况下应该是 ``void (^)(NSTimer *timer)`` 类型的，要不试着全局搜下 哪调用了这两个方法
