### ISSUE TITLE
模型转json对象的过程

### ISSUE THREAD

**Issue by yangchao0033** [ibireme/YYKit#42]
ModelToJSONObjectRecursive中当模型为不合法的字典或者数组时，会对他使用可变的字典或数组进行重新构建，但是在返回结果中没用对其进行copy，这样是否会过分解耦数据，让使用者直接操作修改内部存放的容器？还是为了性能考虑没有进行copy？

**Comment by ibireme** [comment]
不知道你说的"过分解耦"是什么意思。

在运行时，开发者是无法判断一个容器类实例是否是可变的，举个例子：

    NSString *str = @"[1,2,3]";
    NSData *data = [str dataUsingEncoding:NSUTF8StringEncoding];
    NSArray *array = [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:NULL];
    if ([array isKindOfClass:[NSMutableArray class]]) {
        [((NSMutableArray *)array) addObject:@4]; // crash
    }

    *** Terminating app due to uncaught exception 
    'NSInternalInconsistencyException', reason: '-[__NSCFArray insertObject:atIndex:]: 
    mutating method sent to immutable object'

对于一个不可变容器属性，例如 `@property NSArray *users` 来说，给它赋值一个可变容器是没有问题的，但如果开发者直接获取它，然后判断它的类型，并尝试直接强制类型转换来改变其内部逻辑，那这个行为本身就是错误的。

**Comment by yangchao0033** [comment]
你可能误解我的意思了 我的意思是在你准备将内部的可变字典作为`jsonObject`返回的时候，是否应该copy一次，使它不会被外部接口随意修改，我觉得既然吧这个数据类型定义为一个对象的话，他的思想和面向对象封装应该是一致的。--参考《Effective objective-c 2.0》第十八条：尽量使用不可变对象。

**Comment by ibireme** [comment]
首先，在使用时，可变容器和不可变容器的性能差距几乎是一样的。Copy 成不可变对象并不能获得什么好处。
其次，在对外暴露的接口中，并没有出现可变容器。对于调用者来说他使用的是不可变对象。

**Comment by yangchao0033** [comment]
奥 那就没啥问题了 就怕他在外面强制类型转换，然后手动修改😄
