### ISSUE TITLE
裁剪圆角图片缓存后图片大小（非CGSize）变大的问题

### ISSUE THREAD

**Issue by TigerWf** [ibireme/YYKit#45]
你好，请问下 在Feed List Demo中Weibo中 缓存后的圆角头像的大小 比对应url的方形的头像图片的大小要大好几倍，这是UIImageJPEGRepresentation  UIImagePNGRepresentation转data后缓存的原因吗？发现SDWebImage中也有这个问题 ，还是我用错呢？ 望大牛指导下 3Q

**Comment by ibireme** [comment]
你说的"大小"是指什么？
file 的 bytes 大小、image.size 大小还是 image.CGImage.size 大小？

**Comment by TigerWf** [comment]
file的bytes大小

**Comment by ibireme** [comment]
头像原文件格式是 JPEG 的，它通常是在服务端压缩的，压缩比例会比较高。
客户端下载下来后，绘制成圆角时，图片会被加上 Alpha 通道，并且只能用 PNG 保存，这样文件体积很可能会膨胀很多。

**Comment by TigerWf** [comment]
我看新浪微博 的cache文件夹里好像没有缓存圆角图片（都是方形的。）。。难道他们是在上面又贴了一层镂空的view....

**Comment by ibireme** [comment]
没注意。。贴镂空图片也没问题。

我那个，主要是演示加WebImage加圆角的功能

**Comment by TigerWf** [comment]
嗯嗯  了解了  3q
