### ISSUE TITLE
YYWebImage 内存泄露 闪退

### ISSUE THREAD

**Issue by fuhailong** [ibireme/YYKit#482]
YYKit 1.0.9
我有一个无限刷的列表  有图片和基它UI ，在快速拉列表时，内存增长的非常快，然后被系统kill掉，通过leak查下了  有很大一部份的内存泄露都指向了YYKit， 如下图，我试过把所有的缓存都做到disk里，也试过cache.memoryCache.costLimit限制大小，但都没有效果，能否帮忙查看下这个内存泄露的问题么，这个还挺严重的，
<img width="1284" alt="wx20180620-120052 2x" src="https://user-images.githubusercontent.com/4598463/41636636-3a56caf0-7482-11e8-80ba-0b8e10292634.png">

**Comment by hssdx** [comment]
贴一下关键代码，cell for row at index path

**Comment by fuhailong** [comment]
我用的是Texture，我试过不加载图片，没有图片decode的过程，就不会有这么大的内存泄露，
<img width="660" alt="1" src="https://user-images.githubusercontent.com/4598463/41643151-0c804b7c-749d-11e8-970d-edeacf84b81c.png">
<img width="752" alt="2" src="https://user-images.githubusercontent.com/4598463/41643152-0ce231b6-749d-11e8-9e99-09bc4ccea6de.png">
<img width="1078" alt="3" src="https://user-images.githubusercontent.com/4598463/41643154-0d776aa6-749d-11e8-80c9-10c73e9a581e.png">

**Comment by hssdx** [comment]
因为我也没有用过Texture，所以不是很确定，是快速拉会内存暴涨，慢拉就不会吗？试试这样 @autoreleasepool{【YYImage相关代码...】}，图片的 decode 会往 autoreleasepool 注册对象

**Comment by fuhailong** [comment]
我试过添加
@autoreleasepool，内存还是一直在增长，不知道是不是Texture的block创建imageView导致的。
我之前也是过单拉出一个只有图或只有其它UI的demo也没有被系统kill掉过，只要YYImage+Texture就会这样。 感谢您的回答！

**Comment by muken88** [comment]
> 我试过添加 @autoreleasepool，内存还是一直在增长，不知道是不是Texture的block创建imageView导致的。 我之前也是过单拉出一个只有图或只有其它UI的demo也没有被系统kill掉过，只要YYImage+Texture就会这样。 感谢您的回答！

你自己代码写的有问题

**Comment by tom2025888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
谢谢，你的邮件我已经收到！

**Comment by Svyanto** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
