### ISSUE TITLE
显示全文/收起 功能, 在切换layout之后文字会闪烁

### ISSUE THREAD

**Issue by SabinLee** [ibireme/YYKit#487]
tableView-cell上面的yylabel的文字可能很长,平时显示最多3行. 
超出3行时我会生成两个YYTextLayout, 一个用于显示全文一个用于收起, 同时cell会出现个显示全文的按钮, 在点击按钮后我刷新当前cell, 切换为显示全文的layout,但是yylabel设置后会整个label闪一下. 类似于整个label被重绘了, 有解决方法或者更好的方法做这种需求吗?

**Comment by lsj980Ya** [comment]
我这边也有，但不是很明显

**Comment by SabinLee** [comment]
已解决, 解决方法是不要用异步渲染, yylabel.displayAsync属性设置为NO,即在主线程刷新UI,之前是异步刷新, 肯定会闪一下的
