### ISSUE TITLE
建议框架里面的分类方法加个 yy 什么的前缀

### ISSUE THREAD

**Issue by AbooJan** [ibireme/YYKit#49]
目前之前SDWebImage 框架的分类方法也是像你目前这样，现在最新版本已经加入了前缀，避免跟系统或其他框架有冲突，有前缀兼容性更好。

例如：
- (void)setImageWithURL:(NSURL *)imageURL placeholder:(UIImage *)placeholder;

改成：
- (void)yy_setImageWithURL:(NSURL *)imageURL placeholder:(UIImage *)placeholder;

**Comment by ibireme** [comment]
readme 结尾处有说明原因。
推荐用那些拆分出来的子项目，那些项目里面都有前缀的。
