### ISSUE TITLE
README中文介绍

### ISSUE THREAD

**Issue by AnYuan** [ibireme/YYKit#5]
* [YYCategories](https://github.com/ibireme/YYCategories) — iOS 异步绘制与显示的工具。
* [YYCategories](https://github.com/ibireme/YYCategories) — 功能丰富的 Category 类型工具库。

应为：
* [YYAsyncLayer](https://github.com/ibireme/YYAsyncLayer) — iOS 异步绘制与显示的工具。
* [YYCategories](https://github.com/ibireme/YYCategories) — 功能丰富的 Category 类型工具库。

**Comment by ibireme** [comment]
感谢提出～我改一下
