### ISSUE TITLE
YYThreadSafeDictionary死锁问题

### ISSUE THREAD

**Issue by yayiyao** [ibireme/YYKit#502]
在同一个线程中，YYThreadSafeDictionary如果调用遍历方法enumerateKeysAndObjectsUsingBlock:的同时又调用读/写方法（例setObject:forKey:）就会出现死锁问题，因为遍历和读/写操作都会调用dispatch_semaphore_wait方法。

我理解YYThreadSafeDictionary只是为了保证多线程安全，那在同一个线程中操作是否可以避免这种死锁问题？

**Comment by hssdx** [comment]
你这用法就不太安全，即使确保可重入，字典在遍历的同时 进行修改数据，也会发生崩溃或者数据错乱

**Comment by holybin** [comment]
> 

在enumerateKeysAndObjectsUsingBlock中调用count 一样死锁

**Comment by holybin** [comment]
> 你这用法就不太安全，即使确保可重入，字典在遍历的同时 进行修改数据，也会发生崩溃或者数据错乱

在enumerateKeysAndObjectsUsingBlock中调用count 一样死锁

**Comment by tom2025888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
谢谢，你的邮件我已经收到！

**Comment by Svyanto** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
