### ISSUE TITLE
YYModel自动转换功能

### ISSUE THREAD

**Issue by kaqise** [ibireme/YYKit#505]
我用的是modelWithJSON自动转模型，想了解一下可不可以直接把JSON中 latitude 和longitude两个字段直接转成坐标点CLLocationCoordinate2D，虚心求教

**Comment by hssdx** [comment]
可以 啊，要加一个静态方法
例如json:
{
  "coord":{"latitude": 123,"longitude":456},
   XXX
}

在你的model里加上静态方法：
+ (nullable NSDictionary<NSString *, id> *)modelContainerPropertyGenericClass {
    return @{@"coord" : CLLocationCoordinate2D.class};
}

如果你的json属性名和 CLLocationCoordinate2D 名称不一致，还要给 CLLocationCoordinate2D 加一个Category ，然后加上对应的mapping方法就可以了

**Comment by kaqise** [comment]
谢谢大神
