### ISSUE TITLE
图片切圆角

### ISSUE THREAD

**Issue by BestKai** [ibireme/YYKit#51]
imageByRoundCornerRadius  UIImage+YYadd里的这个方法，不能把非等宽登高的图片切成圆的，有没有什么方法可以切成圆的？

**Comment by ibireme** [comment]
先用 [image imageByResizeToSize:CGSizeMake(50, 50) contentMode:UIViewContentModeScaleAspectFill]; 裁成方形，再加圆角。

为了效率考虑，也可以手动画一下：

    CGFloat minSize = MIN(image.size.width, image.size.height);
    CGRect rect = CGRectMake(0, 0, minSize, minSize);
    UIImage *roundImage = [UIImage imageWithSize:rect.size drawBlock:^(CGContextRef context) {
        [[UIBezierPath bezierPathWithOvalInRect:rect] addClip];
        [image drawInRect:rect withContentMode:UIViewContentModeScaleAspectFill clipsToBounds:NO];
    }];
