### ISSUE TITLE
为什么不使用注释的代码呢？

### ISSUE THREAD

**Issue by 778477** [ibireme/YYKit#515]
https://github.com/ibireme/YYKit/blob/4e1bd1cfcdb3331244b219cbd37cc9b1ccb62b7a/YYKit/Base/UIKit/UIView%2BYYAdd.m#L66

**Comment by citynight** [comment]
删除要倒序




| |
lixzzzzzz
|
|
邮箱：lixzzzzzz@126.com
|
在2018年12月24日 18:54，778477 写道：

https://github.com/ibireme/YYKit/blob/4e1bd1cfcdb3331244b219cbd37cc9b1ccb62b7a/YYKit/Base/UIKit/UIView%2BYYAdd.m#L66

**Comment by 778477** [comment]
你可以证明一下注释的代码是错误的实现吗？
