### ISSUE TITLE
提个建议,webP动态图

### ISSUE THREAD

**Issue by suyuexin** [ibireme/YYKit#52]
在使用webP动态图的时候,可不可以把
uint32_t webpLoopCount =  WebPDemuxGetI(demuxer, WEBP_FF_LOOP_COUNT);
播放的次数作为一个接口开放出来,可以任意修改,而不是默认读取webP动图本身的循环次数,这样在很大程度上会方便很多.

**Comment by ibireme** [comment]
可以参考下这个问题：
https://github.com/ibireme/YYImage/issues/1

**Comment by ibireme** [comment]
后续讨论可以见上面这个链接。
