### ISSUE TITLE
关于动态图循环的疑问

### ISSUE THREAD

**Issue by suyuexin** [ibireme/YYKit#55]
如果动态图本身是无限循环的,播放(startAnimating)和停止(stopAnimating)是没有问题;
如果动态图本身就是循环有限次(3次),当循环停止后,再使用播放(startAnimating)没有作用;
怎样才能再次启动动态图的播放?
当然YYImage是非常好用的,假如你知道关于这方面的问题,请指教.谢谢!

**Comment by ibireme** [comment]
后续讨论挪到这里：https://github.com/ibireme/YYImage/issues/3
