### ISSUE TITLE
非技术性建议

### ISSUE THREAD

**Issue by Forfre** [ibireme/YYKit#56]
阅读起来，前一种直观。写起来，后一种省事。
- (NSString *)md5String {
    unsigned char result[CC_MD5_DIGEST_LENGTH];
    CC_MD5(self.bytes, (CC_LONG)self.length, result);
    return [NSString stringWithFormat:
            @"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
            result[0], result[1], result[2], result[3],
            result[4], result[5], result[6], result[7],
            result[8], result[9], result[10], result[11],
            result[12], result[13], result[14], result[15]
            ];
}

//- (NSString *)md5String
//{
//    unsigned char result[CC_MD5_DIGEST_LENGTH];
//    CC_MD5(self.bytes, (CC_LONG)self.length, result);
//    NSMutableString *hash = [NSMutableString string];
//    for (int i = 0; i < CC_MD5_DIGEST_LENGTH; i++) {
//        [hash appendFormat:@"%02x", result[i]];
//    }
//    return hash;
//}

**Comment by ibireme** [comment]
啊哈。。这个是出于性能考虑，所以才写得罗嗦了些。。（虽然这性能差距不明显）
