### ISSUE TITLE
宏定义求解答~~~

### ISSUE THREAD

**Issue by yangchao0033** [ibireme/YYKit#57]
你好，这个宏有点疑问~
```objc
@weakify(nav);
#define weakify(object) autoreleasepool{} __weak __typeof__(object) weak##_##object = object;
```
1、前面的@有什么用啊？
2、还有宏中的debug时autoreleasepool{}和后面release时的try catch有什么区别？

**Comment by yangchao0033** [comment]
不是只有那种重大的错误才会用异常处理，
而且处理方式一般都是直接让程序退出吗？

**Comment by ibireme** [comment]
这个写法是参考了 ReactiveCocoa(libextobjc) 的红定义。其中 At 符号是为了模仿 @inferface 等系统关键词写法，显得比较起眼。try/cache/autorelease 这些东西，都是为了避免编译警告、并保证编译后代码优化不会对性能产生影响。

**Comment by yangchao0033** [comment]
搜噶，多谢多谢😄~

**Comment by SamingZhong** [comment]
“这个写法是参考了 ReactiveCocoa(libextobjc) 的红定义。其中 At 符号是为了模仿 @inferface 等系统关键词写法，显得比较起眼。”
觉得这句话有点欠妥，@其实应该是直接拼接进宏里边，形如@weakify(self) 编译阶段等同于：
@autoreleasepool{} __weak __typeof__(self) weak_self = self;


发自我的 iPhone

**Comment by xx-li** [comment]
weak##_##object 中的 "##_##" 是起什么作用?

**Comment by xiaodeng2014** [comment]
@xx-li  ##_##， 起到拼接的作用，如果object传入self， 那么使用的时候变量就会变成weak_self
