### ISSUE TITLE
iOS 14 xcode12出现问题

### ISSUE THREAD

**Issue by JianWenXie** [ibireme/YYKit#576]
ld: in /Users/pengliping/Desktop/PAPP/VKIntlProperty/Pods/YYKit/Vendor/WebP.framework/WebP(libwebpencode_la-config.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by leeraymond78** [comment]
Me too, only able to build with Debug mode

**Comment by bigbigpro** [comment]
Excluded Architectures 加上的 arm64

**Comment by Mars1989sh** [comment]
> Excluded Architectures 加上的 arm64

试了也没用 还是报错

Pods/YYImage/Vendor/WebP.framework/WebP(libwebpencode_la-config.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by iT-Boyer** [comment]
M1内核在编译时，遇到同样问题，有什么解决办法？

**Comment by Mars1989sh** [comment]
project 自己的项目中的 build setting 加上
project pods 中的 build setting 加上

"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64

我是这么解决模拟器上报building for iOS Simulator, but linking in object file built for iOS, for architecture arm64的问题

**Comment by benben2019** [comment]
> project 自己的项目中的 build setting 加上
> project pods 中的 build setting 加上
> 
> "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64
> 
> 我是这么解决模拟器上报building for iOS Simulator, but linking in object file built for iOS, for architecture arm64的问题

请问能说下具体是怎么解决的吗？

**Comment by GFDreamer** [comment]
Podfille add 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
  
end

**Comment by 1905796135** [comment]
在Podfile 文件最后添加下面这些
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    config.build_settings['VALID_ARCHS'] = 'arm64 arm64e armv7 armv7s x86_64 i386'
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
    
end

**Comment by SimleLong** [comment]
setting "Build Active Architecture Only" to No for all schemes. 

这个方案有效

**Comment by fanyu** [comment]
这个有问题怎么处理呢，尝试了这个方法，是无效的。

> project 自己的项目中的 build setting 加上
> project pods 中的 build setting 加上
> 
> "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64
> 
> 我是这么解决模拟器上报building for iOS Simulator, but linking in object file built for iOS, for architecture arm64的问题

**Comment by jsonehero** [comment]
进入Edit Scheme，选择Run->info，将Build Configuration设置为debug

**Comment by Jacky-LinPeng** [comment]
> project 自己的项目中的 build setting 加上 project pods 中的 build setting 加上
> 
> "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64
> 
> 我是这么解决模拟器上报building for iOS Simulator, but linking in object file built for iOS, for architecture arm64的问题

run跑Release 运行还是报错....
