### ISSUE TITLE
图片显示

### ISSUE THREAD

**Issue by redye** [ibireme/YYKit#59]
在播放 PNG 图片的时候，在模拟器上能完整的显示出来，但在真机上的时候图片只停留在第一帧，请问是什么原因呢 ？模拟器和真机系统都是 9.2。就是下面这幅图
<img width="352" alt="image" src="https://cloud.githubusercontent.com/assets/7239131/11974151/7dc43466-a99c-11e5-8d22-385287068098.png">

**Comment by ibireme** [comment]
GIF 和 WebP 动画都有吧？
检查下项目的 Compress PNG Files 选项，设置为 NO。

**Comment by redye** [comment]
可以了，多谢，小白的道路依旧任重而道远 %>_<%
