### ISSUE TITLE
emoj 表情不显示

### ISSUE THREAD

**Issue by BestKai** [ibireme/YYKit#60]
if (!_chatContentLabel) {
                
                _chatContentLabel = [YYLabel new];
                
                _chatContentLabel.frame = CGRectMake(70, 36, kScreenWidth-85, 22);
                
                _chatContentLabel.displaysAsynchronously = YES;
                
                _chatContentLabel.ignoreCommonProperties = YES;
                
                _chatContentLabel.textVerticalAlignment = YYTextVerticalAlignmentCenter;

                _chatContentLabel.backgroundColor = [UIColor redColor];
                
                [self.contentView addSubview:_chatContentLabel];
            }
            
            _chatContentLabel.hidden = NO;
            
            NSMutableAttributedString *text = [self attributeTextWith:_hisfieds.content];
            
            YYTextContainer *container = [YYTextContainer new];
            
            container.size = CGSizeMake(CGRectGetWidth(_chatContentLabel.frame), 22);
            
            container.maximumNumberOfRows = 1;

            YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];

            
            _chatContentLabel.textLayout = layout;

我这样写的，emoji表情不显示，哪里写的不对吗？？

**Comment by ibireme** [comment]
检查下 label 的大小，或者开启调试看看。

**Comment by BestKai** [comment]
![d48171f4-fc5e-4934-b463-67dd39e99b5e](https://cloud.githubusercontent.com/assets/8436462/12005315/f73363a0-abd9-11e5-8b69-8c7e328a100a.png)
![fcbbe019-fbd7-4c0a-90d8-874329b4af6a](https://cloud.githubusercontent.com/assets/8436462/12005316/f73ce45c-abd9-11e5-823e-16c535591e67.png)
这是截图，打印的也有，就是不显示，label的大小也对。很奇怪。

**Comment by ibireme** [comment]
我觉得，这像是文本高度设小了。
Emoji 的高度要大于字号很多的。

**Comment by BestKai** [comment]
我把YYLabel换成YYTextView就显示了。奇怪的是另外一个地方可以显示，只有这个地方不显示。

**Comment by SamingZhong** [comment]
可以试试把label高度设置到40检查下是否高度不足以让emoj显示，逐步排查。

**Comment by BestKai** [comment]
好了，果然是高度的问题。非常感谢

**Comment by bycc070809** [comment]
yylabel 不能居中是什么问题

**Comment by BestKai** [comment]
不会啊，我的是居中的，有个textVerticalAlignment 这样的属性，设为center
