### ISSUE TITLE
苹果新政策，添加隐私清单PrivacyManifest，有人fork解决吗？

### ISSUE THREAD

**Issue by FanningHau** [ibireme/YYKit#610]
看到几处地方用到了苹果明确标注的API，需要在清单里列出来，像systemUptime()、systemFreeSize()、systemSize()等

**Comment by weixianlove** [comment]
使用 #612 或者：pod 'YYKit', :git => 'https://github.com/weixianlove/YYKit.git'

**Comment by weixianlove** [comment]
pod 'YYKit', :git => 'https://github.com/weixianlove/YYKit.git', :branch => 'privacy_manifest'
