### ISSUE TITLE
为什么计算UILable的像素高度不使用font.lineHeight 属性？

### ISSUE THREAD

**Issue by slemon** [ibireme/YYKit#63]
为什么计算lable的像素高度不使用font.lineHeight 属性？是考虑性能的问题吗？还是其他

**Comment by ibireme** [comment]
因为不能这么算啊。。

举个例子：一段包含中英文、Emoji 的文字，设置字体为 Helvetica 12，但绘制时，中文会用 PingFang SC 来显示、Emoji 会用 AppleColorEmoji 来显示，这些字体的 ascent/descent/lineHeight 都是不一样的。

**Comment by slemon** [comment]
也就是当全是统一的文字的时候，是可以使用lineHeight来算lable的高度？

**Comment by ibireme** [comment]
文字排版在底层的实现很复杂，文字显示高度取决于很多因素，比如文字、字体、段落属性、基线调整等等。即使文本全部都是中文（包括标点符号），或者全是英文，用 lineHeight 来计算也容易出现各种个样的问题。

**Comment by shiablue** [comment]
大神。文字里头有emoji的时候算出来的高度比纯文字高度要高一些。这个有什么方法让他们一样吗？
