### ISSUE TITLE
问一个题外话

### ISSUE THREAD

**Issue by wangbiye** [ibireme/YYKit#65]
我看到Demo里边的布局是用Frame, 现在实际开发中你还会用frame吗, Autolayout呢?

**Comment by XuYanci** [comment]
现在一般都是用autolayout吧。这也是趋势。

**Comment by ibireme** [comment]
简单页面可能用 AutoLayout，太复杂页面还是用 frame 相关的东西。（我个人更习惯用 frame。。。蛤蛤）

**Comment by wangbiye** [comment]
谢谢, 我最近在纠结要不要使用Frame, 我们现在有一个类似于朋友圈的页面(更复杂, 花样更多), 用Autolayout之后滑动有点卡, 希望Frame能解决

**Comment by ldasein** [comment]
对性能要求高的界面肯定要用frame，然后还需要缓存或者预加载布局的计算结果，不然肯定卡的。

**Comment by XuYanci** [comment]
http://www.tuicool.com/articles/2ENFBni 你看看这边文章。你就主要考虑CPU和GPU的消耗。然后逐步去优化。

**Comment by XuYanci** [comment]
AutoLayout 我觉得很方便。这可能要看你们产品对流畅度的要求。微信不也做的卡卡的。 然后可以从其他方面入手 (不一定非得针对autolayout) 。只要提高到你们觉得OK的流畅度不就可以了。

**Comment by wangbiye** [comment]
针对我的项目, 现在我能知道的卡顿原因是CPU负载过高, 基本上滑动的时候CPU都在90%以上, 甚至100多, 原因很大一部分是因为在滑动的过程中刷新了布局, 为了达到设计的效果除了上面文章提到的深度优化, 就是避免滑动的时候刷新布局, 不刷新布局就需要根据样式做出不动的cell, 如果是做不动的cell实在是太可怕了, 一个页面已经有9种完全不动的样式, 如果把部分不同的也区分开, 重新做一个cell, 估计就需要14种左右, 代码写着乱, 时间也更久, 想想都觉得太恐怖, 附上我司的一份设计稿, 可以围观一下, 有很多细节是文字说明, 设计稿没提现出来

![GitHub set up](http://ww2.sinaimg.cn/large/661902d8gw1ezikp9px4vj20hs6681ky.jpg)

**Comment by ibireme** [comment]
单看界面是蛮复杂的。。这种界面一定不要用 AutoLayout 和基于它的布局库。。

就我来说，可能会这么做：
1. 把每个重复的小视图独立出来成单独控件。
2. 把每个卡片当作一个 table section，卡片内的较为独立的小区域作为一个 table cell。比如，一条评论可以当做一个 Cell，赞助加星的工具条可以作为一个 Cell。
3. Cell 重新布局性能消耗是不大的，但布局时控件宽高、位置的计算需要挪到后台线程去。
4. 文本最好都改为异步绘制。
5. 圆角图片这块儿，看实现难度，最好也改为后台绘制。

**Comment by wangbiye** [comment]
谢谢, 我会根据我们的实际情况并根据你的建议去尝试
