### ISSUE TITLE
在dealloc里面执行定时器的invalidate是不会执行

### ISSUE THREAD

**Issue by norman452003** [ibireme/YYKit#67]
看到代码里面有的timer执行invalidate在dealloc里面执行，这种情况是不会进入dealloc里面的吧。得先invalidate才会进入dealloc方法吧

**Comment by PerryJump** [comment]
ARC自动调的dealloc,然后在里面释放掉定时器和KVO通知中心添加的观察者

**Comment by ibireme** [comment]
我搜索了一下，猜测你可能是指的 YYControl.m 里的代码。

YYControl 持有一个 timer，这个 timer 的 target 指向 YYControl 本身。为了打破这个循环引用，此处 timer 指向 target 时，是用的 YYWeakProxy 保证了弱引用。

这样 YYControl 就可以按照正常逻辑走入 dealloc 方法了。

**Comment by XuYanci** [comment]
是的。只要保证了弱引用即可。
