### ISSUE TITLE
非方形头像圆角显示问题

### ISSUE THREAD

**Issue by wonderffee** [ibireme/YYKit#68]
感觉代码中的圆角设置在非方形图片时有问题，从[这里](https://github.com/ibireme/YYKit/blob/5292e0da6b950960fd1b3a38ddd758ccbb46bd55/Demo/YYKitDemo/WBStatusCell.m)提取了关键代码做了一个简单的测试：
```objc
    UIImageView *_avatarView = [UIImageView new];
    _avatarView.size = CGSizeMake(40, 40);
    _avatarView.origin = CGPointMake(160, kWBCellPadding + 3);
    _avatarView.contentMode = UIViewContentModeScaleAspectFill;
    //    _avatarView.clipsToBounds = YES;
    [self.view addSubview:_avatarView];  //注意这里是self.view
    CALayer *avatarBorder = [CALayer layer];

    avatarBorder.frame = _avatarView.bounds;
    avatarBorder.borderWidth = CGFloatFromPixel(1);
    avatarBorder.borderColor = [UIColor colorWithWhite:0.000 alpha:0.090].CGColor;
    avatarBorder.cornerRadius = _avatarView.height / 2;
    avatarBorder.shouldRasterize = YES;
    avatarBorder.rasterizationScale = kScreenScale;
//    [avatarBorder setMasksToBounds:YES];
    [_avatarView.layer addSublayer:avatarBorder];
    
    [_avatarView setImageWithURL:[NSURL URLWithString:@"http://pic.qiushibaike.com/system/avtnew/1448/14486583/medium/20140311151742.jpg"] //profileImageURL
                                 placeholder:[UIImage imageNamed:@"defaultLogo"]
                                     options:kNilOptions
                                     manager:[QBStatusHelper avatarImageManager] //< 圆角头像manager，内置圆角处理
                                    progress:nil
                                   transform:nil
                                  completion:nil];
```

图像原图为：
![test](http://pic.qiushibaike.com/system/avtnew/1448/14486583/medium/20140311151742.jpg)

上面的代码显示效果：
![2016-01-02 12 11 50](https://cloud.githubusercontent.com/assets/4888291/12073186/152eb308-b14a-11e5-9772-6cd788bff26e.png)

我想这是_avatarView.clipsToBounds未设置为YES的原因，把上面代码中的第一个注释去掉，再运行显示效果如下：
![2016-01-02 12 15 07](https://cloud.githubusercontent.com/assets/4888291/12073192/85b31236-b14a-11e5-9973-d1defb5bb1e9.png)
可以看到现在是显示方形了，但是圆角没有了。我想这是圆角在frame之外被clip掉了？把上面代码中的第二个注释去掉也是一样的结果。

我更大的疑问是avatarBorder明明被设置了frame.size为（40，40），为什么addSublayer之后没有遵守这个size呢？求解惑

**Comment by ibireme** [comment]
那个 Demo 里，是假设了图片是方形的，并不适合非方形图片。

给图片加圆角的那个方法，只是按给定数值把图片的四个角裁去，并不会做其他事情。如果你希望把图片变成圆形，那需要先将图片裁成方形，再切圆角，或者自己重写方法把这两个操作合起来。

**Comment by wonderffee** [comment]
发现我被中间的代码给骗了，把代码中的setImageWithURL方法注释掉，换成SDWebImage的正常方法：
[_avatarView sd_setImageWithURL:[NSURL URLWithString:@"http://pic.qiushibaike.com/system/avtnew/1448/14486583/medium/20140311151742.jpg"] placeholderImage:[UIImage imageNamed:@"userDefaultLogo"] options:SDWebImageRetryFailed];

圆角效果是怎么也不会显示出来，然后我又取消setImageWithURL方法的注释，把中间avatarBorder的代码注释掉，会显示圆角效果。说明中间的代码根本就不会产生圆角效果，根据下面的注释，发现圆角实际是在[QBStatusHelper avatarImageManager]中直接对image进行的，真误导人啊😂

**Comment by wonderffee** [comment]
中间的代码应该完全可以删掉吧？

**Comment by ibireme** [comment]
最上面那些代码的逻辑是这样的：

1. 创建一个 UIImageView，仅设置一下 contentMode，其他不变。
2. 创建一个 CALayer，这个 layer 是透明的，但是加上了圆角和白色描边，用于盖在头像图片上面。
3. 设置图片，并在 WebImageManager 里给图片裁处一个圆角。

显示效果是一个圆形的头像，外边有一圈白色描边。

**Comment by wonderffee** [comment]
明白了，还是看得不够仔细
