### ISSUE TITLE
An question about YYAnimatedImageView.m

### ISSUE THREAD

**Issue by lumouren009** [ibireme/YYKit#69]
I have read the code of YYAnimatedImageView.m. There is a question about code below.
![image](https://cloud.githubusercontent.com/assets/3341797/12082030/63fc58dc-b2c6-11e5-8f2b-768af562cf45.png)

Why should you remove value  to the key ( @(nextIndex) ) in the buffer ?

**Comment by ibireme** [comment]
When `_incrBufferCount < _totalFrameCount`, it means that currently the buffer size should not larger than `_incrBufferCount` and it should remove some frame from buffer to keep the buffer size.
