### ISSUE TITLE
pod使用问题

### ISSUE THREAD

**Issue by wonderffee** [ibireme/YYKit#7]
发现只集成YYKit还不够，其它的库都是独立的
YYKeyboardManager
YYDispatchQueuePool
YYAsyncLayer 
上面三个库用pod search的结果都是unable to find
用的CocoaPods版本是0.39.0，应该是最新的吧，怎么还search不到呢？

**Comment by ibireme** [comment]
目前可以在 pod 中找到：

	$ pod search YYKeyboardManager
	-> YYKeyboardManager (0.9.0)
	   iOS utility class allows you to access keyboard view and track keyboard
	   animation.
	   pod 'YYKeyboardManager', '~> 0.9.0'
	   - Homepage: https://github.com/ibireme/YYKeyboardManager
	   - Source:   https://github.com/ibireme/YYKeyboardManager.git
	   - Versions: 0.9.0 [master repo]

	$ pod search YYDispatchQueuePool
	-> YYDispatchQueuePool (0.9.0)
	   iOS utility class to manage global dispatch queue.
	   pod 'YYDispatchQueuePool', '~> 0.9.0'
	   - Homepage: https://github.com/ibireme/YYDispatchQueuePool
	   - Source:   https://github.com/ibireme/YYDispatchQueuePool.git
	   - Versions: 0.9.0 [master repo]
	   
	$ pod search YYAsyncLayer
	-> YYAsyncLayer (0.9.0)
	   iOS utility classes for asynchronous rendering and display.
	   pod 'YYAsyncLayer', '~> 0.9.0'
	   - Homepage: https://github.com/ibireme/YYAsyncLayer
	   - Source:   https://github.com/ibireme/YYAsyncLayer.git
	   - Versions: 0.9.0 [master repo]

你可以尝试运行 `pod update -verbose` 更新 pod 引用，
如果还不行，可以添加 git 地址 

    pod 'YYKeyboardManager', :git => 'https://github.com/ibireme/YYKeyboardManager.git'

**Comment by wonderffee** [comment]
果然是有的，还是参数的问题，平常为了快都只用pod update --verbose --no-repo-update
