### ISSUE TITLE
手动导入后报错

### ISSUE THREAD

**Issue by swsdyg** [ibireme/YYKit#70]
你好，我手动导入的yykit这个框架，但不知道为什么会报这样的错误，不应该使用下面的双引号导入的方式吗
<img width="731" alt="2016-01-04 12 34 40" src="https://cloud.githubusercontent.com/assets/8267484/12083512/c41ae29c-b2df-11e5-8088-3321c105c867.png">

**Comment by ibireme** [comment]
那这说明此处代码能够用 `<YYKit/YYKit.h>` 来引用到 YYKit.h 头文件，但其他头文件却引用不到。

试试 Clean 工程、清空 Derived Data 缓存，然后重启 Xcode。如果还有问题，再检查一下编译选项中的 Framework Search Path 等配置项目。

**Comment by swsdyg** [comment]
Clean 工程、清空 Derived Data 缓存，然后重启 Xcode了，还是不行，这是Framework Search Path的配置，不知道有没有问题

<img width="500" alt="2016-01-04 1 44 38" src="https://cloud.githubusercontent.com/assets/8267484/12084087/5cb77f3e-b2e9-11e5-86dc-dd8441741b7f.png">

**Comment by ibireme** [comment]
那写一个 #import <YYKit/YYKit.h> 看看是否报错，如果没报错那就检查一为什么 YYKit.h 这个头文件会以这种方式引入。

比如检查一下 Search Paths 那几个配置、检查一下 YYKit 文件夹是怎么导入的、放到了哪里、检查下 YYKit.h 是否有重复等等。

**Comment by XuYanci** [comment]
看一下你工程设置里面有没有Include这个目录进来。

**Comment by yuyanghui** [comment]
解决了吗？我也遇到这个问题
