### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by BestKai** [ibireme/YYKit#71]
![1ff75321-654d-4bc7-b4fc-c91a9d29bdef](https://cloud.githubusercontent.com/assets/8436462/12109886/4966c862-b3c1-11e5-8d45-ece385e9a8ea.png)

前几天都没事，今天突然会发生内存泄露造成崩溃，分析了下在这行代码？用的是YYTextView。text为emoji表情。

**Comment by ibireme** [comment]
我用 Instuments 测试了下 Leak，内存占用一直很平稳。。仔细检查了下这块儿的代码逻辑，也拿 Analyze 跑了一遍，暂时也没看出内存问题。。

能提供一下你在使用这个类时的相关代码片段和内存泄漏分析方法吗？有没有可能是 YYTextLayout 或 YYTextView 被其他对象引用了？

**Comment by BestKai** [comment]
我再找找问题吧，奇怪的是只有我的手机有问题，其他几个都没问题。

**Comment by ibireme** [comment]
对了。。如果是测试内存问题，不要直接用 Xcode Run 来调试，Xcode 的调试会造成内存问题。用 Instruments 来测试更准确。

**Comment by BestKai** [comment]
嗯嗯，我再找找问题。非常感谢

**Comment by mrhyh** [comment]
问题找到了吗？ @BestKai

**Comment by BestKai** [comment]
@mrhyh 不好意思，很久的问题了，忘记怎么解决了。用Instruments再检查下自己的代码吧。
