### ISSUE TITLE
RunLoop的Mode关系

### ISSUE THREAD

**Issue by yangchao0033** [ibireme/YYKit#72]
```objc
struct __CFRunLoopMode {
    CFStringRef _name;            // Mode Name, 例如 @"kCFRunLoopDefaultMode"
    CFMutableSetRef _sources0;    // Set
    CFMutableSetRef _sources1;    // Set
    CFMutableArrayRef _observers; // Array
    CFMutableArrayRef _timers;    // Array
    ...
};
 
struct __CFRunLoop {
    CFMutableSetRef _commonModes;     // Set
    CFMutableSetRef _commonModeItems; // Set<Source/Observer/Timer>
    CFRunLoopModeRef _currentMode;    // Current Runloop Mode
    CFMutableSetRef _modes;           // Set
    ...
};
```
你好 我想问一下modes和_commonModes是包含关系还是相交关系，common是作为mode的一种标记还是单独的一个属性呢？
下面是我画的结构图
![结构图](https://github.com/yangchao0033/blog/blob/6e7217092eb3037924f591e975cb55bc1f65234d/ios/2015/12/Image/Snip20160106_3.png?raw=true)

**Comment by ibireme** [comment]
在 RunLoop 内部，逻辑大概是这样的：

1. 把一个 Source/Observer/Timer 加入到指定的 Mode 中时，RunLoop 会找到那个对应的 __CFRunLoopMode，然后加到它内部的容器去。
2. 把一个 Source/Observer/Timer 加入到 CommonModes 中时，RunLoop 会加入到最顶层的 __CFRunLoop 容器中去。
3. RunLoop 运行在某个 Mode 时，它会把当前 Mode 中的 Source/Observer/Timer 和 最顶层 __CFRunLoop 中那些 commonModeItems 并起来使用。

**Comment by yangchao0033** [comment]
看来他们的关系不是想象的那么简单，我再看看runloop的内部原理的那段代码。
