### ISSUE TITLE
请教NSAttributedString (YYText)里一个方法的困惑

### ISSUE THREAD

**Issue by heeween** [ibireme/YYKit#73]
看你的代码好几天了 学习了不少 大神厉害.其中NSAttributedString (YYText)中,其中给属性字符串设置阴影属性这个方法,如下.
- (void)setTextShadow:(YYTextShadow *)textShadow range:(NSRange)range {
    [self setAttribute:YYTextShadowAttributeName value:textShadow range:range];
}
- (void)setAttribute:(NSString *)name value:(id)value range:(NSRange)range {
    if (!name || [NSNull isEqual:name]) return;
    if (value && ![NSNull isEqual:value]) [self addAttribute:name value:value range:range];
    else [self removeAttribute:name range:range];
}

我有个疑问设置阴影最后调用了系统的这个方法
- (void)addAttribute:(NSString *)name value:(id)value range:(NSRange)range;
可是你传入的name是YYTextShadowAttributeName = @"YYTextShadow"是个自己定的字符串,value是自己定义的YYTextShadow对象,系统怎么会接收这么个性化自定义的东西?
- (void)addAttribute:(NSString *)name value:(id)value range:(NSRange)range;这个方法接收的参数又有什么规律呢?想了好久不得其解,不知道我说清楚问题了没,忘解答.

**Comment by ibireme** [comment]
NSAttributedString 这个类并没有任何限制，它可以接受任意的 key-value pair。

CoreText/UIKit 在绘制时，只会去取 CoreText/UIKit 中定义好的那些key-value，而忽略其他的东西。YYText 则用到了一些额外自定义的属性来实现一些额外内容的绘制。

**Comment by heeween** [comment]
恩 多谢回复

**Comment by 171chen** [comment]
请问- (void)addAttribute:(NSString *)name value:(id)value range:(NSRange)range;
这个函数如果value是一个复杂的数组、元素是一个数据模型，在UITableview的cell里面使用的时候资源开销是不是很大？

**Comment by ibireme** [comment]
@171chen 这个只是 AttributedString 中保存的数据，对 cell 开销没有任何影响。

**Comment by 171chen** [comment]
[attributeText addAttribute:@"specileTexts" value:str range:NSMakeRange(0, 1)];
这个函数里，如果我的value是一个元素是一个数据模型的数组的话，在滑动tableview时会很卡，但转化为json格式后就流畅多了，可以解释一下吗，谢谢

**Comment by ibireme** [comment]
这需要用 Instruments 定位一下卡顿的地方，光凭这些信息猜测的话可能是不准确的。
