### ISSUE TITLE
YY大神，你好！请教一个关于圆形图片的问题

### ISSUE THREAD

**Issue by CoderDKBai** [ibireme/YYKit#76]
给image写的一个分类，获取圆形图片，不过这种方式获得的图片有锯齿，请问如果才能去掉锯齿？
百度  google了好多，都没找到解决方法，看了你的YYImage(Add)，还是没搞清楚怎么去掉锯齿，望有时间帮忙看一下，多谢！

    CGFloat centerImageWH = MIN(self.size.width, self.size.height);
    CGFloat centerImageX = ((self.size.width - self.size.height) > 0) ? (self.size.width - self.size.height) * 0.5 : 0;
    CGFloat centerImageY = ((self.size.height - self.size.width) > 0) ? (self.size.height - self.size.width) * 0.5 : 0;
    CGRect centerImageRect = CGRectMake(centerImageX, centerImageY, centerImageWH, centerImageWH);
    CGImageRef centerImageRef = CGImageCreateWithImageInRect(self.CGImage, centerImageRect);
    UIImage *centerImage = [UIImage imageWithCGImage:centerImageRef scale:self.scale orientation:self.imageOrientation];
    CGImageRelease(centerImageRef);
    
    UIGraphicsBeginImageContextWithOptions(centerImage.size, NO, centerImage.scale);
    CGContextRef newContext = UIGraphicsGetCurrentContext();
    CGRect newRect = CGRectMake(0, 0, centerImage.size.width, centerImage.size.height);
    CGContextAddEllipseInRect(newContext, newRect);
    CGContextClip(newContext);
    [centerImage drawInRect:newRect];
    UIImage *circleImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return circleImage;

**Comment by ibireme** [comment]
没太仔细看代码。。
处理图片后出现锯齿一般是 image 或者 context 的 scale 没有设置好，检查一下这个看看。

**Comment by redye** [comment]
这里将图片绘制成圆形是不是只针对正方形图片，因为我使用了一张长宽比例大于1的图片，显示出来的就不是圆形了

**Comment by ibireme** [comment]
UIImage(YYAdd) 那里面的方法，只是给图片加圆角，并不是裁剪圆形图片。

**Comment by redye** [comment]
了解了
