### ISSUE TITLE
UIDevice+YYAdd.h 莫名的出现 Expected ')'

### ISSUE THREAD

**Issue by czwen** [ibireme/YYKit#78]
![screen shot 2016-01-11 at 14 50 45](https://cloud.githubusercontent.com/assets/3235796/12228190/be695cf0-b872-11e5-87b3-786746ac150a.png)

**Comment by ibireme** [comment]
我在做其他项目时也遇到过几次类似的问题，看似没问题的代码却被提示有编译错误。通常这是整个项目中某处代码有问题（比如某个类的定义缺少了 @end），而编译时 Xcode 没能正确判断错误的位置，误认为是其他头文件产生的错误。检查一下最近修改的代码中是否有错误，然后改一下看看。

当然这也可能是其他我不知道的原因。。

**Comment by czwen** [comment]
我是一次性 #import <YYKit/YYKit.h> 就会 出现，单独import文件不会。
而且不引入不报错

**Comment by ibireme** [comment]
那就不清楚了。。目前没有检查到 YYKit 头文件的问题。。

**Comment by ibireme** [comment]
好吧，今天我在改头文件时也遇到了，但它的错误提示指到了一个空行上。
我清空了缓存，还原了头文件，然后再重新编译，错误就消失了。

可以肯定是 Xcode 的问题。。

**Comment by czwen** [comment]
缓存我也清过无数遍了，现在只能把需要的单独加上。BTW，YYKit 很好用很👍，感激作者
