### ISSUE TITLE
diskCache

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYKit#81]
用了YYWebImage下载图片之后。我想知道。没有读取缓存大小的方法吗。或是我没找到。。
我拿到你的[[YYWebImageManager sharedManager] cache].diskCache.path.然后读取这个路径获取的。

**Comment by ibireme** [comment]
有访问缓存的方法。
我刚在 readme 里加了一段说明：https://github.com/ibireme/YYWebImage#图片缓存

**Comment by 597579501** [comment]
thx 。YY大神。最近受你影响挺大的。谢谢你让我重获新生。我这么屌丝的一个问题也让更新了说明。

**Comment by 597579501** [comment]
其实那天我已经看出来大概是你描述的意思。我一直在纠结一个问题就是。我浏览图片的时候。发现你创建缓存文件夹里有个manifest.sqlite-wal这个在变大。但是他一直没有变小。我想知道这个东西是用来做什么的

**Comment by ibireme** [comment]
这个文件是 SQLite 的 WAL(Write Ahead Logging) 机制产生的文件。简单说这是一个日志文件，它里面的内容会定时刷新到 sqlite 文件内。具体资料你可以在网上搜一下 `SQLite WAL`。
