### ISSUE TITLE
YYPhotoGroupView的提问

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYKit#82]
大概问题是这样。微博的那个demo。也许是因为微博只是9图原因。YY大神没有考虑进去。那么如果。9图的时候。其中上面6图是在屏幕上方的。而我点击预览是下面3张图。当我通过photoGroupView滑动到第一张的时候返回。我觉得列表也应该在返回的视图内。那么应该如何计算这个位置。

**Comment by 597579501** [comment]
另外额外请教一下。你是如何看待collectionView。因为我发现无论多复杂的视图你都基于tableview去弄。

**Comment by ibireme** [comment]
这个需要在 YYPhotoGroupView 准备 dismiss 的地方加一个回调，通知到所在的 TableView。dismiss 时计算一下缩放到的视图位置与 TableView 的 offset，如果视图位置被挡住，那就可以调用 TableView 的方法直接设置一个新的 offset。

CollectionView 机制和 TableView 一样，但是更完整更复杂。我更习惯用 TableView，TableView 实现困难时再用 CollectionView。

**Comment by zenghaojim33** [comment]
关于这个类我也有些疑惑，在好几个地方用到了CATransaction，请问用意是什么呢，望赐教

**Comment by ibireme** [comment]
用 CATransaction 禁用 CALayer 的隐式动画。

**Comment by zenghaojim33** [comment]
使用CATransaction禁用隐式动画我知道，但是有些地方似乎没看出有什么效果

比如说下面这一句（188行）
```objective-c  
[CATransaction begin];
[CATransaction setDisableActions:YES];
_imageView.frame = _imageContainerView.bounds;
 [CATransaction commit];
```
将这里的事务去掉并没看出有什么影响。事务貌似只会对单独创建的CALayer有影响，对UIView中的layer没有影响

**Comment by 597579501** [comment]
这个动画我也调了好久。。平时和这些接触的太少了。总算调好了。但是我拿这个YYPhotoGroupView是用做无限列表的地方。如果滑倒下一页。YYPhotoGroupView item也addObjectsFromArray.那么问题来了。如果我滑动了20页。。。然后假如的item就有400个的时候。。。明显是不正确的意思。要循环200个YYPhotoGroupItem总会卡那么一下。后面又试着改。只加载当前点击前后的三个对象。每次滑动就update一下YYPhotoGroupView的items了。。。这个思路应该是对的。。。然后。。。点击返回的动画没了

**Comment by ibireme** [comment]
@zenghaojim33 哦，这块儿应该是多写了，或者之前有过什么 layer 操作后来删掉了。。
@597579501 无限列表的话，应该得多改改了，或者得重新写一份新的东西了。。

**Comment by 597579501** [comment]
@ibireme 我改到现在。。。还没改好。我都想放弃了。。主要项目时间太紧张了。怕来不及。又想用你的。真是纠结。

**Comment by 597579501** [comment]
[_pager setHidden:YES].貌似隐藏不了呢

**Comment by ibireme** [comment]
可能与 pager.hidesForSinglePage 这个属性有关。

**Comment by 597579501** [comment]
如果说YYimageView加载缩略图。。我想判断是否有本地非缩略图的缓存。如果有直接加载image.image(非缩略图)。如果没有就加载image.thumbnailImage(缩略图)。

**Comment by xujianbo12345** [comment]
请教YY大神，为啥这个用在基于UICollectionView的视图里面时不能正确的获取点击图片的初始位置，每次都是从最左上角弹出放大图片？

**Comment by lee0000** [comment]
回复：xujianbo12345
ComAddImgCell *cell = (ComAddImgCell *)[collectionView cellForItemAtIndexPath:indexPath];
  
    NSMutableArray *items = [NSMutableArray new];
    
    for (NSUInteger i = 0; i < _chatCellVM.images.count; i++) {
        ComuV3ChatImageInfo *imageInfo = _chatCellVM.images[i];
        YYPhotoGroupItem *item = [YYPhotoGroupItem new];
        item.largeImageURL = [NSURL URLWithString:imageInfo.key];
        item.largeImageSize = CGSizeMake(imageInfo.width, imageInfo.height);
        
        NSIndexPath *wholeNSIndexPath = [NSIndexPath indexPathForRow:i inSection:0];
        ComAddImgCell *currentCell = (ComAddImgCell *)[collectionView cellForItemAtIndexPath:wholeNSIndexPath];
        item.thumbView = currentCell.postImg;
        
        [items addObject:item];
    }
    
    YYPhotoGroupView *v = [[YYPhotoGroupView alloc] initWithGroupItems:items];
    [v presentFromImageView:cell.postImg toContainer:[UIApplication sharedApplication].keyWindow animated:YES completion:nil];

**Comment by liliangde** [comment]
你好 ，咨询下，在预览图片的时候，如果tableView滚到最下面，在dismiss 的时候 会发现原来的tableView向上偏移了 statusBar的高度，如果在预览的时候不隐藏statusBar就不会出现这个问题是咋回事儿额？
