### ISSUE TITLE
插入图片后再插入文字问题

### ISSUE THREAD

**Issue by zuocai1993** [ibireme/YYKit#83]
YY大神你好，YYText  确实是一个好作品，我在使用过程中遇到一个问题。插入图片后在插入文字  文字会变小。
下面是我插入图片的代码。
![image](https://cloud.githubusercontent.com/assets/16344283/12376897/b39454e8-bd44-11e5-8091-489a92ccfb29.png)

**Comment by ibireme** [comment]
首先确认一下 textView 是否有设置 textParser、textParser 是否错误处理了字符串属性。
之后在设置了 attributedText 后，打印一下 textView.attributedText 属性，看看样式有问题部分的文本属性。

**Comment by zuocai1993** [comment]
还是不好使，我直接在你的demo 上进行修改的  还是有这个问题。我可以把修改的文件发给你帮我看看吗

**Comment by zuocai1993** [comment]
// 监听输入代理
- (BOOL)parseText:(NSMutableAttributedString *)text selectedRange:(NSRangePointer)selectedRange{
    NSLog(@"text====%@",text);
//    NSDictionary *dic = @{NSFontAttributeName:[UIFont systemFontOfSize:40]};
//    NSMutableAttributedString *test2 = [[NSMutableAttributedString alloc]initWithString:@"asdasda" attributes:dic];
//    
//    [_testStr appendAttributedString:test2];
//_textView.attributedText = _testStr;
    
    return YES;
}
// 添加图片按钮
- (void)click:(id)sender{
    
    UIImage *image = [UIImage imageNamed:@"dribbble256_imageio"];
    
    NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:[UIFont systemFontOfSize:16] alignment:YYTextVerticalAlignmentCenter];
    
    [_testStr appendAttributedString:attachText];
    
    _textView.attributedText = _testStr;

}

- (void)viewDidLoad {
    [super viewDidLoad];
    [self textView];
    self.navigationItem.rightBarButtonItem =[[UIBarButtonItem alloc]initWithTitle:@"1111" style:UIBarButtonItemStyleDone target:self action:@selector(click:)];
  
}

// 初始化
- (void)textView{
    _textView = [[YYTextView alloc]initWithFrame:self.view.bounds];
    _textView.textParser =self;
    [self.view addSubview:_textView];
    
    NSDictionary *dic = @{NSFontAttributeName:[UIFont systemFontOfSize:40]};
    _testStr = [[NSMutableAttributedString alloc]initWithString:@"" attributes:dic];
    
    UIImage *image = [UIImage imageNamed:@"dribbble256_imageio"];
    
    NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:[UIFont systemFontOfSize:16] alignment:YYTextVerticalAlignmentCenter];
    
    [_testStr appendAttributedString:attachText];
    
    NSMutableAttributedString *test2 = [[NSMutableAttributedString alloc]initWithString:@"vjijgioeqjro" attributes:dic];
    
    [_testStr appendAttributedString:test2];
    _textView.attributedText = _testStr;
    _textView.backgroundColor = [UIColor whiteColor];
}

**Comment by ibireme** [comment]
parser 里面貌似什么都没做啊？

你可以打印一下 textView.attributedText 看看，字体不对的范围，应该是没有设置字体、或者字体大小有问题。重新设置一下就行。

**Comment by zuocai1993** [comment]
我打印 textView.attributedText  字号 始终都是正确的   ，  我在初始化的时候给 NSMutableAttributedString  初始化了属性  40号字体， 不晓得为什么  这个问题困惑了我很久，还忘指点。

**Comment by zuocai1993** [comment]
问题已经找到，感谢解答，YYtextview 我能不能改他的偏移度，就是输入文字 他会一直往上移动  保证最后一行字不被键盘挡住 这个高度能调整吗

**Comment by ibireme** [comment]
试试这几个属性：extraAccessoryViewHeight、textContainerInset、contentInset。

**Comment by godsoul** [comment]
[https://camo.githubusercontent.com/e6cafb0155aa51b064b55733779c4590cba355a7/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323530353431312f313237363934392f39373035303838342d326561302d313165332d383963662d3062636466643863663232352e6a7067](url)

**Comment by godsoul** [comment]
![](https://camo.githubusercontent.com/e6cafb0155aa51b064b55733779c4590cba355a7/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323530353431312f313237363934392f39373035303838342d326561302d313165332d383963662d3062636466643863663232352e6a7067)

**Comment by GMCoder** [comment]
我在加入图片之后文字也变小了 我猜是attributedString的问题  能说一下你怎么解决的吗 @zuocai1993
