### ISSUE TITLE
Version question

### ISSUE THREAD

**Issue by zdrzdr** [ibireme/YYKit#88]
为什么今天 pod search YYKit最新才是 0.9.11？你修改后以后几天都是0.9.10。

**Comment by ibireme** [comment]
是 0.9.11 啊。。
https://github.com/ibireme/YYKit/releases

**Comment by zdrzdr** [comment]
我在命令行执行的pod search YYKit，前几天都是0.9.11.

**Comment by ibireme** [comment]
更新一下 pod：`pod update`
最新应该是 0.9.11。
