### ISSUE TITLE
Masonry和YYKit 不兼容

### ISSUE THREAD

**Issue by ampm** [ibireme/YYKit#9]
同时集成Masonry和YYKit 
举例：Masonry 中的类似以下代码make.left.equalTo(_testView2.right) 一句会导致Masonry报 attempting to add unsupported attribute错

[_testView makeConstraints:^(MASConstraintMaker *make) {
    make.centerY.equalTo(_container);
    make.left.equalTo(_testView2.right).offset(5);
    make.width.equalTo(120);
    make.height.equalTo(32);
}];

**Comment by ibireme** [comment]
YYKit 中有很多 Category，为了方便我自己使用和保持代码美观，这些 Category 都没有加代码前缀，所以可能会和其他某些库造成冲突，这个我在 readme 里也说明了。

推荐用那些拆分出来的子项目：除了 YYCategories 之外，所有子项目的 Category 里都有 `yy_` 前缀，至少能保证不会产生这种冲突问题。

**Comment by ampm** [comment]
恩 看到了 是UIView+YYAdd里面的冲突导致的
