### ISSUE TITLE
关于OSSpinLock安全

### ISSUE THREAD

**Issue by rogerjinHub** [ibireme/YYKit#90]
我看你代码里很多地方用了OSSpinLock 这个锁，但是http://blog.ibireme.com/2016/01/16/spinlock_is_unsafe_in_ios/ 这篇文章说OSSpinLock不再安全，如果用了你的代码，确信不会出问题？

**Comment by ibireme** [comment]
已经都改掉了。。
而且，就算用 OSSpinLock 出问题的概率也很小，至少我目前没有测试出来。。
