### ISSUE TITLE
CPU达到100%

### ISSUE THREAD

**Issue by cloudhm** [ibireme/YYKit#93]
将Model转化成Layout模型时CPU会达到100%，页面卡死。需要转化的模型数量越多，需要的时间越长。求解。

**Comment by ibireme** [comment]
这当然要放到后台线程执行咯。。

**Comment by cloudhm** [comment]
谢谢，界面不会卡死了。但是CPU仍然会占用100%，有办法优化吗？

**Comment by ibireme** [comment]
CPU 就是拿来用的啊，不然留着干什么。。如果在处理任务时 CPU 不能全力运作，那属于劣化了吧。

**Comment by cloudhm** [comment]
非常感谢，问题解决了。
