### ISSUE TITLE
YYKeychain

### ISSUE THREAD

**Issue by diyinqianchang** [ibireme/YYKit#95]
[YYKeychain setPassword:@"xxxxx" forService:@"xxxxxxxx" account:@"xxxxxxx" error:&error];
用这个的时候直接崩溃了

-[__NSCFDictionary objectAtIndexedSubscript:]:

#import "YYKeychain.m"      392行

**Comment by ibireme** [comment]
合并到这个问题吧：https://github.com/ibireme/YYKit/issues/96
