### ISSUE TITLE
YYKeychain

### ISSUE THREAD

**Issue by lichenglong001** [ibireme/YYKit#96]
+ (BOOL)updateItem:(YYKeychainItem *)item error:(__autoreleasing NSError **)error {
    NSMutableDictionary *query = [item queryDic];
    NSMutableDictionary *update = [item dic];
    // 添加  [update removeObjectForKey:@"class"];// kSecClass不可改,否则报错-50

+ (YYKeychainItem *)selectOneItem:(YYKeychainItem *)item error:(__autoreleasing NSError **)error {
    NSMutableDictionary *query = [item dic];
    query[(__bridge id)kSecMatchLimit] = (__bridge id)kSecMatchLimitOne;
    query[(__bridge id)kSecReturnAttributes] = @YES;
    // 添加 query[(__bridge id)kSecReturnData] = @YES;// kSecReturnAttributes不会返回password

+ (BOOL)setPassword:(NSString *)password  forService:(NSString *)serviceName account:(NSString *)account error:(__autoreleasing NSError **)error {
    // ......
    if (result) {
        result.password = password;
        return [self updateItem:result error:error];
    } else {
        // 添加 item.password = password;// 否则并不能插入密码
        return [self insertItem:item error:error];
    }
}

**Comment by diyinqianchang** [comment]
是不是也发现了这个"YYKeychain.h"的一些问题

**Comment by ibireme** [comment]
擦。。我应该把这个类删掉，先写一遍 test case 的。。这个类很早之前写的，简单用了几下也没仔细测试，问题可能蛮多的。。

访问 keychain这个功能还是推荐用 SSKeychain。

**Comment by lichenglong001** [comment]
结构看上去比ss清晰，而且也没发现其它错误。

**Comment by ibireme** [comment]
呃。。好吧，我抽空写一遍 testcase，修复一下可能的问题。
