### ISSUE TITLE
使用Cocoapods导入框架后编译报错library not found for -lYYKit

### ISSUE THREAD

**Issue by jvjishou** [ibireme/YYKit#97]
导入版本（0.9.11）
具体报错信息：
Ld /Users/a002/Library/Developer/Xcode/DerivedData/YYKit-Demo-dgqzavevxuwmdwczaspqjrvruaoz/Build/Products/Debug-iphonesimulator/YYKit-Demo.app/YYKit-Demo normal x86_64
    cd /Users/a002/Desktop/desp/代码联系/YYKit-Demo
    export IPHONEOS_DEPLOYMENT_TARGET=9.2
    export PATH="/Applications/Xcode7.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode7.2.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode7.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode7.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -L/Users/a002/Library/Developer/Xcode/DerivedData/YYKit-Demo-dgqzavevxuwmdwczaspqjrvruaoz/Build/Products/Debug-iphonesimulator -F/Users/a002/Library/Developer/Xcode/DerivedData/YYKit-Demo-dgqzavevxuwmdwczaspqjrvruaoz/Build/Products/Debug-iphonesimulator -F/Users/a002/Desktop/desp/代码联系/YYKit-Demo/Pods/YYKit/Vendor -filelist /Users/a002/Library/Developer/Xcode/DerivedData/YYKit-Demo-dgqzavevxuwmdwczaspqjrvruaoz/Build/Intermediates/YYKit-Demo.build/Debug-iphonesimulator/YYKit-Demo.build/Objects-normal/x86_64/YYKit-Demo.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.2 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lYYKit -lsqlite3 -lz -framework Accelerate -framework AssetsLibrary -framework CoreFoundation -framework CoreGraphics -framework CoreImage -framework CoreText -framework ImageIO -framework MobileCoreServices -framework QuartzCore -framework SystemConfiguration -framework UIKit -framework WebP -fobjc-arc -fobjc-link-runtime -lPods -Xlinker -dependency_info -Xlinker /Users/a002/Library/Developer/Xcode/DerivedData/YYKit-Demo-dgqzavevxuwmdwczaspqjrvruaoz/Build/Intermediates/YYKit-Demo.build/Debug-iphonesimulator/YYKit-Demo.build/Objects-normal/x86_64/YYKit-Demo_dependency_info.dat -o /Users/a002/Library/Developer/Xcode/DerivedData/YYKit-Demo-dgqzavevxuwmdwczaspqjrvruaoz/Build/Products/Debug-iphonesimulator/YYKit-Demo.app/YYKit-Demo

ld: library not found for -lYYKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

收到导入框架使用YYTextView的时候报错如下：Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of 。
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    YYTextView *textView = [[YYTextView alloc] init];
//    [self.view addSubview:textView];
//    textView.width = self.view.width;
//    textView.height = 200;
//    textView.left = 0;
//    textView.top = 0;
//    textView.placeholderText = @"请输入反馈意见";
}

把YYTextView去掉正常。

**Comment by ibireme** [comment]
清空缓存、更新 CocoaPods 命令行工具、更新 pod 列表，更新 YYKit 代码。

如果没问题，YYTextEffectWindow 里应该有下面这个函数：https://github.com/ibireme/YYKit/blob/master/YYKit/Text/Component/YYTextEffectWindow.m#L42-L55
