### ISSUE TITLE
YYScreenSize() 无法合理应对屏幕旋转的调整，iPad分屏的屏幕调整

### ISSUE THREAD

**Issue by WeeTom** [ibireme/YYKit#98]
大神怎么看？

**Comment by ibireme** [comment]
这个函数本身就是返回屏幕的宽高，并且不考虑屏幕旋转，函数注释上有描述：Get main screen's size. Height is always larger than width.

如果要获得 App 窗口的大小，那直接用 UIApplication 的 window bounds 就可以了。

**Comment by WeeTom** [comment]
OK sorry 搞错了，因为demo里都是用YYScreenSize 去控制Cell 尺寸的，被牵着走了~
