### ISSUE TITLE
YYKitDemo 在ios7 下出错

### ISSUE THREAD

**Issue by qylibohao** [ibireme/YYKit#99]
运行weibo例子，在发帖页面点击#号按钮或者点击发送自定义表情就崩溃.
定位到代码如下
[_innerText replaceCharactersInRange:NSMakeRange(_selectedTextRange.end.offset, 0) 
withString:markedText];

**Comment by ibireme** [comment]
我手头有一个 iOS7.1 的 iPad，并不能复现。

这可能需要你提供设备、系统版本号、YYKit 版本号、崩溃时的调用栈（或崩溃日志）等信息，才能定位。

**Comment by qylibohao** [comment]
iphone5 ios7.1.1 ,YYKit 是昨天下的最新版。
![tmp20c34228](https://cloud.githubusercontent.com/assets/5283516/12602073/54326e3c-c4e1-11e5-8466-036128207a6d.png)

**Comment by ibireme** [comment]
那个 BI_ 开头的几个回调是什么东西。。这难道是百度输入法之类的东西？话说系统是否越狱了？

**Comment by qylibohao** [comment]
切换输入法试了下，我用的是百度输入法，点击导致的崩溃。切换回系统的就没事。何解呢？

**Comment by ibireme** [comment]
那肯定是越狱了。。唉这第三方输入法。。话说它们应该只适配了 UITextView/UITextField 吧。。这我也没办法了。。
